/*
 * Copyright 2024 M-Way Solutions GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ---
 *
 * APP_68_Fintech_ChurnPredictor
 *
 * This application provides a service to predict customer churn for financial technology
 * companies. It analyzes customer interaction history, transaction patterns, and performs
 * sentiment analysis on support communications to generate a churn probability score.
 *
 * LEGAL DISCLAIMER:
 * This software is provided "as is" without warranty of any kind, express or implied.
 * The predictions generated by this service are for informational purposes only and
 * should not be used as the sole basis for business decisions. The accuracy of
 * predictions is not guaranteed. The service must be configured and used in compliance
 * with all applicable laws and regulations, including data privacy and consumer
 * protection laws.
 */

import fastify, { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { randomUUID } from 'crypto';
import { z } from 'zod';
import {
    CoreSDK,
    Logger,
    ConfigManager,
    ServiceMetrics,
    AuditLogger,
} from '@core/sdk';
import { AuthService, AuthStrategy } from '@core/auth';
import { EventBus, Event, CloudEvent } from '@core/events';
import { Ontology } from '@core/ontology';

// --- AGENT METADATA (MACHINE-READABLE) ---
const agent_metadata = {
    agent_id: 'APP_68_Fintech_ChurnPredictor',
    purpose: 'Predicts customer churn risk for fintech services by analyzing interaction history and support ticket sentiment.',
    dependencies: [
        'core-sdk',
        'core-auth',
        'core-events',
        'core-ontology',
        'sentiment-analysis-provider-api',
        'predictive-modeling-provider-api',
        'customer-data-source-api',
    ],
    invalidation_conditions: [
        'Significant drift in underlying customer behavior patterns.',
        'Deprecation of integrated AI model APIs (e.g., OpenAI, Google Vertex AI).',
        'Changes in data privacy regulations affecting input features.',
    ],
    adjacent_apps: [
        'APP_25_Support_TicketSummarizer',
        'APP_41_Analytics_CustomerLTV',
        'APP_55_Marketing_TargetedCampaignEngine',
    ],
};

// --- CONFIGURATION ---
const config = new ConfigManager({
    port: { env: 'PORT', type: 'number', default: 3068 },
    logLevel: { env: 'LOG_LEVEL', type: 'string', default: 'info' },
    openaiApiKey: { env: 'OPENAI_API_KEY', type: 'string', secret: true },
    anthropicApiKey: { env: 'ANTHROPIC_API_KEY', type: 'string', secret: true },
    googleApplicationCredentials: { env: 'GOOGLE_APPLICATION_CREDENTIALS', type: 'string', secret: true },
    huggingfaceApiKey: { env: 'HUGGINGFACE_API_KEY', type: 'string', secret: true },
    defaultSentimentProvider: { env: 'DEFAULT_SENTIMENT_PROVIDER', type: 'string', default: 'openai' },
    defaultPredictionModel: { env: 'DEFAULT_PREDICTION_MODEL', type: 'string', default: 'vertex-ai-gb' },
    jurisdictionFeatureFlags: { env: 'JURISDICTION_FEATURE_FLAGS', type: 'json', default: { 'EU': { 'disable_text_analysis': true } } },
});

// --- CORE SERVICES INITIALIZATION ---
const core = new CoreSDK({
    appName: agent_metadata.agent_id,
    configManager: config,
});
const logger: Logger = core.getLogger();
const metrics: ServiceMetrics = core.getMetrics();
const audit: AuditLogger = core.getAuditLogger();
const authService = new AuthService({
    strategy: AuthStrategy.JWT,
    jwtSecret: config.get('JWT_SECRET'),
});
const eventBus = new EventBus({
    connectionString: config.get('EVENT_BUS_CONNECTION_STRING'),
});

// --- ONTOLOGY & DATA CONTRACTS ---
const CustomerInteractionSchema = z.object({
    type: z.enum(['transaction', 'login', 'support_ticket', 'feature_use']),
    timestamp: z.string().datetime(),
    metadata: z.record(z.any()),
});

const ChurnPredictionRequestSchema = z.object({
    customerId: z.string().uuid(),
    jurisdiction: z.string().optional().default('US'),
    modelConfig: z.object({
        predictionModelId: z.string().optional(),
        sentimentProviderId: z.string().optional(),
    }).optional(),
    interactions: z.array(CustomerInteractionSchema).min(1),
});

type ChurnPredictionRequest = z.infer<typeof ChurnPredictionRequestSchema>;
type CustomerInteraction = z.infer<typeof CustomerInteractionSchema>;

interface ChurnPredictionResult {
    jobId: string;
    customerId: string;
    status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
    churnProbability: number | null;
    riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | null;
    contributingFactors: string[];
    modelUsed: string;
    sentimentAnalysis: {
        provider: string;
        averageScore: number;
        analyzedTickets: number;
    } | null;
    cost: {
        sentimentTokens: number;
        predictionUnits: number;
        totalMicroCents: number;
    };
    error?: string;
    createdAt: string;
    completedAt?: string;
}

// --- IN-MEMORY JOB STORE (for demonstration; replace with Redis/DB) ---
const jobStore = new Map<string, ChurnPredictionResult>();

// --- AI VENDOR ADAPTERS ---
// Tension: Cost vs. Quality/Nuance in sentiment analysis. OpenAI might be more nuanced but expensive.
interface SentimentAnalysisProvider {
    readonly id: string;
    analyze(texts: string[]): Promise<{ scores: number[], tokens: number }>;
}

class OpenAISentimentAdapter implements SentimentAnalysisProvider {
    id = 'openai-gpt4-sentiment';
    private apiKey = config.get('openaiApiKey');

    async analyze(texts: string[]): Promise<{ scores: number[], tokens: number }> {
        if (!this.apiKey) throw new Error('OpenAI API key is not configured.');
        logger.debug(`Analyzing ${texts.length} texts with OpenAI.`);
        // Mocked API call
        await new Promise(res => setTimeout(res, 200 + Math.random() * 200));
        const scores = texts.map(text => (text.includes('bad') || text.includes('frustrated')) ? -0.8 : (text.includes('great') ? 0.9 : 0.1));
        const tokens = texts.join(' ').length / 4; // Rough estimate
        metrics.increment('sentiment_analysis.openai.requests', 1);
        metrics.histogram('sentiment_analysis.openai.tokens', tokens);
        return { scores, tokens: Math.round(tokens) };
    }
}

class AnthropicSentimentAdapter implements SentimentAnalysisProvider {
    id = 'anthropic-claude3-sentiment';
    private apiKey = config.get('anthropicApiKey');

    async analyze(texts: string[]): Promise<{ scores: number[], tokens: number }> {
        if (!this.apiKey) throw new Error('Anthropic API key is not configured.');
        logger.debug(`Analyzing ${texts.length} texts with Anthropic.`);
        // Mocked API call
        await new Promise(res => setTimeout(res, 250 + Math.random() * 200));
        const scores = texts.map(text => (text.includes('bad') || text.includes('frustrated')) ? -0.75 : (text.includes('great') ? 0.85 : 0.15));
        const tokens = texts.join(' ').length / 4; // Rough estimate
        metrics.increment('sentiment_analysis.anthropic.requests', 1);
        metrics.histogram('sentiment_analysis.anthropic.tokens', tokens);
        return { scores, tokens: Math.round(tokens) };
    }
}

// Tension: Speed/Cost vs. Accuracy in prediction. Gradient Boosting is accurate but slower. Logistic Regression is fast but simple.
interface PredictionModelProvider {
    readonly id: string;
    readonly description: string;
    predict(features: Record<string, number>): Promise<{ probability: number, factors: string[], units: number }>;
}

class VertexAIGradientBoostingAdapter implements PredictionModelProvider {
    id = 'vertex-ai-gb';
    description = 'High-accuracy Gradient Boosting model hosted on Google Vertex AI. Slower, more expensive.';
    private credentials = config.get('googleApplicationCredentials');

    async predict(features: Record<string, number>): Promise<{ probability: number, factors: string[], units: number }> {
        if (!this.credentials) throw new Error('Google Application Credentials not configured.');
        logger.debug('Predicting with Vertex AI Gradient Boosting model.');
        // Mocked API call
        await new Promise(res => setTimeout(res, 500 + Math.random() * 300));
        let probability = 0.1;
        if (features.avgSentiment < -0.5) probability += 0.4;
        if (features.transactionFrequency < 0.2) probability += 0.2;
        if (features.daysSinceLastLogin > 30) probability += 0.3;
        
        const factors = ['model_complexity:high', `sentiment:${features.avgSentiment}`, `recency:${features.daysSinceLastLogin}`];
        const units = 1; // 1 prediction unit
        metrics.increment('prediction_model.vertex_ai.requests', 1);
        return { probability: Math.min(probability, 0.95), factors, units };
    }
}

class HuggingFaceLogisticRegressionAdapter implements PredictionModelProvider {
    id = 'hf-logistic-regression';
    description = 'Fast, low-cost Logistic Regression model from Hugging Face Inference Endpoints.';
    private apiKey = config.get('huggingfaceApiKey');

    async predict(features: Record<string, number>): Promise<{ probability: number, factors: string[], units: number }> {
        if (!this.apiKey) throw new Error('Hugging Face API key is not configured.');
        logger.debug('Predicting with Hugging Face Logistic Regression model.');
        // Mocked API call
        await new Promise(res => setTimeout(res, 100 + Math.random() * 100));
        let probability = 0.05;
        if (features.avgSentiment < -0.6) probability += 0.3;
        if (features.daysSinceLastLogin > 45) probability += 0.25;

        const factors = ['model_complexity:low', `sentiment:${features.avgSentiment}`, `recency:${features.daysSinceLastLogin}`];
        const units = 0.1; // 0.1 prediction units (cheaper)
        metrics.increment('prediction_model.huggingface.requests', 1);
        return { probability: Math.min(probability, 0.8), factors, units };
    }
}

// --- EXTENSIBILITY: PROVIDER REGISTRY ---
class ProviderRegistry {
    private sentimentProviders = new Map<string, SentimentAnalysisProvider>();
    private predictionModels = new Map<string, PredictionModelProvider>();

    registerSentimentProvider(provider: SentimentAnalysisProvider) {
        this.sentimentProviders.set(provider.id, provider);
    }

    registerPredictionModel(model: PredictionModelProvider) {
        this.predictionModels.set(model.id, model);
    }

    getSentimentProvider(id: string): SentimentAnalysisProvider {
        const provider = this.sentimentProviders.get(id);
        if (!provider) throw new Error(`Sentiment provider '${id}' not found.`);
        return provider;
    }

    getPredictionModel(id: string): PredictionModelProvider {
        const model = this.predictionModels.get(id);
        if (!model) throw new Error(`Prediction model '${id}' not found.`);
        return model;
    }

    listModels() {
        return Array.from(this.predictionModels.values()).map(m => ({ id: m.id, description: m.description }));
    }
}

const providerRegistry = new ProviderRegistry();
providerRegistry.registerSentimentProvider(new OpenAISentimentAdapter());
providerRegistry.registerSentimentProvider(new AnthropicSentimentAdapter());
providerRegistry.registerPredictionModel(new VertexAIGradientBoostingAdapter());
providerRegistry.registerPredictionModel(new HuggingFaceLogisticRegressionAdapter());

// --- CORE BUSINESS LOGIC SERVICES ---
class FeatureEngineeringService {
    async createFeatures(request: ChurnPredictionRequest, sentimentProvider: SentimentAnalysisProvider): Promise<{ features: Record<string, number>, sentimentMeta: any }> {
        const { interactions, jurisdiction } = request;
        const now = new Date();

        // Basic features
        const logins = interactions.filter(i => i.type === 'login');
        const lastLogin = logins.length > 0 ? new Date(logins.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())[0].timestamp) : now;
        const daysSinceLastLogin = (now.getTime() - lastLogin.getTime()) / (1000 * 3600 * 24);

        const transactions = interactions.filter(i => i.type === 'transaction');
        const transactionFrequency = transactions.length / 30; // transactions per month (assuming 30 day window)

        // Sentiment features
        let sentimentMeta = null;
        let avgSentiment = 0;

        // Jurisdictional feature flag check
        const flags = config.get('jurisdictionFeatureFlags')[jurisdiction] || {};
        if (flags.disable_text_analysis) {
            logger.warn(`Text analysis disabled for jurisdiction: ${jurisdiction}`);
            sentimentMeta = { provider: 'none', averageScore: 0, analyzedTickets: 0, tokens: 0, reason: 'Disabled by jurisdiction flag' };
        } else {
            const supportTickets = interactions.filter(i => i.type === 'support_ticket').map(i => i.metadata.text as string).filter(Boolean);
            if (supportTickets.length > 0) {
                const { scores, tokens } = await sentimentProvider.analyze(supportTickets);
                avgSentiment = scores.reduce((a, b) => a + b, 0) / scores.length;
                sentimentMeta = { provider: sentimentProvider.id, averageScore: avgSentiment, analyzedTickets: supportTickets.length, tokens };
            } else {
                sentimentMeta = { provider: sentimentProvider.id, averageScore: 0, analyzedTickets: 0, tokens: 0 };
            }
        }

        const features = {
            daysSinceLastLogin,
            transactionFrequency,
            supportTicketCount: interactions.filter(i => i.type === 'support_ticket').length,
            avgSentiment,
        };

        logger.info({ customerId: request.customerId, features }, 'Generated features for churn prediction.');
        return { features, sentimentMeta };
    }
}

class PredictionService {
    private featureService = new FeatureEngineeringService();

    async startPredictionJob(request: ChurnPredictionRequest): Promise<string> {
        const jobId = randomUUID();
        const job: ChurnPredictionResult = {
            jobId,
            customerId: request.customerId,
            status: 'PENDING',
            churnProbability: null,
            riskLevel: null,
            contributingFactors: [],
            modelUsed: '',
            sentimentAnalysis: null,
            cost: { sentimentTokens: 0, predictionUnits: 0, totalMicroCents: 0 },
            createdAt: new Date().toISOString(),
        };
        jobStore.set(jobId, job);

        // Asynchronously process the job
        this.processJob(jobId, request).catch(err => {
            logger.error({ jobId, err }, 'Unhandled error during async job processing.');
        });

        const event = new CloudEvent({
            source: agent_metadata.agent_id,
            type: Ontology.ChurnPrediction.Requested,
            subject: request.customerId,
            data: { jobId, customerId: request.customerId },
        });
        await eventBus.publish(event);

        return jobId;
    }

    private async processJob(jobId: string, request: ChurnPredictionRequest) {
        try {
            this.updateJobStatus(jobId, { status: 'PROCESSING' });

            const sentimentProviderId = request.modelConfig?.sentimentProviderId || config.get('defaultSentimentProvider');
            const predictionModelId = request.modelConfig?.predictionModelId || config.get('defaultPredictionModel');

            const sentimentProvider = providerRegistry.getSentimentProvider(sentimentProviderId);
            const predictionModel = providerRegistry.getPredictionModel(predictionModelId);

            const { features, sentimentMeta } = await this.featureService.createFeatures(request, sentimentProvider);
            const { probability, factors, units } = await predictionModel.predict(features);

            const riskLevel = probability > 0.7 ? 'HIGH' : probability > 0.4 ? 'MEDIUM' : 'LOW';

            // Unit economics calculation (example pricing)
            const sentimentCost = sentimentMeta.tokens * 0.5; // $0.50 per 1k tokens
            const predictionCost = units * 1000; // $1 per prediction unit
            const totalMicroCents = Math.round((sentimentCost + predictionCost) * 100);

            const finalResult: Partial<ChurnPredictionResult> = {
                status: 'COMPLETED',
                churnProbability: probability,
                riskLevel,
                contributingFactors: factors,
                modelUsed: predictionModel.id,
                sentimentAnalysis: sentimentMeta,
                cost: {
                    sentimentTokens: sentimentMeta.tokens,
                    predictionUnits: units,
                    totalMicroCents,
                },
                completedAt: new Date().toISOString(),
            };
            this.updateJobStatus(jobId, finalResult);

            const event = new CloudEvent({
                source: agent_metadata.agent_id,
                type: Ontology.ChurnPrediction.Completed,
                subject: request.customerId,
                data: jobStore.get(jobId),
            });
            await eventBus.publish(event);
            
            await audit.log({
                actor: { type: 'system', id: agent_metadata.agent_id },
                action: 'churn.predict',
                resource: { type: 'customer', id: request.customerId },
                outcome: 'success',
                details: { jobId, probability, riskLevel, model: predictionModel.id }
            });

        } catch (error: any) {
            logger.error({ jobId, error: error.message }, 'Churn prediction job failed.');
            this.updateJobStatus(jobId, {
                status: 'FAILED',
                error: error.message,
                completedAt: new Date().toISOString(),
            });
            const event = new CloudEvent({
                source: agent_metadata.agent_id,
                type: Ontology.ChurnPrediction.Failed,
                subject: request.customerId,
                data: { jobId, error: error.message },
            });
            await eventBus.publish(event);
        }
    }

    private updateJobStatus(jobId: string, updates: Partial<ChurnPredictionResult>) {
        const job = jobStore.get(jobId);
        if (job) {
            jobStore.set(jobId, { ...job, ...updates });
        }
    }
}

// --- API SERVER SETUP ---
const server: FastifyInstance = fastify({ logger: core.getFastifyLogger() });
const predictionService = new PredictionService();

// --- HOOKS & MIDDLEWARE ---
server.addHook('onRequest', async (request, reply) => {
    // Attach core services for easy access in handlers
    (request as any).core = core;
    (request as any).audit = audit;
    metrics.increment('http.requests.total', 1, { method: request.method, path: request.routerPath });
});

server.addHook('preHandler', authService.getFastifyHook(['/health', '/introspect']));

// --- API ROUTES ---
server.post('/v1/predict', {
    schema: {
        body: ChurnPredictionRequestSchema,
        response: {
            202: {
                type: 'object',
                properties: {
                    jobId: { type: 'string' },
                    statusUrl: { type: 'string' },
                },
            },
        },
    },
}, async (request: FastifyRequest<{ Body: ChurnPredictionRequest }>, reply: FastifyReply) => {
    const jobId = await predictionService.startPredictionJob(request.body);
    reply.code(202).send({
        jobId,
        statusUrl: `/v1/predictions/${jobId}`,
    });
});

server.get('/v1/predictions/:jobId', async (request: FastifyRequest<{ Params: { jobId: string } }>, reply: FastifyReply) => {
    const { jobId } = request.params;
    const result = jobStore.get(jobId);

    if (!result) {
        return reply.code(404).send({ error: 'Job not found' });
    }

    return reply.send(result);
});

server.get('/v1/models', async (request, reply) => {
    return reply.send({
        predictionModels: providerRegistry.listModels(),
    });
});

server.get('/health', async (request, reply) => {
    return { status: 'ok', timestamp: new Date().toISOString() };
});

// --- SELF-QUERYING AGENT ENDPOINTS ---
server.get('/introspect', async (request, reply) => {
    reply.send({
        ...agent_metadata,
        uptime: process.uptime(),
        activeJobs: Array.from(jobStore.values()).filter(j => j.status === 'PROCESSING').length,
        totalJobs: jobStore.size,
        availableModels: providerRegistry.listModels(),
    });
});

server.get('/assumptions', async (request, reply) => {
    reply.send({
        title: 'Core Operating Assumptions for APP_68_Fintech_ChurnPredictor',
        assumptions: [
            {
                id: 'A01',
                category: 'Data Quality',
                statement: 'Input customer interaction data is timely, accurate, and representative of actual user behavior.',
                impact: 'Low-quality or biased data will lead to inaccurate predictions and skewed churn models.',
            },
            {
                id: 'A02',
                category: 'Model Relevance',
                statement: 'The sentiment and behavioral patterns correlated with churn are stable over the short-to-medium term.',
                impact: 'Sudden market shifts or product changes can invalidate the model, requiring retraining.',
            },
            {
                id: 'A03',
                category: 'API Stability',
                statement: 'External AI provider APIs (OpenAI, Anthropic, Google Cloud) are available and performant.',
                impact: 'Downtime or latency in provider APIs will directly impact this service\'s availability and performance.',
            },
            {
                id: 'A04',
                category: 'Economic Model',
                statement: 'The cost of prediction (API calls, compute) is significantly less than the value of retaining a customer.',
                impact: 'If AI provider costs increase dramatically, the service may become economically unviable.',
            },
        ],
    });
});

server.get('/failure-modes', async (request, reply) => {
    reply.send({
        title: 'Potential Failure Modes for APP_68_Fintech_ChurnPredictor',
        failure_modes: [
            {
                id: 'F01',
                mode: 'Model Drift',
                description: 'The predictive model becomes less accurate over time as customer behavior evolves.',
                mitigation: 'Regular model monitoring, automated retraining pipelines, and A/B testing of new models.',
                detection: 'Monitoring prediction accuracy against actual churn data; tracking distribution shifts in input features.',
            },
            {
                id: 'F02',
                mode: 'API Key Leakage',
                description: 'API keys for integrated AI services are compromised, leading to unauthorized usage and high costs.',
                mitigation: 'Use of secret management systems (e.g., HashiCorp Vault), key rotation policies, and network-level access controls.',
                detection: 'Billing alerts, anomalous usage pattern monitoring from AI providers.',
            },
            {
                id: 'F03',
                mode: 'Biased Predictions',
                description: 'The model unfairly flags certain customer demographics as high-churn risks due to biases in the training data.',
                mitigation: 'Bias detection and fairness toolkits during model development, analysis of prediction distribution across segments.',
                detection: 'Regular audits of model predictions against protected attributes.',
            },
            {
                id: 'F04',
                mode: 'Cascading Failure',
                description: 'An outage in a single sentiment analysis provider brings down the entire prediction service.',
                mitigation: 'Implementation of a provider-agnostic adapter pattern with automatic failover to a secondary provider.',
                detection: 'Health checks on external dependencies, circuit breaker patterns.',
            },
        ],
    });
});

server.get('/update-triggers', async (request, reply) => {
    reply.send({
        title: 'Triggers for System Updates or Re-evaluation',
        triggers: [
            {
                id: 'T01',
                trigger: 'Sustained drop in prediction accuracy below a predefined threshold (e.g., 85% precision).',
                action: 'Initiate model retraining pipeline with new data.',
            },
            {
                id: 'T02',
                trigger: 'Release of a new, more cost-effective or accurate model by a major AI provider.',
                action: 'Evaluate and integrate the new model as a selectable option via the ProviderRegistry.',
            },
            {
                id: 'T03',
                trigger: 'Change in data privacy laws in a major operational jurisdiction (e.g., GDPR, CCPA).',
                action: 'Review and update feature engineering logic and jurisdictional flags to ensure compliance.',
            },
            {
                id: 'T04',
                trigger: 'AI provider API costs increase by more than 20%.',
                action: 'Re-evaluate default model choices and update unit economics calculations.',
            },
        ],
    });
});

// --- SERVER START ---
const start = async () => {
    try {
        const port = config.get('port');
        await server.listen({ port, host: '0.0.0.0' });
        logger.info(`APP_68_Fintech_ChurnPredictor listening on port ${port}`);
    } catch (err) {
        server.log.error(err);
        process.exit(1);
    }
};

start();