import React, { useState, useEffect, useCallback } from 'react';

// Define a type for a simplified connected account, mirroring relevant Stripe Account fields
interface ConnectedAccount {
  id: string;
  name: string; // business_profile.name or company.name
  type: 'standard' | 'express' | 'custom';
  chargesEnabled: boolean;
  payoutsEnabled: boolean;
  detailsSubmitted: boolean;
  disabledReason: string | null; // e.g., 'requirements.past_due', 'requirements.pending_verification'
  capabilities: {
    card_payments: 'active' | 'inactive' | 'pending';
    transfers: 'active' | 'inactive' | 'pending';
    // Add other relevant capabilities as needed
  };
  // In a real application, this link would be generated by your backend using Stripe's AccountLink API
  onboardingLink?: string;
}

// Mock API service to simulate fetching connected accounts
const mockFetchConnectedAccounts = (): Promise<ConnectedAccount[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const accounts: ConnectedAccount[] = [
        {
          id: 'acct_123XYZ',
          name: 'Acme Corp',
          type: 'standard',
          chargesEnabled: true,
          payoutsEnabled: true,
          detailsSubmitted: true,
          disabledReason: null,
          capabilities: {
            card_payments: 'active',
            transfers: 'active',
          },
          onboardingLink: 'https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_XYZ&scope=read_write&stripe_user[email]=test@acme.com', // Example link
        },
        {
          id: 'acct_456ABC',
          name: 'Beta Solutions',
          type: 'express',
          chargesEnabled: false,
          payoutsEnabled: false,
          detailsSubmitted: true,
          disabledReason: 'requirements.past_due',
          capabilities: {
            card_payments: 'inactive',
            transfers: 'inactive',
          },
          onboardingLink: 'https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_ABC&scope=read_write&stripe_user[email]=test@beta.com',
        },
        {
          id: 'acct_789DEF',
          name: 'Gamma Innovations',
          type: 'custom',
          chargesEnabled: true,
          payoutsEnabled: false,
          detailsSubmitted: true,
          disabledReason: 'requirements.pending_verification',
          capabilities: {
            card_payments: 'active',
            transfers: 'inactive',
          },
          onboardingLink: 'https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_DEF&scope=read_write&stripe_user[email]=test@gamma.com',
        },
        {
          id: 'acct_012GHI',
          name: 'Delta Services',
          type: 'standard',
          chargesEnabled: true,
          payoutsEnabled: true,
          detailsSubmitted: true,
          disabledReason: null,
          capabilities: {
            card_payments: 'active',
            transfers: 'active',
          },
          // No onboarding link needed if fully active, but could be provided for updates
        },
        {
          id: 'acct_345JKL',
          name: 'Epsilon Tech',
          type: 'express',
          chargesEnabled: false,
          payoutsEnabled: false,
          detailsSubmitted: false, // Details not submitted yet
          disabledReason: 'requirements.not_met',
          capabilities: {
            card_payments: 'inactive',
            transfers: 'inactive',
          },
          onboardingLink: 'https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_JKL&scope=read_write&stripe_user[email]=test@epsilon.com',
        },
      ];
      resolve(accounts);
    }, 1000); // Simulate network delay
  });
};

// Helper function to determine overall verification status
const getVerificationStatus = (account: ConnectedAccount): { status: string; colorClass: string } => {
  if (account.disabledReason) {
    if (account.disabledReason.includes('past_due')) {
      return { status: 'Action Required (Past Due)', colorClass: 'bg-red-100 text-red-800' };
    }
    if (account.disabledReason.includes('pending_verification')) {
      return { status: 'Pending Verification', colorClass: 'bg-yellow-100 text-yellow-800' };
    }
    if (account.disabledReason.includes('not_met')) {
      return { status: 'Requirements Not Met', colorClass: 'bg-red-100 text-red-800' };
    }
    return { status: `Disabled: ${account.disabledReason.replace('requirements.', '')}`, colorClass: 'bg-red-100 text-red-800' };
  }
  if (!account.detailsSubmitted) {
    return { status: 'Onboarding Incomplete', colorClass: 'bg-yellow-100 text-yellow-800' };
  }
  if (!account.chargesEnabled || !account.payoutsEnabled) {
    return { status: 'Partially Enabled', colorClass: 'bg-orange-100 text-orange-800' };
  }
  return { status: 'Verified & Active', colorClass: 'bg-green-100 text-green-800' };
};

// Helper function to format capabilities
const formatCapabilities = (capabilities: ConnectedAccount['capabilities']): string => {
  const activeCaps: string[] = [];
  for (const [cap, status] of Object.entries(capabilities)) {
    if (status === 'active') {
      activeCaps.push(cap.replace(/_/g, ' ')); // e.g., "card payments"
    }
  }
  return activeCaps.length > 0 ? activeCaps.map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(', ') : 'None Active';
};

const ConnectedAccountsPage: React.FC = () => {
  const [accounts, setAccounts] = useState<ConnectedAccount[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchAccounts = async () => {
      try {
        setLoading(true);
        const data = await mockFetchConnectedAccounts();
        setAccounts(data);
      } catch (err) {
        setError('Failed to load connected accounts.');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchAccounts();
  }, []);

  const handleViewDetails = useCallback((accountId: string) => {
    // In a real app, this would navigate to a detailed account page
    console.log(`Navigating to details for account: ${accountId}`);
    alert(`Viewing details for ${accountId}`);
    // Example: history.push(`/connect/accounts/${accountId}`);
  }, []);

  const handleReOnboard = useCallback((accountId: string, onboardingLink?: string) => {
    // In a real app, this would redirect to Stripe Connect Onboarding flow
    console.log(`Initiating re-onboarding for account: ${accountId}`);
    if (onboardingLink) {
      // For demonstration, we'll just alert. In production, you'd redirect.
      alert(`Redirecting to Stripe Connect onboarding for ${accountId}. Link: ${onboardingLink}`);
      // window.location.href = onboardingLink;
    } else {
      alert(`No specific onboarding link found for ${accountId}. You might need to create one via API for updates.`);
    }
  }, []);

  if (loading) {
    return (
      <div className="p-6 bg-gray-50 min-h-screen flex flex-col items-center justify-center">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Connected Accounts</h1>
        <div className="flex justify-center items-center h-48">
          <p className="text-gray-600 text-lg">Loading connected accounts...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6 bg-gray-50 min-h-screen">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Connected Accounts</h1>
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <strong className="font-bold">Error!</strong>
          <span className="block sm:inline"> {error}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Connected Accounts</h1>

      {accounts.length === 0 ? (
        <div className="bg-white p-8 rounded-lg shadow-md text-center max-w-2xl mx-auto">
          <p className="text-lg text-gray-600 mb-4">No connected accounts found.</p>
          <p className="text-gray-500">
            Start by connecting a new Stripe account to your platform to enable payments and payouts.
          </p>
          {/* Add a button to initiate new account connection */}
          <button className="mt-6 px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
            Connect New Account
          </button>
        </div>
      ) : (
        <div className="bg-white shadow-md rounded-lg overflow-hidden">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Account Name
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Account ID
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Type
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Verification Status
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Capabilities
                </th>
                <th scope="col" className="relative px-6 py-3">
                  <span className="sr-only">Actions</span>
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {accounts.map((account) => {
                const { status, colorClass } = getVerificationStatus(account);
                const isFullyActive = status === 'Verified & Active';
                return (
                  <tr key={account.id}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {account.name || 'N/A'}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {account.id}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 capitalize">
                      {account.type}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${colorClass}`}>
                        {status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatCapabilities(account.capabilities)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <button
                        onClick={() => handleViewDetails(account.id)}
                        className="text-blue-600 hover:text-blue-900 mr-4"
                      >
                        View Details
                      </button>
                      {!isFullyActive && account.onboardingLink && (
                        <button
                          onClick={() => handleReOnboard(account.id, account.onboardingLink)}
                          className="text-indigo-600 hover:text-indigo-900"
                        >
                          Re-onboard
                        </button>
                      )}
                      {isFullyActive && account.onboardingLink && ( // Option to update details even if active
                         <button
                         onClick={() => handleReOnboard(account.id, account.onboardingLink)}
                         className="text-gray-600 hover:text-gray-900"
                       >
                         Update Details
                       </button>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default ConnectedAccountsPage;