export interface AC_ProductModel {
  id: string;
  name: string;
  description: string;
  price: number; // Price in the smallest currency unit (e.g., cents for USD) to avoid floating point issues.
  currency: string; // e.g., 'USD', 'EUR'
  isSubscription: boolean;
  subscriptionInterval?: 'day' | 'week' | 'month' | 'year'; // Required if isSubscription is true
  createdAt: Date;
  updatedAt: Date;
}

/**
 * DTO (Data Transfer Object) for creating a new product.
 * Omits fields that are typically generated by the database (id, createdAt, updatedAt).
 */
export type CreateProductDTO = Omit<AC_ProductModel, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * DTO (Data Transfer Object) for updating an existing product.
 * Allows partial updates of product fields.
 */
export type UpdateProductDTO = Partial<CreateProductDTO>;

/**
 * Mock database client to simulate interactions with a real database.
 * In a production environment, this would be replaced by an actual ORM client
 * (e.g., PrismaClient, TypeORM Repository, Mongoose Model) or a direct database driver.
 * This mock allows the repository to be tested and demonstrated without external dependencies.
 */
class MockDbClient {
  private products: AC_ProductModel[] = [];

  /**
   * Finds products based on optional criteria.
   * @param criteria Partial match criteria for filtering products.
   * @returns A promise resolving to an array of matching products.
   */
  async findMany(criteria?: Partial<AC_ProductModel>): Promise<AC_ProductModel[]> {
    if (!criteria) {
      return [...this.products]; // Return a shallow copy of all products
    }
    return this.products.filter(p =>
      Object.keys(criteria).every(key =>
        p[key as keyof AC_ProductModel] === criteria[key as keyof AC_ProductModel]
      )
    );
  }

  /**
   * Finds a unique product by its ID.
   * @param criteria An object containing the product ID.
   * @returns A promise resolving to the product or null if not found.
   */
  async findUnique(criteria: { id: string }): Promise<AC_ProductModel | null> {
    return this.products.find(p => p.id === criteria.id) || null;
  }

  /**
   * Creates a new product in the mock database.
   * @param data The product data to create.
   * @returns A promise resolving to the newly created product.
   */
  async create(data: CreateProductDTO): Promise<AC_ProductModel> {
    const newProduct: AC_ProductModel = {
      ...data,
      id: `prod_${Date.now()}_${Math.random().toString(36).substring(2, 11)}`, // Generate a unique ID
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    this.products.push(newProduct);
    return newProduct;
  }

  /**
   * Updates an existing product by ID.
   * @param criteria An object containing the product ID.
   * @param data The partial product data to update.
   * @returns A promise resolving to the updated product or null if not found.
   */
  async update(criteria: { id: string }, data: UpdateProductDTO): Promise<AC_ProductModel | null> {
    const index = this.products.findIndex(p => p.id === criteria.id);
    if (index === -1) {
      return null;
    }
    this.products[index] = {
      ...this.products[index],
      ...data,
      updatedAt: new Date(),
    };
    return this.products[index];
  }

  /**
   * Deletes a product by ID.
   * @param criteria An object containing the product ID.
   * @returns A promise resolving to the deleted product or null if not found.
   */
  async delete(criteria: { id: string }): Promise<AC_ProductModel | null> {
    const index = this.products.findIndex(p => p.id === criteria.id);
    if (index === -1) {
      return null;
    }
    const [deletedProduct] = this.products.splice(index, 1);
    return deletedProduct;
  }
}

/**
 * Data access layer for products.
 * Provides methods to interact with the AC_ProductModel, abstracting database operations.
 * This repository handles CRUD operations and specific queries related to products.
 */
export class BC_ProductRepository {
  private db: MockDbClient; // In a production app, this would be an actual DB client instance (e.g., PrismaClient).

  /**
   * Initializes the Product Repository.
   * @param dbClient An optional database client instance. Defaults to a new MockDbClient.
   *                 This allows for dependency injection, which is useful for testing.
   */
  constructor(dbClient: MockDbClient = new MockDbClient()) {
    this.db = dbClient;
  }

  /**
   * Creates a new product in the database.
   * @param productData The data for the product to be created.
   * @returns A promise resolving to the newly created product.
   * @throws Error if product creation fails.
   */
  async create(productData: CreateProductDTO): Promise<AC_ProductModel> {
    try {
      const product = await this.db.create(productData);
      return product;
    } catch (error) {
      console.error('BC_ProductRepository: Error creating product:', error);
      throw new Error('Failed to create product.');
    }
  }

  /**
   * Finds a product by its unique ID.
   * @param id The ID of the product to find.
   * @returns A promise resolving to the product or null if not found.
   * @throws Error if the database operation fails.
   */
  async findById(id: string): Promise<AC_ProductModel | null> {
    try {
      const product = await this.db.findUnique({ id });
      return product;
    } catch (error) {
      console.error(`BC_ProductRepository: Error finding product with ID ${id}:`, error);
      throw new Error(`Failed to find product with ID ${id}.`);
    }
  }

  /**
   * Retrieves all products from the database.
   * @returns A promise resolving to an array of all products.
   * @throws Error if the database operation fails.
   */
  async findAll(): Promise<AC_ProductModel[]> {
    try {
      const products = await this.db.findMany();
      return products;
    } catch (error) {
      console.error('BC_ProductRepository: Error finding all products:', error);
      throw new Error('Failed to retrieve all products.');
    }
  }

  /**
   * Updates an existing product by its ID.
   * @param id The ID of the product to update.
   * @param productData The partial data to update the product with.
   * @returns A promise resolving to the updated product or null if not found.
   * @throws Error if product update fails.
   */
  async update(id: string, productData: UpdateProductDTO): Promise<AC_ProductModel | null> {
    try {
      const updatedProduct = await this.db.update({ id }, productData);
      return updatedProduct;
    } catch (error) {
      console.error(`BC_ProductRepository: Error updating product with ID ${id}:`, error);
      throw new Error(`Failed to update product with ID ${id}.`);
    }
  }

  /**
   * Deletes a product by its ID.
   * @param id The ID of the product to delete.
   * @returns A promise resolving to the deleted product or null if not found.
   * @throws Error if product deletion fails.
   */
  async delete(id: string): Promise<AC_ProductModel | null> {
    try {
      const deletedProduct = await this.db.delete({ id });
      return deletedProduct;
    } catch (error) {
      console.error(`BC_ProductRepository: Error deleting product with ID ${id}:`, error);
      throw new Error(`Failed to delete product with ID ${id}.`);
    }
  }

  /**
   * Finds products based on their subscription status.
   * This is particularly relevant for the project goal of managing subscription apps.
   * @param isSubscription A boolean indicating whether to find subscription products (true) or one-time products (false).
   * @returns A promise resolving to an array of matching products.
   * @throws Error if the database operation fails.
   */
  async findBySubscriptionStatus(isSubscription: boolean): Promise<AC_ProductModel[]> {
    try {
      const products = await this.db.findMany({ isSubscription });
      return products;
    } catch (error) {
      console.error(`BC_ProductRepository: Error finding products by subscription status ${isSubscription}:`, error);
      throw new Error(`Failed to retrieve products by subscription status.`);
    }
  }
}