export interface JPMorganChaseTransaction {
  id: string;
  accountId: string; // Represents the account this transaction belongs to
  date: string; // ISO 8601 format: YYYY-MM-DD
  description: string;
  amount: number; // Positive for credit (inflow), negative for debit (outflow)
  currency: string; // e.g., "USD"
  type: 'DEBIT' | 'CREDIT';
  category: string; // e.g., "Groceries", "Utilities", "Salary", "Dining"
  status: 'POSTED' | 'PENDING' | 'CANCELLED';
  merchantName?: string;
  merchantId?: string; // Optional ID for the merchant
  originalAmount?: number; // For foreign currency transactions, original amount in foreign currency
  originalCurrency?: string; // For foreign currency transactions, original currency
  referenceNumber?: string; // Bank's internal reference number
}

export const mockJPMorganChaseTransactions: JPMorganChaseTransaction[] = [
  {
    id: 'txn_jpm_001',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-26',
    description: 'Whole Foods Market',
    amount: -75.23,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Groceries',
    status: 'POSTED',
    merchantName: 'Whole Foods Market',
  },
  {
    id: 'txn_jpm_002',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-26',
    description: 'Starbucks',
    amount: -5.50,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Coffee Shops',
    status: 'POSTED',
    merchantName: 'Starbucks',
  },
  {
    id: 'txn_jpm_003',
    accountId: 'acc_jpm_savings_456',
    date: '2023-10-25',
    description: 'Payroll Deposit - ACME Corp',
    amount: 2500.00,
    currency: 'USD',
    type: 'CREDIT',
    category: 'Salary',
    status: 'POSTED',
    merchantName: 'ACME Corp',
  },
  {
    id: 'txn_jpm_004',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-25',
    description: 'Netflix Subscription',
    amount: -19.99,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Subscriptions',
    status: 'POSTED',
    merchantName: 'Netflix',
  },
  {
    id: 'txn_jpm_005',
    accountId: 'acc_jpm_credit_789',
    date: '2023-10-24',
    description: 'Amazon.com',
    amount: -120.45,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Shopping',
    status: 'POSTED',
    merchantName: 'Amazon.com',
  },
  {
    id: 'txn_jpm_006',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-24',
    description: 'Utility Bill - Electricity',
    amount: -85.70,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Utilities',
    status: 'POSTED',
    merchantName: 'City Power & Light',
  },
  {
    id: 'txn_jpm_007',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-23',
    description: 'Transfer to Savings',
    amount: -500.00,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Transfers',
    status: 'POSTED',
  },
  {
    id: 'txn_jpm_008',
    accountId: 'acc_jpm_savings_456',
    date: '2023-10-23',
    description: 'Transfer from Checking',
    amount: 500.00,
    currency: 'USD',
    type: 'CREDIT',
    category: 'Transfers',
    status: 'POSTED',
  },
  {
    id: 'txn_jpm_009',
    accountId: 'acc_jpm_credit_789',
    date: '2023-10-22',
    description: 'Dinner at The Fancy Bistro',
    amount: -110.00,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Dining',
    status: 'POSTED',
    merchantName: 'The Fancy Bistro',
  },
  {
    id: 'txn_jpm_010',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-22',
    description: 'ATM Withdrawal',
    amount: -60.00,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Cash',
    status: 'POSTED',
  },
  {
    id: 'txn_jpm_011',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-27',
    description: 'Uber Ride',
    amount: -18.75,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Transportation',
    status: 'PENDING', // Example of a pending transaction
    merchantName: 'Uber',
  },
  {
    id: 'txn_jpm_012',
    accountId: 'acc_jpm_credit_789',
    date: '2023-10-27',
    description: 'Online Software Purchase',
    amount: -49.99,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Software',
    status: 'PENDING',
    merchantName: 'Software Co.',
  },
  {
    id: 'txn_jpm_013',
    accountId: 'acc_jpm_checking_123',
    date: '2023-10-21',
    description: 'Gym Membership',
    amount: -35.00,
    currency: 'USD',
    type: 'DEBIT',
    category: 'Health & Fitness',
    status: 'POSTED',
    merchantName: 'Fitness First',
  },
  {
    id: 'txn_jpm_014',
    accountId: 'acc_jpm_savings_456',
    date: '2023-10-20',
    description: 'Interest Earned',
    amount: 1.25,
    currency: 'USD',
    type: 'CREDIT',
    category: 'Interest',
    status: 'POSTED',
  },
  {
    id: 'txn_jpm_015',
    accountId: 'acc_jpm_credit_789',
    date: '2023-10-19',
    description: 'Payment to JPMorgan Chase Card',
    amount: 300.00, // Payment is a credit to the credit card account
    currency: 'USD',
    type: 'CREDIT',
    category: 'Credit Card Payment',
    status: 'POSTED',
  },
];