import axios, { AxiosInstance, AxiosError } from 'axios';
import { Logger } from 'pino'; // Assuming a pino-compatible logger interface

// --- Custom Error Types ---

/**
 * Base error for all model inference related issues.
 */
export class ModelInferenceError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = 'ModelInferenceError';
  }
}

/**
 * Thrown when the model service is unavailable, times out, or returns a server-side error (5xx).
 */
export class ModelUnavailableError extends ModelInferenceError {
  constructor(message: string, cause?: unknown) {
    super(message, cause);
    this.name = 'ModelUnavailableError';
  }
}

/**
 * Thrown when the input data is invalid or rejected by the model service (4xx).
 */
export class InvalidInputError extends ModelInferenceError {
  constructor(message: string, cause?: unknown) {
    super(message, cause);
    this.name = 'InvalidInputError';
  }
}

// --- Data Transfer Objects (DTOs) ---

/**
 * Configuration for the ModelInferenceClient.
 */
export interface ModelInferenceClientConfig {
  /** The base URL of the deployed ML model endpoint (e.g., 'https://ml-models.internal/fraud-detection'). */
  endpointUrl: string;
  /** An API key for authenticating with the model service, if required. */
  apiKey?: string;
  /** Request timeout in milliseconds. Defaults to 5000. */
  timeoutMs?: number;
}

/**
 * Input features for the fraud detection model.
 * This is a representative example and should be aligned with the actual model's expected input schema.
 */
export interface FraudPredictionInput {
  transactionId: string;
  userId: string;
  amount: number;
  currency: string;
  merchantId: string;
  paymentMethod: 'credit_card' | 'paypal' | 'bank_transfer' | 'crypto';
  deviceIp: string;
  userAgent: string;
  transactionTimestamp: string; // ISO 8601 format (e.g., "2023-10-27T10:00:00Z")
  userAccountAgeDays?: number;
  previousTransactionsCount?: number;
  billingCountry?: string;
  shippingCountry?: string;
}

/**
 * The prediction output from the fraud detection model.
 */
export interface FraudPredictionOutput {
  /** A unique identifier for this specific prediction, often generated by the model service. */
  predictionId: string;
  /** The probability score (between 0.0 and 1.0) that the transaction is fraudulent. */
  fraudProbability: number;
  /** A binary classification based on a predefined threshold within the model service. */
  isFraud: boolean;
  /** The version identifier of the model that made the prediction (e.g., 'v2.1.3'). */
  modelVersion: string;
  /** Optional array of risk factors or feature importances identified by the model. */
  riskFactors?: string[];
}

/**
 * A client for making predictions with a deployed fraud detection ML model.
 * It encapsulates the logic for HTTP communication, authentication, and robust error handling.
 */
export class ModelInferenceClient {
  private readonly httpClient: AxiosInstance;
  private readonly logger: Logger;

  /**
   * Creates an instance of ModelInferenceClient.
   * @param {ModelInferenceClientConfig} config - The configuration for the client.
   * @param {Logger} logger - An instance of a logger for structured logging.
   */
  constructor(config: ModelInferenceClientConfig, logger: Logger) {
    this.logger = logger.child({ context: 'ModelInferenceClient' });

    if (!config.endpointUrl) {
      throw new Error('ModelInferenceClient: endpointUrl is required in config.');
    }

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };

    if (config.apiKey) {
      headers['Authorization'] = `Bearer ${config.apiKey}`;
    }

    this.httpClient = axios.create({
      baseURL: config.endpointUrl,
      timeout: config.timeoutMs || 5000, // Default to 5 seconds
      headers,
    });

    this.logger.info({ endpoint: config.endpointUrl }, 'ModelInferenceClient initialized.');
  }

  /**
   * Sends transaction data to the ML model and returns a fraud prediction.
   *
   * @param {FraudPredictionInput} input - The features of the transaction to be evaluated.
   * @returns {Promise<FraudPredictionOutput>} A promise that resolves with the model's prediction.
   * @throws {InvalidInputError} If the input data is invalid or rejected by the model service.
   * @throws {ModelUnavailableError} If the model service is unavailable or times out.
   * @throws {ModelInferenceError} For other unexpected errors during the inference process.
   */
  public async predict(input: FraudPredictionInput): Promise<FraudPredictionOutput> {
    const logContext = { transactionId: input.transactionId, userId: input.userId };
    this.logger.info(logContext, 'Requesting fraud prediction.');

    try {
      // The actual endpoint path might be at the root or a sub-path like '/predict'
      const response = await this.httpClient.post<FraudPredictionOutput>('/predict', input);

      if (!this.isValidPredictionOutput(response.data)) {
        this.logger.error({ ...logContext, responseData: response.data }, 'Received invalid prediction output from model service.');
        throw new ModelInferenceError('Invalid response format from model service.');
      }

      this.logger.info(
        {
          ...logContext,
          predictionId: response.data.predictionId,
          fraudProbability: response.data.fraudProbability,
          modelVersion: response.data.modelVersion,
        },
        'Successfully received fraud prediction.'
      );

      return response.data;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        this.handleAxiosError(error, logContext);
      }
      
      this.logger.error({ err: error, ...logContext }, 'An unexpected error occurred during model inference.');
      throw new ModelInferenceError(`An unexpected error occurred: ${(error as Error).message}`, error);
    }
  }

  /**
   * Handles Axios-specific errors and throws appropriate custom, domain-specific errors.
   * @param {AxiosError} error - The error thrown by Axios.
   * @param {object} logContext - Contextual information for logging.
   * @private
   */
  private handleAxiosError(error: AxiosError, logContext: object): never {
    this.logger.error(
      {
        ...logContext,
        err: {
          message: error.message,
          code: error.code,
          status: error.response?.status,
          data: error.response?.data,
        },
      },
      'Model inference HTTP request failed.'
    );

    if (error.response) {
      // The server responded with a non-2xx status code
      if (error.response.status >= 400 && error.response.status < 500) {
        const message = `Model service rejected input with status ${error.response.status}.`;
        throw new InvalidInputError(message, error);
      }
      if (error.response.status >= 500) {
        const message = `Model service is unavailable (status ${error.response.status}).`;
        throw new ModelUnavailableError(message, error);
      }
    } else if (error.request) {
      // The request was made but no response was received (e.g., timeout, network error)
      throw new ModelUnavailableError('No response received from model service.', error);
    }

    // Something else happened in setting up the request
    throw new ModelInferenceError('Failed to make request to model service.', error);
  }

  /**
   * A type guard to validate the structure of the prediction output.
   * For production systems, consider using a more robust validation library like Zod.
   * @param {any} data - The data to validate.
   * @returns {boolean} True if the data conforms to the FraudPredictionOutput interface.
   * @private
   */
  private isValidPredictionOutput(data: any): data is FraudPredictionOutput {
    return (
      data &&
      typeof data.predictionId === 'string' &&
      typeof data.fraudProbability === 'number' &&
      data.fraudProbability >= 0 &&
      data.fraudProbability <= 1 &&
      typeof data.isFraud === 'boolean' &&
      typeof data.modelVersion === 'string'
    );
  }
}