// In a real-world scenario, these types would likely be generated from the OpenAPI
// specification or defined in a shared library. They are included here for completeness.

/**
 * Represents the type of account group, aligning with the OpenAPI schema.
 */
export type AccountGroup = 'CHECKING' | 'SAVINGS' | 'CREDITCARD' | 'LOAN' | 'LINEOFCREDIT' | 'BROKERAGE' | 'RETIREMENT';

/**
 * A simplified representation of a single financial account, based on the various
 * AccountDetailsList schemas in the OpenAPI definition.
 */
export interface Account {
  accountId: string;
  accountGroup: AccountGroup;
  displayAccountNumber: string;
  productName: string;
  currencyCode: string;
  availableBalance: number;
  currentBalance: number;
  // Fields primarily for credit card, loan, or line of credit accounts
  minimumDueAmount?: number;
  paymentDueDate?: string; // Format: YYYY-MM-DD
  purchasesAPR?: number;
}

/**
 * Represents the overall financial state of the user, composed of their accounts.
 */
export interface FinancialState {
  accounts: Account[];
}

/**
 * Defines the structure for a proposed fund transfer action generated by the negotiator.
 */
export interface ProposedTransfer {
  fromAccountId: string;
  fromAccountDisplay: string;
  toAccountId: string;
  toAccountDisplay: string;
  amount: number;
  currencyCode: string;
  reason: string;
}

/**
 * Internal type to represent an account that requires funds.
 */
interface AccountNeed {
  account: Account;
  amountNeeded: number;
  priority: number; // Lower number indicates higher priority
}

/**

 * Internal type to represent an account with surplus funds available for transfer.
 */
interface AccountSurplus {
  account: Account;
  amountAvailable: number;
  priority: number; // Lower number indicates a more preferred source
}

// --- Agent Configuration ---

const LOW_BALANCE_THRESHOLD = 500;
const SURPLUS_BUFFER = 1000; // A safety buffer to leave in source accounts.

/**
 * Defines the priority for using accounts as a source of funds.
 * Checking accounts are the most liquid and preferred source.
 */
const SOURCE_PRIORITY: Record<AccountGroup, number> = {
  CHECKING: 1,
  SAVINGS: 2,
  BROKERAGE: 3, // Low priority to avoid liquidating investments
  CREDITCARD: 99,
  LOAN: 99,
  LINEOFCREDIT: 99,
  RETIREMENT: 99,
};

/**
 * Defines the priority for sending funds to an account.
 * High-interest debt is the highest priority to avoid charges.
 */
const SINK_PRIORITY: Record<AccountGroup, number> = {
  CREDITCARD: 1,
  LOAN: 2,
  LINEOFCREDIT: 3,
  CHECKING: 4, // Important to avoid overdraft fees
  SAVINGS: 99,
  BROKERAGE: 99,
  RETIREMENT: 99,
};

/**
 * An automated agent that simulates liquidity negotiation between a user's accounts.
 * It analyzes the overall financial state to identify potential shortfalls and
 * proposes optimal fund transfers to maintain financial health and avoid fees.
 */
export class AutoNegotiator {

  /**
   * Analyzes the user's financial state and proposes a series of optimal transfers
   * to resolve any identified liquidity deficits.
   *
   * @param state The current financial state, including all relevant accounts.
   * @returns An array of proposed fund transfers, or an empty array if no action is needed.
   */
  public proposeTransfers(state: FinancialState): ProposedTransfer[] {
    const { needs, surpluses } = this.identifyNeedsAndSurpluses(state.accounts);

    if (needs.length === 0 || surpluses.length === 0) {
      return []; // No action is possible or required.
    }

    const sortedNeeds = needs.sort((a, b) => a.priority - b.priority);
    const sortedSurpluses = surpluses.sort((a, b) => a.priority - b.priority);

    return this.generateTransferPlan(sortedNeeds, sortedSurpluses);
  }

  /**
   * Segregates accounts into those requiring funds (sinks) and those with
   * excess funds that can be used as sources.
   *
   * @param accounts A list of all financial accounts for the user.
   * @returns An object containing lists of accounts with needs and surpluses.
   */
  private identifyNeedsAndSurpluses(accounts: Account[]): { needs: AccountNeed[]; surpluses: AccountSurplus[] } {
    const needs: AccountNeed[] = [];
    const surpluses: AccountSurplus[] = [];

    for (const account of accounts) {
      // 1. Identify Needs (Sinks)
      let amountNeeded = 0;

      // Check for upcoming payments on liability accounts
      if (account.accountGroup === 'CREDITCARD' || account.accountGroup === 'LOAN' || account.accountGroup === 'LINEOFCREDIT') {
        if (account.minimumDueAmount && account.minimumDueAmount > 0 && account.paymentDueDate) {
          const dueDate = new Date(account.paymentDueDate);
          const today = new Date();
          // Calculate days until due, ignoring time part
          dueDate.setHours(0,0,0,0);
          today.setHours(0,0,0,0);
          const daysUntilDue = (dueDate.getTime() - today.getTime()) / (1000 * 3600 * 24);

          // Flag payments due within the next 7 days as a need
          if (daysUntilDue >= 0 && daysUntilDue <= 7) {
             amountNeeded = account.minimumDueAmount;
          }
        }
      }
      // Check for low balance in checking accounts to prevent overdraft
      else if (account.accountGroup === 'CHECKING') {
        if (account.availableBalance < LOW_BALANCE_THRESHOLD) {
          amountNeeded = LOW_BALANCE_THRESHOLD - account.availableBalance;
        }
      }

      if (amountNeeded > 0) {
        needs.push({
          account,
          amountNeeded: Math.ceil(amountNeeded), // Use ceiling to ensure coverage
          priority: SINK_PRIORITY[account.accountGroup] ?? 99,
        });
      }

      // 2. Identify Surpluses (Sources)
      const surplusPriority = SOURCE_PRIORITY[account.accountGroup] ?? 99;
      if (surplusPriority < 99) { // Check if the account type is a valid source
        const availableForTransfer = account.availableBalance - SURPLUS_BUFFER;
        if (availableForTransfer > 0) {
          surpluses.push({
            account,
            amountAvailable: availableForTransfer,
            priority: surplusPriority,
          });
        }
      }
    }

    return { needs, surpluses };
  }

  /**
   * Creates an optimized transfer plan by matching the highest priority needs
   * with the best available sources of funds.
   *
   * @param needs A sorted list of accounts that require funds.
   * @param surpluses A sorted list of accounts that can provide funds.
   * @returns an array of proposed fund transfer actions.
   */
  private generateTransferPlan(needs: AccountNeed[], surpluses: AccountSurplus[]): ProposedTransfer[] {
    const proposedTransfers: ProposedTransfer[] = [];
    const availableSurpluses = [...surpluses]; // Create a mutable copy to track available funds

    for (const need of needs) {
      let remainingNeed = need.amountNeeded;

      for (const surplus of availableSurpluses) {
        if (remainingNeed <= 0) break;
        if (surplus.amountAvailable <= 0) continue;
        if (surplus.account.accountId === need.account.accountId) continue; // Cannot transfer to itself

        const transferAmount = Math.min(remainingNeed, surplus.amountAvailable);

        proposedTransfers.push({
          fromAccountId: surplus.account.accountId,
          fromAccountDisplay: `${surplus.account.productName} (...${surplus.account.displayAccountNumber.slice(-4)})`,
          toAccountId: need.account.accountId,
          toAccountDisplay: `${need.account.productName} (...${need.account.displayAccountNumber.slice(-4)})`,
          amount: parseFloat(transferAmount.toFixed(2)),
          currencyCode: need.account.currencyCode,
          reason: this.getTransferReason(need),
        });

        // Deduct the transferred amount from the need and the surplus
        remainingNeed -= transferAmount;
        surplus.amountAvailable -= transferAmount;
      }
    }

    return proposedTransfers;
  }

  /**
   * Generates a human-readable reason for a proposed transfer.
   * @param need The account need that triggered the transfer proposal.
   * @returns A string explaining why the transfer is recommended.
   */
  private getTransferReason(need: AccountNeed): string {
    switch(need.account.accountGroup) {
      case 'CREDITCARD':
      case 'LOAN':
      case 'LINEOFCREDIT':
        return `To cover minimum payment of ${need.amountNeeded.toFixed(2)} ${need.account.currencyCode} due on ${need.account.paymentDueDate}.`;
      case 'CHECKING':
        return `To bring balance above the ${LOW_BALANCE_THRESHOLD} ${need.account.currencyCode} safety threshold.`;
      default:
        return `To ensure sufficient funds for upcoming debits.`;
    }
  }
}