export interface Customer {
  id: string;
  email: string;
  firstName?: string;
  lastName?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  phoneNumber?: string;
  status: 'active' | 'inactive' | 'pending'; // For AE25
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateCustomerInput {
  email: string;
  passwordHash: string; // Hashed password, typically generated by an auth service before calling this service
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
}

export interface UpdateCustomerInput {
  firstName?: string;
  lastName?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
  phoneNumber?: string;
  // Password changes should ideally go through a separate auth service method
}

/**
 * Interface for the Customer Data Access Layer (Repository).
 * Assumes methods for interacting with a persistent storage.
 */
export interface ICustomerRepository {
  /**
   * Creates a new customer record in the database.
   * @param customerData - The data for the new customer, including a hashed password.
   * @returns The newly created customer object.
   */
  create(customerData: Omit<Customer, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { passwordHash: string }): Promise<Customer>;

  /**
   * Finds a customer by their unique ID.
   * @param id - The customer's unique identifier.
   * @returns The customer object if found, otherwise null.
   */
  findById(id: string): Promise<Customer | null>;

  /**
   * Finds a customer by their email address.
   * @param email - The customer's email address.
   * @returns The customer object if found, otherwise null.
   */
  findByEmail(email: string): Promise<Customer | null>;

  /**
   * Updates an existing customer's profile information.
   * @param id - The ID of the customer to update.
   * @param updateData - A partial object containing the fields to update.
   * @returns The updated customer object if found and updated, otherwise null.
   */
  update(id: string, updateData: Partial<Omit<Customer, 'id' | 'email' | 'createdAt' | 'updatedAt'>>): Promise<Customer | null>;

  /**
   * Updates the status of a customer's account.
   * @param id - The ID of the customer to update.
   * @param status - The new status for the customer ('active', 'inactive', 'pending').
   * @returns The updated customer object if found and updated, otherwise null.
   */
  updateStatus(id: string, status: Customer['status']): Promise<Customer | null>;
}

/**
 * Interface for a logging utility.
 */
export interface ILogger {
  info(message: string, context?: Record<string, any>): void;
  warn(message: string, context?: Record<string, any>): void;
  error(message: string, error?: Error, context?: Record<string, any>): void;
  debug(message: string, context?: Record<string, any>): void;
}

/**
 * Custom error for when a customer is not found.
 */
export class CustomerNotFoundError extends Error {
  constructor(message: string = 'Customer not found') {
    super(message);
    this.name = 'CustomerNotFoundError';
  }
}

/**
 * Custom error for when a customer with the given email already exists.
 */
export class CustomerAlreadyExistsError extends Error {
  constructor(message: string = 'Customer with this email already exists') {
    super(message);
    this.name = 'CustomerAlreadyExistsError';
  }
}

/**
 * Custom error for invalid customer data provided.
 */
export class InvalidCustomerDataError extends Error {
  constructor(message: string = 'Invalid customer data provided') {
    super(message);
    this.name = 'InvalidCustomerDataError';
  }
}

/**
 * CB_CustomerService provides business logic for customer management.
 * It handles customer creation, retrieval, updates, and deactivation,
 * implementing specific application requirements (AE6, AE23-25, AE38).
 */
export class CB_CustomerService {
  private customerRepository: ICustomerRepository;
  private logger: ILogger;

  /**
   * Constructs a new CB_CustomerService instance.
   * @param customerRepository - The data access layer for customer operations.
   * @param logger - The logging utility.
   */
  constructor(customerRepository: ICustomerRepository, logger: ILogger) {
    this.customerRepository = customerRepository;
    this.logger = logger;
    this.logger.info('CB_CustomerService initialized.');
  }

  /**
   * AE6: Customer Account Creation
   * Creates a new customer account with the provided details.
   *
   * @param input - Data for creating the customer, including a pre-hashed password.
   * @returns A promise that resolves to the newly created customer object.
   * @throws InvalidCustomerDataError if required input (email, passwordHash) is missing.
   * @throws CustomerAlreadyExistsError if a customer with the given email already exists.
   * @throws Error for any other unexpected issues during creation.
   */
  public async createCustomer(input: CreateCustomerInput): Promise<Customer> {
    this.logger.debug('Attempting to create new customer.', { email: input.email });

    if (!input.email || !input.passwordHash) {
      this.logger.warn('Attempted to create customer with missing email or passwordHash.', { input });
      throw new InvalidCustomerDataError('Email and passwordHash are required to create a customer.');
    }

    const existingCustomer = await this.customerRepository.findByEmail(input.email);
    if (existingCustomer) {
      this.logger.warn('Customer creation failed: Email already exists.', { email: input.email });
      throw new CustomerAlreadyExistsError(`Customer with email ${input.email} already exists.`);
    }

    try {
      const newCustomerData = {
        email: input.email,
        passwordHash: input.passwordHash,
        firstName: input.firstName,
        lastName: input.lastName,
        phoneNumber: input.phoneNumber,
        address: input.address,
        city: input.city,
        state: input.state,
        zipCode: input.zipCode,
        country: input.country,
        status: 'active' as const, // Default status for new accounts
      };
      const customer = await this.customerRepository.create(newCustomerData);
      this.logger.info('Customer account created successfully.', { customerId: customer.id, email: customer.email });
      return customer;
    } catch (error: any) {
      this.logger.error('Error creating customer account.', error, { email: input.email });
      throw error; // Re-throw to be handled by upstream caller
    }
  }

  /**
   * AE23: Customer Profile Viewing
   * Retrieves a customer's profile by their unique ID.
   *
   * @param customerId - The unique ID of the customer.
   * @returns A promise that resolves to the customer object.
   * @throws InvalidCustomerDataError if the customerId is missing.
   * @throws CustomerNotFoundError if no customer is found with the given ID.
   */
  public async getCustomerById(customerId: string): Promise<Customer> {
    this.logger.debug('Attempting to retrieve customer by ID.', { customerId });

    if (!customerId) {
      this.logger.warn('Attempted to retrieve customer with missing ID.');
      throw new InvalidCustomerDataError('Customer ID is required to retrieve a customer.');
    }

    const customer = await this.customerRepository.findById(customerId);
    if (!customer) {
      this.logger.warn('Customer retrieval failed: Customer not found.', { customerId });
      throw new CustomerNotFoundError(`Customer with ID ${customerId} not found.`);
    }

    this.logger.info('Customer profile retrieved successfully.', { customerId: customer.id });
    return customer;
  }

  /**
   * AE24: Customer Profile Editing
   * Updates a customer's profile information.
   *
   * @param customerId - The ID of the customer whose profile is to be updated.
   * @param updateData - An object containing the fields to update.
   * @returns A promise that resolves to the updated customer object.
   * @throws InvalidCustomerDataError if customerId is missing or updateData is empty.
   * @throws CustomerNotFoundError if no customer is found with the given ID.
   * @throws Error for any other unexpected issues during update.
   */
  public async updateCustomerProfile(customerId: string, updateData: UpdateCustomerInput): Promise<Customer> {
    this.logger.debug('Attempting to update customer profile.', { customerId, updateData });

    if (!customerId) {
      this.logger.warn('Attempted to update customer with missing ID.');
      throw new InvalidCustomerDataError('Customer ID is required to update a customer.');
    }

    if (Object.keys(updateData).length === 0) {
      this.logger.warn('Attempted to update customer with empty data.', { customerId });
      throw new InvalidCustomerDataError('No update data provided.');
    }

    try {
      const updatedCustomer = await this.customerRepository.update(customerId, updateData);

      if (!updatedCustomer) {
        this.logger.warn('Customer update failed: Customer not found.', { customerId });
        throw new CustomerNotFoundError(`Customer with ID ${customerId} not found.`);
      }

      this.logger.info('Customer profile updated successfully.', { customerId: updatedCustomer.id });
      return updatedCustomer;
    } catch (error: any) {
      this.logger.error('Error updating customer profile.', error, { customerId, updateData });
      throw error;
    }
  }

  /**
   * AE25: Customer Account Deactivation
   * Deactivates a customer's account by changing their status to 'inactive'.
   *
   * @param customerId - The ID of the customer to deactivate.
   * @returns A promise that resolves to the deactivated customer object.
   * @throws InvalidCustomerDataError if customerId is missing.
   * @throws CustomerNotFoundError if no customer is found with the given ID.
   * @throws Error for any other unexpected issues during deactivation.
   */
  public async deactivateCustomerAccount(customerId: string): Promise<Customer> {
    this.logger.debug('Attempting to deactivate customer account.', { customerId });

    if (!customerId) {
      this.logger.warn('Attempted to deactivate customer with missing ID.');
      throw new InvalidCustomerDataError('Customer ID is required to deactivate an account.');
    }

    const customer = await this.customerRepository.findById(customerId);
    if (!customer) {
      this.logger.warn('Customer deactivation failed: Customer not found.', { customerId });
      throw new CustomerNotFoundError(`Customer with ID ${customerId} not found.`);
    }

    if (customer.status === 'inactive') {
      this.logger.info('Customer account is already inactive, no action needed.', { customerId });
      return customer; // Already inactive, return existing customer
    }

    try {
      const deactivatedCustomer = await this.customerRepository.updateStatus(customerId, 'inactive');

      if (!deactivatedCustomer) {
        // This case should ideally not happen if findById succeeded, but good for robustness
        this.logger.error('Failed to update customer status to inactive after finding customer.', null, { customerId });
        throw new Error(`Failed to deactivate customer account with ID ${customerId}.`);
      }

      this.logger.info('Customer account deactivated successfully.', { customerId: deactivatedCustomer.id });
      return deactivatedCustomer;
    } catch (error: any) {
      this.logger.error('Error deactivating customer account.', error, { customerId });
      throw error;
    }
  }

  /**
   * AE38: Subscription Management for Customers
   * Retrieves a list of subscription IDs associated with a specific customer.
   * This method acts as a gateway or placeholder for integrating with a dedicated
   * SubscriptionService or directly querying subscription data linked to the customer.
   *
   * @param customerId - The ID of the customer.
   * @returns A promise resolving to an array of subscription IDs.
   * @throws InvalidCustomerDataError if the customerId is missing.
   * @throws CustomerNotFoundError if the customer does not exist.
   */
  public async getCustomerSubscriptions(customerId: string): Promise<string[]> {
    this.logger.debug('Attempting to retrieve subscriptions for customer.', { customerId });

    if (!customerId) {
      this.logger.warn('Attempted to retrieve subscriptions with missing customer ID.');
      throw new InvalidCustomerDataError('Customer ID is required to retrieve subscriptions.');
    }

    const customer = await this.customerRepository.findById(customerId);
    if (!customer) {
      this.logger.warn('Customer subscriptions retrieval failed: Customer not found.', { customerId });
      throw new CustomerNotFoundError(`Customer with ID ${customerId} not found.`);
    }

    // --- Placeholder for actual subscription retrieval logic ---
    // In a real application, this would typically involve:
    // 1. Calling a dedicated `SubscriptionService` (e.g., `this.subscriptionService.getSubscriptionsByCustomerId(customerId)`).
    // 2. Or, if subscriptions are directly linked/embedded in the Customer model, retrieving them from the customer object.
    // 3. Or, a direct query to a `SubscriptionRepository` to find subscriptions by customerId.

    // For now, we return an empty array as a placeholder.
    this.logger.info('Retrieved customer subscriptions (placeholder - actual logic to be implemented).', { customerId });
    return [];
  }
}