import { v4 as uuidv4 } from 'uuid';

// --- Data Models ---

/**
 * Defines the available usage metrics that can be tracked.
 * This enum/type should be expanded as new features requiring usage-based billing are introduced.
 */
export type UsageMetric = 'API_CALLS' | 'STORAGE_GB_HOURS' | 'COMPUTE_UNITS' | 'DATA_TRANSFER_GB' | 'AI_MODEL_INFERENCE_UNITS';

/**
 * Represents a single record of usage for a specific metric.
 */
export interface UsageRecord {
    id: string; // Unique identifier for the usage record
    userId: string; // The ID of the user associated with the usage
    subscriptionId: string; // The ID of the subscription this usage falls under
    metricName: UsageMetric; // The specific metric being tracked (e.g., 'API_CALLS')
    quantity: number; // The amount of usage for this metric
    timestamp: Date; // The exact time the usage occurred
    // Additional metadata could be added here, e.g., 'region', 'featureId', 'costCenter'
}

// --- Repository Interface (Abstraction for Data Access Layer) ---

/**
 * Defines the contract for interacting with the underlying data store for usage records.
 * This abstraction allows the service to be independent of the specific database technology.
 */
export interface IUsageRepository {
    /**
     * Creates and persists a new usage record.
     * @param record The usage record data, excluding the 'id' which is generated by the repository.
     * @returns The newly created UsageRecord, including its generated 'id'.
     */
    createUsageRecord(record: Omit<UsageRecord, 'id'>): Promise<UsageRecord>;

    /**
     * Retrieves all usage records for a given subscription within a specified date range.
     * @param subscriptionId The ID of the subscription.
     * @param startDate The start date of the period (inclusive).
     * @param endDate The end date of the period (inclusive).
     * @returns An array of UsageRecord objects.
     */
    getUsageRecordsBySubscriptionId(subscriptionId: string, startDate: Date, endDate: Date): Promise<UsageRecord[]>;

    // Future methods could include:
    // - getUsageRecordsByUserId(userId: string, startDate: Date, endDate: Date): Promise<UsageRecord[]>;
    // - deleteUsageRecord(id: string): Promise<void>;
    // - updateUsageRecord(id: string, updates: Partial<UsageRecord>): Promise<UsageRecord>;
}

// --- Mock/In-Memory Repository Implementation (for development and testing) ---

/**
 * An in-memory implementation of IUsageRepository.
 * In a production environment, this would be replaced by a database-specific implementation
 * (e.g., using Prisma, TypeORM, or a direct SQL client).
 */
export class InMemoryUsageRepository implements IUsageRepository {
    private records: UsageRecord[] = [];

    /**
     * Creates a new usage record and stores it in memory.
     * Generates a unique ID for the record.
     */
    public async createUsageRecord(record: Omit<UsageRecord, 'id'>): Promise<UsageRecord> {
        const newRecord: UsageRecord = {
            id: uuidv4(),
            ...record,
            timestamp: record.timestamp || new Date(), // Ensure timestamp is set
        };
        this.records.push(newRecord);
        // console.log(`[InMemoryUsageRepository] Recorded usage: ${JSON.stringify(newRecord)}`); // For debugging
        return newRecord;
    }

    /**
     * Retrieves usage records from memory for a given subscription and date range.
     */
    public async getUsageRecordsBySubscriptionId(subscriptionId: string, startDate: Date, endDate: Date): Promise<UsageRecord[]> {
        return this.records.filter(record =>
            record.subscriptionId === subscriptionId &&
            record.timestamp >= startDate &&
            record.timestamp <= endDate
        ).sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime()); // Sort by timestamp
    }
}

// --- CH_UsageService Implementation ---

/**
 * Business logic for tracking and recording usage data for usage-based billing.
 * Implements AE21 (tracking usage events) and AE22 (retrieving and aggregating usage for billing).
 */
export class CH_UsageService {
    private usageRepository: IUsageRepository;
    private logger: Console; // Using Console as a simple logger; could be replaced with a more robust logging library

    /**
     * Constructs the CH_UsageService.
     * @param usageRepository An implementation of IUsageRepository to handle data persistence.
     * @param logger An optional logger instance. Defaults to `console`.
     */
    constructor(usageRepository: IUsageRepository, logger: Console = console) {
        if (!usageRepository) {
            throw new Error('CH_UsageService: UsageRepository must be provided.');
        }
        this.usageRepository = usageRepository;
        this.logger = logger;
        this.logger.info('CH_UsageService initialized.');
    }

    /**
     * Records a single usage event for a given user and subscription.
     * This method is central to AE21, capturing granular usage data.
     *
     * @param userId The ID of the user performing the action.
     * @param subscriptionId The ID of the subscription associated with the usage.
     * @param metricName The name of the usage metric (e.g., 'API_CALLS', 'STORAGE_GB_HOURS').
     * @param quantity The amount of usage for this metric. Must be a positive number.
     * @param timestamp Optional. The time the usage occurred. Defaults to the current time.
     * @returns The created UsageRecord.
     * @throws Error if input validation fails or the record cannot be persisted.
     */
    public async recordUsage(
        userId: string,
        subscriptionId: string,
        metricName: UsageMetric,
        quantity: number,
        timestamp: Date = new Date()
    ): Promise<UsageRecord> {
        this.logger.debug(`Attempting to record usage: userId=${userId}, subId=${subscriptionId}, metric=${metricName}, quantity=${quantity}`);

        // Input validation
        if (!userId || typeof userId !== 'string') {
            throw new Error('CH_UsageService: Invalid userId provided. Must be a non-empty string.');
        }
        if (!subscriptionId || typeof subscriptionId !== 'string') {
            throw new Error('CH_UsageService: Invalid subscriptionId provided. Must be a non-empty string.');
        }
        if (!this.getAvailableUsageMetrics().includes(metricName)) {
            throw new Error(`CH_UsageService: Invalid usage metric: '${metricName}'. Must be one of ${this.getAvailableUsageMetrics().join(', ')}.`);
        }
        if (typeof quantity !== 'number' || quantity <= 0) {
            throw new Error('CH_UsageService: Quantity must be a positive number.');
        }
        if (!(timestamp instanceof Date) || isNaN(timestamp.getTime())) {
            throw new Error('CH_UsageService: Invalid timestamp provided. Must be a valid Date object.');
        }

        try {
            const newRecord = await this.usageRepository.createUsageRecord({
                userId,
                subscriptionId,
                metricName,
                quantity,
                timestamp,
            });
            this.logger.info(`Successfully recorded usage for subscription ${subscriptionId}, metric ${metricName}: ${quantity}`);
            return newRecord;
        } catch (error) {
            this.logger.error(`Failed to record usage for subscription ${subscriptionId}, metric ${metricName}:`, error);
            throw new Error(`CH_UsageService: Failed to record usage: ${(error as Error).message}`);
        }
    }

    /**
     * Retrieves all raw usage records for a specific subscription within a given time period.
     * This method supports AE22 by providing the detailed data needed for billing analysis.
     *
     * @param subscriptionId The ID of the subscription.
     * @param startDate The start date of the period (inclusive).
     * @param endDate The end date of the period (inclusive).
     * @returns An array of UsageRecord objects.
     * @throws Error if input validation fails or retrieval from the repository fails.
     */
    public async getRawUsageForSubscription(
        subscriptionId: string,
        startDate: Date,
        endDate: Date
    ): Promise<UsageRecord[]> {
        this.logger.debug(`Fetching raw usage for subscription ${subscriptionId} from ${startDate.toISOString()} to ${endDate.toISOString()}`);

        // Input validation
        if (!subscriptionId || typeof subscriptionId !== 'string') {
            throw new Error('CH_UsageService: Invalid subscriptionId provided. Must be a non-empty string.');
        }
        if (!(startDate instanceof Date) || isNaN(startDate.getTime())) {
            throw new Error('CH_UsageService: Invalid startDate provided. Must be a valid Date object.');
        }
        if (!(endDate instanceof Date) || isNaN(endDate.getTime())) {
            throw new Error('CH_UsageService: Invalid endDate provided. Must be a valid Date object.');
        }
        if (startDate > endDate) {
            throw new Error('CH_UsageService: startDate cannot be after endDate.');
        }

        try {
            const records = await this.usageRepository.getUsageRecordsBySubscriptionId(subscriptionId, startDate, endDate);
            this.logger.info(`Retrieved ${records.length} raw usage records for subscription ${subscriptionId}.`);
            return records;
        } catch (error) {
            this.logger.error(`Failed to retrieve raw usage for subscription ${subscriptionId}:`, error);
            throw new Error(`CH_UsageService: Failed to retrieve raw usage: ${(error as Error).message}`);
        }
    }

    /**
     * Aggregates usage data for a specific subscription within a given time period.
     * This is crucial for generating billing summaries and implements a key part of AE22.
     * The aggregation sums the quantities for each unique usage metric.
     *
     * @param subscriptionId The ID of the subscription.
     * @param startDate The start date of the period (inclusive).
     * @param endDate The end date of the period (inclusive).
     * @returns An object where keys are UsageMetric names and values are the total quantity for that metric.
     *          All available metrics will be present, initialized to 0 if no usage was recorded.
     * @throws Error if input validation fails or aggregation fails.
     */
    public async getAggregatedUsageForSubscription(
        subscriptionId: string,
        startDate: Date,
        endDate: Date
    ): Promise<Record<UsageMetric, number>> {
        this.logger.debug(`Aggregating usage for subscription ${subscriptionId} from ${startDate.toISOString()} to ${endDate.toISOString()}`);

        // Reuse validation from getRawUsageForSubscription
        // This will throw an error if validation fails, preventing further execution.
        await this.getRawUsageForSubscription(subscriptionId, startDate, endDate);

        try {
            const records = await this.usageRepository.getUsageRecordsBySubscriptionId(subscriptionId, startDate, endDate);

            const aggregatedUsage: Record<UsageMetric, number> = {} as Record<UsageMetric, number>;
            // Initialize all possible metrics to 0 to ensure a complete billing summary
            for (const metric of this.getAvailableUsageMetrics()) {
                aggregatedUsage[metric] = 0;
            }

            for (const record of records) {
                aggregatedUsage[record.metricName] = (aggregatedUsage[record.metricName] || 0) + record.quantity;
            }

            this.logger.info(`Aggregated usage for subscription ${subscriptionId}: ${JSON.stringify(aggregatedUsage)}`);
            return aggregatedUsage;
        } catch (error) {
            this.logger.error(`Failed to aggregate usage for subscription ${subscriptionId}:`, error);
            throw new Error(`CH_UsageService: Failed to aggregate usage: ${(error as Error).message}`);
        }
    }

    /**
     * Returns a list of all currently defined usage metrics.
     * This can be used by other services or UI components to display options or validate inputs.
     * @returns An array of UsageMetric strings.
     */
    public getAvailableUsageMetrics(): UsageMetric[] {
        return ['API_CALLS', 'STORAGE_GB_HOURS', 'COMPUTE_UNITS', 'DATA_TRANSFER_GB', 'AI_MODEL_INFERENCE_UNITS'];
    }
}