/*
 * Copyright (c) 2024 Ecosystem Architect. All rights reserved.
 *
 * This software is the confidential and proprietary information of the Ecosystem.
 * You shall not disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into with the Ecosystem.
 *
 * APP_18_Governance_Explainability
 * Domain: Governance & Policy Enforcement
 * Purpose: Core logic for generating human-readable explanations for AI decisions.
 *
 * LEGAL DISCLAIMER:
 * This software provides automated explanations for AI model outputs. These explanations
 * are probabilistic and generated by secondary AI models. They do not constitute
 * legal advice or guaranteed causal reasoning. Users must verify critical explanations
 * with human subject matter experts.
 */

import { EventEmitter } from 'events';
import { randomUUID } from 'crypto';

// -----------------------------------------------------------------------------
// SHARED CORE MOCKS (Assumed to be in @ecosystem/shared-sdk)
// -----------------------------------------------------------------------------

interface Logger {
    info(msg: string, meta?: any): void;
    error(msg: string, meta?: any): void;
    warn(msg: string, meta?: any): void;
    debug(msg: string, meta?: any): void;
}

interface EventBus {
    publish(topic: string, payload: any): Promise<void>;
}

interface AIProvider {
    name: string;
    complete(prompt: string, config: any): Promise<string>;
    healthCheck(): Promise<boolean>;
}

class MockLogger implements Logger {
    info(msg: string, meta?: any) { console.log(`[INFO] ${msg}`, meta || ''); }
    error(msg: string, meta?: any) { console.error(`[ERROR] ${msg}`, meta || ''); }
    warn(msg: string, meta?: any) { console.warn(`[WARN] ${msg}`, meta || ''); }
    debug(msg: string, meta?: any) { console.debug(`[DEBUG] ${msg}`, meta || ''); }
}

// -----------------------------------------------------------------------------
// DOMAIN TYPES
// -----------------------------------------------------------------------------

export enum ExplanationMode {
    TECHNICAL = 'TECHNICAL', // Feature weights, raw logits
    EXECUTIVE = 'EXECUTIVE', // High-level summary, risk score
    COMPLIANCE = 'COMPLIANCE', // Audit trail, specific regulatory references
    CUSTOMER = 'CUSTOMER', // Simplified, "Why did I get this?"
}

export enum RiskLevel {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
    CRITICAL = 'CRITICAL',
}

export interface ModelContext {
    modelId: string;
    provider: string;
    modelVersion: string;
    inputVector?: Record<string, any>;
    prompt?: string;
    output: string;
    timestamp: number;
    metadata: Record<string, any>;
}

export interface ExplanationRequest {
    requestId: string;
    context: ModelContext;
    mode: ExplanationMode;
    jurisdiction: string; // e.g., "EU_GDPR", "US_FCRA"
    targetAudienceLevel: 'novice' | 'expert' | 'auditor';
    includeCounterfactuals: boolean;
}

export interface FeatureImportance {
    featureName: string;
    importanceScore: number; // -1.0 to 1.0
    contributionType: 'positive' | 'negative' | 'neutral';
    confidence: number;
}

export interface CounterfactualScenario {
    changedFeature: string;
    originalValue: any;
    newValue: any;
    predictedOutcome: string;
    likelihood: number;
}

export interface ExplanationResult {
    explanationId: string;
    requestId: string;
    generatedAt: string;
    summary: string;
    detailedNarrative: string;
    featureImportance: FeatureImportance[];
    counterfactuals: CounterfactualScenario[];
    riskAssessment: {
        level: RiskLevel;
        flags: string[];
        reasoning: string;
    };
    meta: {
        explainerModel: string;
        latencyMs: number;
        costEstimateUSD: number;
    };
}

// -----------------------------------------------------------------------------
// CORE SERVICE
// -----------------------------------------------------------------------------

export class ExplainerService {
    private logger: Logger;
    private eventBus: EventBus;
    private primaryLLM: AIProvider; // e.g., OpenAI GPT-4
    private verifierLLM: AIProvider; // e.g., Anthropic Claude 3
    private config: any;

    // Introspection Metadata
    public readonly agentMetadata = {
        purpose: "Generate legally defensible, human-readable explanations for black-box AI decisions.",
        dependencies: ["OpenAI_GPT4", "Anthropic_Claude3", "VectorStore_Policies"],
        invalidation_conditions: ["Model drift > 5%", "Regulatory schema update", "Low confidence score"],
        adjacent_apps: ["APP_37_Governance_AuditTrailEngine", "APP_05_Inference_Gateway"]
    };

    constructor(
        logger: Logger,
        eventBus: EventBus,
        primaryLLM: AIProvider,
        verifierLLM: AIProvider,
        config: any
    ) {
        this.logger = logger || new MockLogger();
        this.eventBus = eventBus;
        this.primaryLLM = primaryLLM;
        this.verifierLLM = verifierLLM;
        this.config = config || {};
    }

    /**
     * Main entry point to generate an explanation.
     * Orchestrates feature extraction, counterfactual generation, and narrative synthesis.
     */
    public async explainDecision(request: ExplanationRequest): Promise<ExplanationResult> {
        const startTime = Date.now();
        this.logger.info(`Starting explanation generation for request ${request.requestId}`, { mode: request.mode });

        try {
            // 1. Validation & Compliance Check
            this.validateRequest(request);

            // 2. Feature Importance Analysis (Perturbation / Gradient Proxy)
            const featureImportance = await this.analyzeFeatureImportance(request.context);

            // 3. Counterfactual Generation (if requested)
            let counterfactuals: CounterfactualScenario[] = [];
            if (request.includeCounterfactuals) {
                counterfactuals = await this.generateCounterfactuals(request.context, featureImportance);
            }

            // 4. Risk Assessment
            const riskAssessment = await this.assessRisk(request.context, featureImportance);

            // 5. Narrative Synthesis (The "Story")
            const narrative = await this.synthesizeNarrative(
                request,
                featureImportance,
                counterfactuals,
                riskAssessment
            );

            // 6. Verification (Adversarial Check)
            await this.verifyExplanation(narrative, request.context);

            const result: ExplanationResult = {
                explanationId: randomUUID(),
                requestId: request.requestId,
                generatedAt: new Date().toISOString(),
                summary: narrative.summary,
                detailedNarrative: narrative.detail,
                featureImportance,
                counterfactuals,
                riskAssessment,
                meta: {
                    explainerModel: this.primaryLLM.name,
                    latencyMs: Date.now() - startTime,
                    costEstimateUSD: this.calculateCost(narrative.tokenCount)
                }
            };

            // 7. Audit Logging & Event Emission
            await this.emitAuditTrail(result);

            return result;

        } catch (error) {
            this.logger.error(`Explanation failed for ${request.requestId}`, error);
            await this.eventBus.publish('EXPLANATION_FAILURE', {
                requestId: request.requestId,
                error: error instanceof Error ? error.message : 'Unknown error'
            });
            throw error;
        }
    }

    /**
     * Simulates a perturbation-based feature importance analysis (LIME-like).
     * In a real implementation, this would call a dedicated Python service or use ONNX runtime.
     */
    private async analyzeFeatureImportance(context: ModelContext): Promise<FeatureImportance[]> {
        this.logger.debug("Analyzing feature importance via perturbation proxy...");
        
        // Mock logic: If input is structured, analyze keys. If text, analyze keywords.
        const features: FeatureImportance[] = [];
        
        if (context.inputVector) {
            for (const [key, value] of Object.entries(context.inputVector)) {
                // Heuristic: numeric magnitude or specific flags trigger importance
                const score = Math.random() * 2 - 1; // Random -1 to 1 for simulation
                features.push({
                    featureName: key,
                    importanceScore: parseFloat(score.toFixed(4)),
                    contributionType: score > 0 ? 'positive' : (score < 0 ? 'negative' : 'neutral'),
                    confidence: 0.85 + (Math.random() * 0.1)
                });
            }
        } else if (context.prompt) {
            // Text based importance (Keyword extraction simulation)
            const words = context.prompt.split(' ').slice(0, 5); // Take first 5 words as "features"
            words.forEach(w => {
                features.push({
                    featureName: `token:${w}`,
                    importanceScore: 0.5,
                    contributionType: 'positive',
                    confidence: 0.9
                });
            });
        }

        // Sort by absolute importance
        return features.sort((a, b) => Math.abs(b.importanceScore) - Math.abs(a.importanceScore));
    }

    /**
     * Generates "What if?" scenarios using the Verifier LLM to ensure distinct reasoning paths.
     */
    private async generateCounterfactuals(
        context: ModelContext, 
        features: FeatureImportance[]
    ): Promise<CounterfactualScenario[]> {
        this.logger.debug("Generating counterfactuals...");

        const topFeatures = features.slice(0, 3);
        const scenarios: CounterfactualScenario[] = [];

        // Prompt engineering for the verifier model to hallucinate plausible alternatives
        const prompt = `
            Given the input context: ${JSON.stringify(context.inputVector || context.prompt)}
            And the output: "${context.output}"
            
            Identify 3 critical changes to the input that would likely flip the output or significantly change the outcome.
            Return JSON array.
        `;

        try {
            // Abstracted call to Anthropic/Verifier
            const response = await this.verifierLLM.complete(prompt, { temperature: 0.2 });
            
            // Mock parsing logic (assuming the LLM returns valid JSON for this exercise)
            // In production, use a robust parser like Zod
            topFeatures.forEach(f => {
                scenarios.push({
                    changedFeature: f.featureName,
                    originalValue: "X",
                    newValue: "Y",
                    predictedOutcome: "Outcome flipped to REJECT",
                    likelihood: 0.75
                });
            });
        } catch (e) {
            this.logger.warn("Failed to generate counterfactuals via LLM, falling back to heuristics.");
        }

        return scenarios;
    }

    /**
     * Synthesizes the technical data into a human-readable narrative based on the requested mode.
     */
    private async synthesizeNarrative(
        request: ExplanationRequest,
        features: FeatureImportance[],
        counterfactuals: CounterfactualScenario[],
        risk: any
    ): Promise<{ summary: string; detail: string; tokenCount: number }> {
        
        const systemPrompt = `
            You are a Compliance Officer and AI Explainability Expert.
            Mode: ${request.mode}
            Audience: ${request.targetAudienceLevel}
            Jurisdiction: ${request.jurisdiction}
            
            Task: Explain why the AI model made its decision.
            Constraints:
            - Be objective.
            - Use the provided feature importance data.
            - Do not hallucinate data not present.
            - If Risk is HIGH, use cautionary language.
        `;

        const dataPayload = JSON.stringify({
            input: request.context.inputVector || request.context.prompt,
            output: request.context.output,
            topFeatures: features.slice(0, 5),
            counterfactuals: counterfactuals,
            riskLevel: risk.level
        });

        const userPrompt = `Data: ${dataPayload}\n\nGenerate a summary (max 2 sentences) and a detailed narrative.`;

        // Call Primary LLM (e.g., OpenAI)
        const rawResponse = await this.primaryLLM.complete(`${systemPrompt}\n\n${userPrompt}`, { temperature: 0.1 });

        // Mock parsing of the response
        return {
            summary: rawResponse.substring(0, 100) + "...", // Mock split
            detail: rawResponse,
            tokenCount: rawResponse.length / 4 // Rough estimate
        };
    }

    /**
     * Evaluates the decision for potential compliance risks or bias.
     */
    private async assessRisk(context: ModelContext, features: FeatureImportance[]): Promise<any> {
        // Check for protected class proxies in features
        const protectedTerms = ['race', 'gender', 'zipcode', 'age', 'religion'];
        const flags: string[] = [];
        
        features.forEach(f => {
            if (protectedTerms.some(t => f.featureName.toLowerCase().includes(t))) {
                flags.push(`Protected attribute detected: ${f.featureName}`);
            }
        });

        let level = RiskLevel.LOW;
        if (flags.length > 0) level = RiskLevel.HIGH;
        if (flags.length > 2) level = RiskLevel.CRITICAL;

        return {
            level,
            flags,
            reasoning: flags.length > 0 
                ? "Decision heavily relies on protected attributes or their proxies." 
                : "No immediate bias indicators found in top features."
        };
    }

    /**
     * Cross-checks the generated narrative against the raw data using a second model.
     * This implements the "Speed vs Safety" tension. Safety adds latency.
     */
    private async verifyExplanation(narrative: { summary: string, detail: string }, context: ModelContext): Promise<void> {
        if (this.config.skipVerification) return;

        const verificationPrompt = `
            Original Output: ${context.output}
            Generated Explanation: ${narrative.summary}
            
            Does this explanation accurately reflect the output? Answer YES or NO with confidence score.
        `;

        const check = await this.verifierLLM.complete(verificationPrompt, { maxTokens: 10 });
        if (check.includes("NO")) {
            this.logger.warn("Explanation verification failed. Flagging for human review.");
            // In a real system, we might retry or flag the result object
        }
    }

    private validateRequest(request: ExplanationRequest) {
        if (!request.context || !request.context.output) {
            throw new Error("Invalid context: Missing output to explain.");
        }
        // Jurisdictional checks
        if (request.jurisdiction === 'EU_GDPR' && request.mode === ExplanationMode.TECHNICAL) {
            // GDPR "Right to Explanation" often requires simplified logic, not just weights
            this.logger.info("GDPR context detected: Enforcing simplification layers.");
        }
    }

    private calculateCost(tokens: number): number {
        // Mock pricing: $0.03 per 1k tokens
        return (tokens / 1000) * 0.03;
    }

    private async emitAuditTrail(result: ExplanationResult) {
        await this.eventBus.publish('GOVERNANCE_AUDIT_LOG', {
            type: 'EXPLANATION_GENERATED',
            payload: result,
            timestamp: Date.now(),
            signature: 'sha256-mock-signature'
        });
    }

    // -------------------------------------------------------------------------
    // INTROSPECTION API (Self-Querying Agent Mode)
    // -------------------------------------------------------------------------

    public introspect() {
        return {
            status: 'HEALTHY',
            models: {
                primary: this.primaryLLM.name,
                verifier: this.verifierLLM.name
            },
            metrics: {
                explanationsGenerated: 1420, // Mock state
                averageLatency: 450
            },
            config: this.config
        };
    }

    public getAssumptions() {
        return [
            "Feature importance can be linearly approximated via perturbation.",
            "The primary LLM does not hallucinate facts about the input vector.",
            "Users requesting 'EXECUTIVE' mode prefer brevity over completeness."
        ];
    }

    public getFailureModes() {
        return [
            "Model Collapse: If the primary LLM degrades, explanations become generic.",
            "Adversarial Input: Crafted inputs might trick the feature importance scorer.",
            "Privacy Leak: Explanation might inadvertently reveal training data snippets."
        ];
    }

    public getUpdateTriggers() {
        return [
            "New regulatory framework (e.g., EU AI Act updates).",
            "Drift detection in the underlying model > 10%.",
            "New adapter availability for superior reasoning models."
        ];
    }
}

// -----------------------------------------------------------------------------
// FACTORY / EXPORT
// -----------------------------------------------------------------------------

export function createExplainer(
    logger: Logger, 
    eventBus: EventBus, 
    primary: AIProvider, 
    verifier: AIProvider
) {
    return new ExplainerService(logger, eventBus, primary, verifier, {
        skipVerification: process.env.SKIP_VERIFICATION === 'true',
        jurisdictionDefault: 'US_GENERIC'
    });
}