import express, { Request, Response } from 'express';
import { body, validationResult } from 'express-validator';
import { PortfolioService } from '../services/PortfolioService';
import { Portfolio } from '../models/Portfolio';
import { AssetAllocation } from '../models/AssetAllocation';
import { RiskTolerance } from '../models/RiskTolerance';
import { FinancialGoal } from '../models/FinancialGoal';
import { PortfolioPerformance } from '../models/PortfolioPerformance';
import { AuthenticationMiddleware } from '../middleware/AuthenticationMiddleware';
import { AuthorizationMiddleware } from '../middleware/AuthorizationMiddleware';
import { UserRole } from '../models/UserRole';

const router = express.Router();

const portfolioService = new PortfolioService();

// Authentication middleware (apply to all routes below)
router.use(AuthenticationMiddleware.authenticate);

/**
 * @route   GET /api/v1/portfolios
 * @desc    Get all portfolios for the authenticated user
 * @access  Private
 */
router.get('/', async (req: Request, res: Response) => {
  try {
    const userId = req.user?.id; // Assuming user ID is available in the request after authentication
    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized: User ID not found' });
    }

    const portfolios = await portfolioService.getPortfoliosByUserId(userId);
    res.json(portfolios);
  } catch (error: any) {
    console.error(error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

/**
 * @route   GET /api/v1/portfolios/:id
 * @desc    Get a portfolio by ID
 * @access  Private
 */
router.get('/:id', async (req: Request, res: Response) => {
  try {
    const portfolioId = req.params.id;
    const userId = req.user?.id;

    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized: User ID not found' });
    }

    const portfolio = await portfolioService.getPortfolioById(portfolioId, userId);

    if (!portfolio) {
      return res.status(404).json({ message: 'Portfolio not found' });
    }

    res.json(portfolio);
  } catch (error: any) {
    console.error(error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

/**
 * @route   POST /api/v1/portfolios
 * @desc    Create a new portfolio
 * @access  Private
 */
router.post(
  '/',
  [
    body('name').notEmpty().withMessage('Name is required'),
    body('description').optional().isString(),
    body('assetAllocation').optional().isObject(),
    body('riskTolerance').optional().isIn(Object.values(RiskTolerance)),
    body('financialGoals').optional().isArray(),
  ],
  async (req: Request, res: Response) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    try {
      const userId = req.user?.id;
      if (!userId) {
        return res.status(401).json({ message: 'Unauthorized: User ID not found' });
      }

      const { name, description, assetAllocation, riskTolerance, financialGoals } = req.body;

      const newPortfolio: Portfolio = {
        id: '', // Will be generated by the service
        userId: userId,
        name,
        description,
        assetAllocation: assetAllocation as AssetAllocation,
        riskTolerance: riskTolerance as RiskTolerance,
        financialGoals: financialGoals as FinancialGoal[],
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const createdPortfolio = await portfolioService.createPortfolio(newPortfolio);
      res.status(201).json(createdPortfolio);
    } catch (error: any) {
      console.error(error);
      res.status(500).json({ message: 'Server error', error: error.message });
    }
  }
);

/**
 * @route   PUT /api/v1/portfolios/:id
 * @desc    Update a portfolio
 * @access  Private
 */
router.put(
  '/:id',
  [
    body('name').optional().notEmpty().withMessage('Name is required'),
    body('description').optional().isString(),
    body('assetAllocation').optional().isObject(),
    body('riskTolerance').optional().isIn(Object.values(RiskTolerance)),
    body('financialGoals').optional().isArray(),
  ],
  async (req: Request, res: Response) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    try {
      const portfolioId = req.params.id;
      const userId = req.user?.id;

      if (!userId) {
        return res.status(401).json({ message: 'Unauthorized: User ID not found' });
      }

      const { name, description, assetAllocation, riskTolerance, financialGoals } = req.body;

      const updatedPortfolioData: Partial<Portfolio> = {
        name,
        description,
        assetAllocation: assetAllocation as AssetAllocation,
        riskTolerance: riskTolerance as RiskTolerance,
        financialGoals: financialGoals as FinancialGoal[],
        updatedAt: new Date(),
      };

      const updatedPortfolio = await portfolioService.updatePortfolio(portfolioId, userId, updatedPortfolioData);

      if (!updatedPortfolio) {
        return res.status(404).json({ message: 'Portfolio not found' });
      }

      res.json(updatedPortfolio);
    } catch (error: any) {
      console.error(error);
      res.status(500).json({ message: 'Server error', error: error.message });
    }
  }
);

/**
 * @route   DELETE /api/v1/portfolios/:id
 * @desc    Delete a portfolio
 * @access  Private
 */
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const portfolioId = req.params.id;
    const userId = req.user?.id;

    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized: User ID not found' });
    }

    const deleted = await portfolioService.deletePortfolio(portfolioId, userId);

    if (!deleted) {
      return res.status(404).json({ message: 'Portfolio not found' });
    }

    res.status(204).send(); // No content
  } catch (error: any) {
    console.error(error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

/**
 * @route   GET /api/v1/portfolios/:id/performance
 * @desc    Get performance data for a portfolio
 * @access  Private
 */
router.get('/:id/performance', async (req: Request, res: Response) => {
  try {
    const portfolioId = req.params.id;
    const userId = req.user?.id;

    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized: User ID not found' });
    }

    const performanceData = await portfolioService.getPortfolioPerformance(portfolioId, userId);

    if (!performanceData) {
      return res.status(404).json({ message: 'Portfolio performance data not found' });
    }

    res.json(performanceData);
  } catch (error: any) {
    console.error(error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

/**
 * @route   POST /api/v1/portfolios/:id/rebalance
 * @desc    Rebalance a portfolio
 * @access  Private
 */
router.post('/:id/rebalance', async (req: Request, res: Response) => {
  try {
    const portfolioId = req.params.id;
    const userId = req.user?.id;

    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized: User ID not found' });
    }

    const rebalancedPortfolio = await portfolioService.rebalancePortfolio(portfolioId, userId);

    if (!rebalancedPortfolio) {
      return res.status(404).json({ message: 'Portfolio not found' });
    }

    res.json(rebalancedPortfolio);
  } catch (error: any) {
    console.error(error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

/**
 * @route   GET /api/v1/portfolios/recommendations
 * @desc    Get portfolio recommendations based on user profile
 * @access  Private
 */
router.get('/recommendations', async (req: Request, res: Response) => {
  try {
    const userId = req.user?.id;

    if (!userId) {
      return res.status(401).json({ message: 'Unauthorized: User ID not found' });
    }

    const recommendations = await portfolioService.getPortfolioRecommendations(userId);
    res.json(recommendations);
  } catch (error: any) {
    console.error(error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

// Admin-only route to get all portfolios (for monitoring/admin purposes)
router.get('/admin/all',
  AuthorizationMiddleware.authorize([UserRole.Admin]),
  async (req: Request, res: Response) => {
    try {
      const allPortfolios = await portfolioService.getAllPortfolios();
      res.json(allPortfolios);
    } catch (error: any) {
      console.error(error);
      res.status(500).json({ message: 'Server error', error: error.message });
    }
  });

export default router;