import { IResolvers } from '@graphql-tools/utils';

// NOTE: In a real project, these types would likely be generated by a tool like GraphQL Code Generator.
// They are defined here for clarity and to make the resolvers type-safe.

interface User {
  id: string;
  name: string;
  email: string;
}

interface Post {
  id: string;
  title: string;
  content: string;
  authorId: string;
}

interface CreateUserInput {
  name: string;
  email: string;
  // password would be here in a real app
}

interface CreatePostInput {
  title: string;
  content: string;
  authorId: string;
}

// Define the shape of the data sources that will be available in the context.
// These would typically be classes that handle fetching data from microservices.
interface GatewayDataSources {
  usersAPI: {
    getAllUsers: () => Promise<User[]>;
    getUserById: (id: string) => Promise<User | null>;
    createUser: (input: CreateUserInput) => Promise<User>;
  };
  postsAPI: {
    getAllPosts: () => Promise<Post[]>;
    getPostById: (id: string) => Promise<Post | null>;
    getPostsByAuthorId: (authorId: string) => Promise<Post[]>;
    createPost: (input: CreatePostInput) => Promise<Post>;
  };
}

// Define the GraphQL context type for our resolvers.
export interface GatewayContext {
  dataSources: GatewayDataSources;
  // Example of other context properties
  // userId?: string;
}

export const resolvers: IResolvers<any, GatewayContext> = {
  Query: {
    /**
     * Retrieves a list of all users.
     * Delegates the call to the Users microservice.
     */
    users: (_, __, { dataSources }) => {
      return dataSources.usersAPI.getAllUsers();
    },

    /**
     * Retrieves a single user by their ID.
     * Delegates the call to the Users microservice.
     */
    user: (_, { id }: { id: string }, { dataSources }) => {
      return dataSources.usersAPI.getUserById(id);
    },

    /**
     * Retrieves a list of all posts.
     * Delegates the call to the Posts microservice.
     */
    posts: (_, __, { dataSources }) => {
      return dataSources.postsAPI.getAllPosts();
    },

    /**
     * Retrieves a single post by its ID.
     * Delegates the call to the Posts microservice.
     */
    post: (_, { id }: { id: string }, { dataSources }) => {
      return dataSources.postsAPI.getPostById(id);
    },
  },

  Mutation: {
    /**
     * Creates a new user.
     * Delegates the call to the Users microservice.
     */
    createUser: (_, { input }: { input: CreateUserInput }, { dataSources }) => {
      return dataSources.usersAPI.createUser(input);
    },

    /**
     * Creates a new post.
     * Delegates the call to the Posts microservice.
     * A real-world implementation would likely include authentication/authorization.
     */
    createPost: (_, { input }: { input: CreatePostInput }, { dataSources }) => {
      return dataSources.postsAPI.createPost(input);
    },
  },

  /**
   * Field resolvers for handling relationships between types.
   * This is a key feature of a GraphQL gateway, allowing for data composition
   * from multiple microservices into a single, unified graph.
   */

  User: {
    /**
     * Resolves the 'posts' field for a User.
     * Fetches all posts written by the parent User object.
     * Delegates the call to the Posts microservice.
     */
    posts: (user: User, _, { dataSources }) => {
      return dataSources.postsAPI.getPostsByAuthorId(user.id);
    },
  },

  Post: {
    /**
     * Resolves the 'author' field for a Post.
     * Fetches the User who is the author of the parent Post object.
     * Delegates the call to the Users microservice.
     */
    author: (post: Post, _, { dataSources }) => {
      return dataSources.usersAPI.getUserById(post.authorId);
    },
  },
};