/**
 * @license
 * Copyright 2024 Aethernaut Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { io, Socket } from 'socket.io-client';
import { ZodSchema, ZodError } from 'zod';
import { v4 as uuidv4 } from 'uuid';

// Local SDK imports
import { AetherAuthTokenProvider } from '../auth/authTokenProvider';
import { AetherLogger, createDefaultLogger } from '../observability/logging';
import { EventSchemas, getEventSchema } from '../ontology/events';

// --- Type Definitions ---

/**
 * Represents the payload type for a given event name from the central ontology.
 */
export type EventPayload<T extends keyof EventSchemas> = EventSchemas[T];

/**
 * Defines the shape of a handler function for a specific event.
 * @param payload The validated and typed event payload.
 * @param eventMeta Metadata associated with the event, like its ID and timestamp.
 */
export type EventHandler<T extends keyof EventSchemas> = (
  payload: EventPayload<T>,
  eventMeta: EventMetadata
) => void | Promise<void>;

/**
 * Metadata associated with every event on the bus.
 */
export interface EventMetadata {
  eventId: string;
  timestamp: string; // ISO 8601 format
  sourceApp: string; // The APP_NN_DOMAIN_FUNCTION identifier
  correlationId?: string;
}

/**
 * The full event structure that is transmitted over the wire.
 */
interface WireEvent<T extends keyof EventSchemas> {
  eventName: T;
  payload: EventPayload<T>;
  meta: EventMetadata;
}

/**
 * Configuration for the AetherEventBusClient.
 */
export interface AetherEventBusConfig {
  /**
   * The URL of the APP_03_Protocol_EventBusGateway.
   * e.g., "wss://events.aethernaut.ai"
   */
  gatewayUrl: string;

  /**
   * An instance of an AetherAuthTokenProvider to supply authentication tokens.
   */
  authTokenProvider: AetherAuthTokenProvider;

  /**
   * The unique identifier of the application connecting to the bus.
   * e.g., "APP_14_Agents_MultiModelOrchestrator"
   */
  sourceAppId: string;

  /**
   * Optional logger instance. If not provided, a default console logger will be used.
   */
  logger?: AetherLogger;

  /**
   * Connection and retry configuration.
   */
  connection?: {
    /** Time to wait for connection before timing out. Default: 10000ms */
    timeout?: number;
    /** Reconnection attempt options. */
    reconnection?: {
      /** Whether to automatically attempt to reconnect. Default: true */
      enabled?: boolean;
      /** Initial delay before first reconnection attempt. Default: 1000ms */
      initialDelay?: number;
      /** Maximum delay between attempts. Default: 30000ms */
      maxDelay?: number;
      /** Randomization factor for delays. Default: 0.5 */
      randomizationFactor?: number;
    };
  };
}

/**
 * Options for publishing an event.
 * This exposes the core tension between speed/cost and safety/reliability.
 */
export interface PublishOptions {
  /**
   * A unique identifier to correlate this event with other operations or events.
   * If not provided, a new one may be generated by the gateway.
   */
  correlationId?: string;

  /**
   * Defines the delivery guarantee for this event.
   * - 'best-effort': Fire-and-forget. Fastest, lowest cost, but messages can be lost.
   * - 'at-least-once': The client will wait for an acknowledgement from the gateway.
   *   Slower and more resource-intensive, but ensures the gateway has received the event.
   * Default: 'at-least-once'
   */
  delivery?: 'best-effort' | 'at-least-once';

  /**
   * Timeout in milliseconds for waiting for an acknowledgement when delivery is 'at-least-once'.
   * Default: 5000ms
   */
  ackTimeout?: number;
}

/**
 * Options for subscribing to an event stream.
 */
export interface SubscribeOptions {
  /**
   * If provided, joins a consumer group with this name.
   * Only one subscriber within a group will receive a given message, enabling distributed workloads.
   * If not provided, the subscription is unique and will receive all messages.
   */
  consumerGroup?: string;
}

export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'reconnecting' | 'error';

// --- Custom Errors ---

export class EventBusError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'EventBusError';
  }
}

export class EventBusConnectionError extends EventBusError {
  constructor(message: string) {
    super(message);
    this.name = 'EventBusConnectionError';
  }
}

export class EventBusPublishError extends EventBusError {
  public eventName: string;
  public reason: string;

  constructor(eventName: string, reason: string) {
    super(`Failed to publish event "${eventName}": ${reason}`);
    this.name = 'EventBusPublishError';
    this.eventName = eventName;
    this.reason = reason;
  }
}

export class EventBusSchemaValidationError extends EventBusPublishError {
  public validationErrors: ZodError;

  constructor(eventName: string, validationErrors: ZodError) {
    super(eventName, 'Payload failed schema validation.');
    this.name = 'EventBusSchemaValidationError';
    this.validationErrors = validationErrors;
  }
}


// --- The Client ---

/**
 * A typed, robust client for interacting with the Aethernaut ecosystem-wide event bus.
 * It connects to APP_03_Protocol_EventBusGateway and handles typed event publishing
 * and subscribing, authentication, and resilient connections.
 */
export class AetherEventBusClient {
  private config: AetherEventBusConfig;
  private logger: AetherLogger;
  private socket: Socket | null = null;
  private status: ConnectionStatus = 'disconnected';
  private subscriptions: Map<string, Set<(...args: any[]) => void>> = new Map();

  constructor(config: AetherEventBusConfig) {
    this.config = {
      ...config,
      connection: {
        timeout: config.connection?.timeout ?? 10000,
        reconnection: {
          enabled: config.connection?.reconnection?.enabled ?? true,
          initialDelay: config.connection?.reconnection?.initialDelay ?? 1000,
          maxDelay: config.connection?.reconnection?.maxDelay ?? 30000,
          randomizationFactor: config.connection?.reconnection?.randomizationFactor ?? 0.5,
        },
      },
    };
    this.logger = config.logger || createDefaultLogger('AetherEventBusClient');
    this.logger.info('Event bus client initialized.');
  }

  /**
   * Establishes a connection to the event bus gateway.
   * This method is idempotent.
   * @returns A promise that resolves when the connection is established, or rejects on failure.
   */
  public connect(): Promise<void> {
    if (this.socket && (this.status === 'connected' || this.status === 'connecting')) {
      this.logger.debug('Connect called while already connected or connecting. Ignoring.');
      return Promise.resolve();
    }

    this.logger.info(`Connecting to event bus gateway at ${this.config.gatewayUrl}...`);
    this.status = 'connecting';

    return new Promise(async (resolve, reject) => {
      try {
        const token = await this.config.authTokenProvider.getToken();
        
        this.socket = io(this.config.gatewayUrl, {
          auth: { token },
          reconnection: this.config.connection?.reconnection?.enabled,
          reconnectionDelay: this.config.connection?.reconnection?.initialDelay,
          reconnectionDelayMax: this.config.connection?.reconnection?.maxDelay,
          randomizationFactor: this.config.connection?.reconnection?.randomizationFactor,
          timeout: this.config.connection?.timeout,
          transports: ['websocket'], // Prioritize modern, efficient transport
        });

        this.setupSocketListeners(resolve, reject);

      } catch (error) {
        this.logger.error('Failed to get auth token for event bus connection.', { error });
        this.status = 'error';
        reject(new EventBusConnectionError('Authentication token provider failed.'));
      }
    });
  }

  /**
   * Disconnects from the event bus gateway.
   */
  public disconnect(): void {
    if (this.socket) {
      this.logger.info('Disconnecting from event bus gateway.');
      this.socket.disconnect();
      this.status = 'disconnected';
      this.socket = null;
      this.subscriptions.clear();
    }
  }

  /**
   * Publishes an event to the bus.
   * @param eventName The name of the event, must be a key in `EventSchemas`.
   * @param payload The event payload, which will be validated against the event's schema.
   * @param options Publishing options, controlling delivery guarantees.
   * @returns A promise that resolves when the event is successfully published according to the delivery option.
   */
  public async publish<T extends keyof EventSchemas>(
    eventName: T,
    payload: EventPayload<T>,
    options: PublishOptions = {}
  ): Promise<void> {
    const { delivery = 'at-least-once', ackTimeout = 5000, correlationId } = options;

    if (this.status !== 'connected') {
      throw new EventBusPublishError(eventName as string, 'Client is not connected.');
    }

    const schema = getEventSchema(eventName);
    if (!schema) {
      throw new EventBusPublishError(eventName as string, 'Unknown event type, no schema found in ontology.');
    }

    try {
      schema.parse(payload);
    } catch (error) {
      if (error instanceof ZodError) {
        throw new EventBusSchemaValidationError(eventName as string, error);
      }
      throw error; // Re-throw other errors
    }

    const wireMessage: WireEvent<T> = {
      eventName,
      payload,
      meta: {
        eventId: uuidv4(),
        timestamp: new Date().toISOString(),
        sourceApp: this.config.sourceAppId,
        correlationId,
      },
    };

    this.logger.debug(`Publishing event: ${eventName as string}`, { eventId: wireMessage.meta.eventId });

    if (delivery === 'best-effort') {
      this.socket!.emit('publish', wireMessage);
      return Promise.resolve();
    }

    // At-least-once delivery with acknowledgement
    return new Promise((resolve, reject) => {
      this.socket!
        .timeout(ackTimeout)
        .emit('publish', wireMessage, (err: any, response: any) => {
          if (err) {
            return reject(new EventBusPublishError(eventName as string, 'Acknowledgement timed out.'));
          }
          if (response?.status === 'ok') {
            this.logger.debug(`Event acknowledged: ${eventName as string}`, { eventId: wireMessage.meta.eventId });
            resolve();
          } else {
            reject(new EventBusPublishError(eventName as string, `Gateway rejected event: ${response?.reason || 'Unknown reason'}`));
          }
        });
    });
  }

  /**
   * Subscribes to an event type.
   * @param eventName The name of the event to listen for.
   * @param handler The function to call when the event is received.
   * @param options Subscription options, e.g., for joining a consumer group.
   * @returns An `unsubscribe` function to remove this specific subscription.
   */
  public subscribe<T extends keyof EventSchemas>(
    eventName: T,
    handler: EventHandler<T>,
    options: SubscribeOptions = {}
  ): () => void {
    if (!this.socket) {
      this.logger.warn(`Subscribing to "${eventName as string}" before connection is established. Subscription will be active upon connection.`);
    }

    const schema = getEventSchema(eventName);
    if (!schema) {
      this.logger.error(`Attempted to subscribe to unknown event "${eventName as string}". No schema found.`);
      // Return a no-op unsubscribe function
      return () => {};
    }

    const wrappedHandler = (wireMessage: WireEvent<T>) => {
      try {
        // Even though the gateway should validate, we re-validate on the client
        // as a defense-in-depth measure.
        schema.parse(wireMessage.payload);
        handler(wireMessage.payload, wireMessage.meta);
      } catch (error) {
        this.logger.error(`Schema validation failed for incoming event "${eventName as string}".`, {
          eventId: wireMessage.meta.eventId,
          error: error instanceof ZodError ? error.issues : error,
        });
      }
    };

    if (!this.subscriptions.has(eventName as string)) {
      this.subscriptions.set(eventName as string, new Set());
    }
    this.subscriptions.get(eventName as string)!.add(wrappedHandler);

    // Inform the gateway of the new subscription
    this.socket?.emit('subscribe', { eventName, options });
    this.logger.info(`Subscribed to event: ${eventName as string}`, { options });

    const unsubscribe = () => {
      const handlers = this.subscriptions.get(eventName as string);
      if (handlers) {
        handlers.delete(wrappedHandler);
        if (handlers.size === 0) {
          this.subscriptions.delete(eventName as string);
          // Inform the gateway we are no longer interested in this event type
          this.socket?.emit('unsubscribe', { eventName, options });
          this.logger.info(`Unsubscribed from all handlers for event: ${eventName as string}`);
        }
      }
    };

    return unsubscribe;
  }

  /**
   * Gets the current connection status.
   */
  public getStatus(): ConnectionStatus {
    return this.status;
  }

  private setupSocketListeners(
    connectResolve: () => void,
    connectReject: (reason?: any) => void
  ) {
    if (!this.socket) return;

    // Clear existing listeners to prevent duplicates on reconnect logic
    this.socket.off();

    this.socket.on('connect', () => {
      this.status = 'connected';
      this.logger.info(`Successfully connected to event bus gateway. Session ID: ${this.socket!.id}`);
      // Re-establish any subscriptions that were made before connecting
      this.resubscribeAll();
      connectResolve();
    });

    this.socket.on('connect_error', (err) => {
      this.logger.error('Event bus connection error.', { message: err.message });
      this.status = 'error';
      // The initial connection promise should fail on connect_error
      connectReject(new EventBusConnectionError(err.message));
    });

    this.socket.on('disconnect', (reason) => {
      this.status = 'disconnected';
      this.logger.warn(`Disconnected from event bus gateway. Reason: ${reason}`);
      if (reason === 'io server disconnect') {
        // The server forcefully disconnected the socket; we must reconnect manually
        this.socket!.connect();
      }
      // else, the client will automatically try to reconnect if configured
    });

    this.socket.on('reconnect_attempt', (attempt) => {
      this.status = 'reconnecting';
      this.logger.info(`Attempting to reconnect to event bus... (Attempt #${attempt})`);
    });

    this.socket.on('reconnect', (attempt) => {
      this.status = 'connected';
      this.logger.info(`Successfully reconnected to event bus after ${attempt} attempts.`);
      this.resubscribeAll();
    });

    this.socket.on('reconnect_failed', () => {
      this.status = 'error';
      this.logger.error('Failed to reconnect to the event bus after multiple attempts.');
    });

    // Central listener for all incoming events
    this.socket.on('event', (wireMessage: WireEvent<keyof EventSchemas>) => {
      const { eventName } = wireMessage;
      this.logger.debug(`Received event: ${eventName}`, { eventId: wireMessage.meta.eventId });
      const handlers = this.subscriptions.get(eventName);
      if (handlers) {
        handlers.forEach(handler => {
          try {
            handler(wireMessage);
          } catch (e) {
            this.logger.error(`Error in event handler for "${eventName}"`, { error: e });
          }
        });
      }
    });
  }

  /**
   * Re-sends all subscription requests to the gateway.
   * This is necessary after a successful reconnection.
   */
  private resubscribeAll() {
    if (!this.socket) return;
    this.logger.info('Re-establishing subscriptions with the gateway...');
    for (const eventName of this.subscriptions.keys()) {
      // Note: This simplified resubscribe doesn't retain consumer group options.
      // A more robust implementation would store the options along with the handlers.
      this.socket.emit('subscribe', { eventName });
      this.logger.debug(`Re-subscribed to ${eventName}`);
    }
  }
}

/**
 * Factory function to create and initialize an AetherEventBusClient.
 * @param config The configuration for the client.
 * @returns A promise that resolves with a connected client instance.
 */
export async function createEventBusClient(config: AetherEventBusConfig): Promise<AetherEventBusClient> {
  const client = new AetherEventBusClient(config);
  await client.connect();
  return client;
}