using Nethereum.ABI.Decoders;
using Nethereum.ABI.Encoders;
using Nethereum.Hex.HexTypes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Nethereum.Cognitive
{
    public static class OpcodeMapper
    {
        private static readonly Dictionary<byte, string> OpcodeNames = new Dictionary<byte, string>
        {
            { 0x00, "STOP" },
            { 0x01, "ADD" },
            { 0x02, "MUL" },
            { 0x03, "SUB" },
            { 0x04, "DIV" },
            { 0x05, "SDIV" },
            { 0x06, "MOD" },
            { 0x07, "SMOD" },
            { 0x08, "ADDMOD" },
            { 0x09, "MULMOD" },
            { 0x0a, "EXP" },
            { 0x0b, "SIGNEXTEND" },
            { 0x10, "LT" },
            { 0x11, "SLT" },
            { 0x12, "GTE" },
            { 0x13, "SGT" },
            { 0x14, "EQ" },
            { 0x15, "ISZERO" },
            { 0x16, "AND" },
            { 0x17, "OR" },
            { 0x18, "XOR" },
            { 0x19, "NOT" },
            { 0x1a, "BYTE" },
            { 0x1b, "SHL" },
            { 0x1c, "SHR" },
            { 0x1d, "SAR" },
            { 0x20, "SHA3" },
            { 0x30, "ADDRESS" },
            { 0x31, "BALANCE" },
            { 0x32, "CALLER" },
            { 0x33, "CALLVALUE" },
            { 0x34, "CALLDATALOAD" },
            { 0x35, "CALLDATASIZE" },
            { 0x36, "CALLDATACOPY" },
            { 0x37, "CODESIZE" },
            { 0x38, "CODECOPY" },
            { 0x39, "GASPRICE" },
            { 0x3a, "EXTCODESIZE" },
            { 0x3b, "EXTCODECOPY" },
            { 0x3c, "RETURNDATASIZE" },
            { 0x3d, "RETURNDATACOPY" },
            { 0x3e, "EXTCODEHASH" },
            { 0x40, "BLOCKHASH" },
            { 0x41, "COINBASE" },
            { 0x42, "TIMESTAMP" },
            { 0x43, "NUMBER" },
            { 0x44, "DIFFICULTY" },
            { 0x45, "GASLIMIT" },
            { 0x46, "CHAINID" },
            { 0x47, "SELFBALANCE" },
            { 0x48, "BASEFEE" },
            { 0x50, "POP" },
            { 0x51, "MLOAD" },
            { 0x52, "MSTORE" },
            { 0x53, "MSTORE8" },
            { 0x54, "SLOAD" },
            { 0x55, "SSTORE" },
            { 0x56, "JUMP" },
            { 0x57, "JUMPI" },
            { 0x58, "PC" },
            { 0x59, "MSIZE" },
            { 0x5a, "GAS" },
            { 0x5b, "JUMPDEST" },
            { 0x60, "PUSH1" },
            { 0x61, "PUSH2" },
            { 0x62, "PUSH3" },
            { 0x63, "PUSH4" },
            { 0x64, "PUSH5" },
            { 0x65, "PUSH6" },
            { 0x66, "PUSH7" },
            { 0x67, "PUSH8" },
            { 0x68, "PUSH9" },
            { 0x69, "PUSH10" },
            { 0x6a, "PUSH11" },
            { 0x6b, "PUSH12" },
            { 0x6c, "PUSH13" },
            { 0x6d, "PUSH14" },
            { 0x6e, "PUSH15" },
            { 0x6f, "PUSH16" },
            { 0x70, "PUSH17" },
            { 0x71, "PUSH18" },
            { 0x72, "PUSH19" },
            { 0x73, "PUSH20" },
            { 0x74, "PUSH21" },
            { 0x75, "PUSH22" },
            { 0x76, "PUSH23" },
            { 0x77, "PUSH24" },
            { 0x78, "PUSH25" },
            { 0x79, "PUSH26" },
            { 0x7a, "PUSH27" },
            { 0x7b, "PUSH28" },
            { 0x7c, "PUSH29" },
            { 0x7d, "PUSH30" },
            { 0x7e, "PUSH31" },
            { 0x7f, "PUSH32" },
            { 0x80, "DUP1" },
            { 0x81, "DUP2" },
            { 0x82, "DUP3" },
            { 0x83, "DUP4" },
            { 0x84, "DUP5" },
            { 0x85, "DUP6" },
            { 0x86, "DUP7" },
            { 0x87, "DUP8" },
            { 0x88, "DUP9" },
            { 0x89, "DUP10" },
            { 0x8a, "DUP11" },
            { 0x8b, "DUP12" },
            { 0x8c, "DUP13" },
            { 0x8d, "DUP14" },
            { 0x8e, "DUP15" },
            { 0x8f, "DUP16" },
            { 0x90, "SWAP1" },
            { 0x91, "SWAP2" },
            { 0x92, "SWAP3" },
            { 0x93, "SWAP4" },
            { 0x94, "SWAP5" },
            { 0x95, "SWAP6" },
            { 0x96, "SWAP7" },
            { 0x97, "SWAP8" },
            { 0x98, "SWAP9" },
            { 0x99, "SWAP10" },
            { 0x9a, "SWAP11" },
            { 0x9b, "SWAP12" },
            { 0x9c, "SWAP13" },
            { 0x9d, "SWAP14" },
            { 0x9e, "SWAP15" },
            { 0x9f, "SWAP16" },
            { 0xa0, "LOG0" },
            { 0xa1, "LOG1" },
            { 0xa2, "LOG2" },
            { 0xa3, "LOG3" },
            { 0xa4, "LOG4" },
            { 0xf0, "CREATE" },
            { 0xf1, "CALL" },
            { 0xf2, "CALLCODE" },
            { 0xf3, "RETURN" },
            { 0xf4, "DELEGATECALL" },
            { 0xf5, "CREATE2" },
            { 0xfa, "STATICCALL" },
            { 0xfd, "REVERT" },
            { 0xfe, "INVALID" },
            { 0xff, "SELFDESTRUCT" }
        };

        private static readonly Dictionary<string, string> HighLevelOpcodeMap = new Dictionary<string, string>
        {
            {"STOP", "Halt execution"},
            {"ADD", "Arithmetic addition"},
            {"MUL", "Arithmetic multiplication"},
            {"SUB", "Arithmetic subtraction"},
            {"DIV", "Integer division"},
            {"SDIV", "Signed integer division"},
            {"MOD", "Remainder operation"},
            {"SMOD", "Signed remainder operation"},
            {"ADDMOD", "Modular addition"},
            {"MULMOD", "Modular multiplication"},
            {"EXP", "Exponentiation"},
            {"SIGNEXTEND", "Sign extend"},
            {"LT", "Less than"},
            {"SLT", "Signed less than"},
            {"GTE", "Greater than or equal"},
            {"SGT", "Signed greater than"},
            {"EQ", "Equality check"},
            {"ISZERO", "Check if value is zero"},
            {"AND", "Bitwise AND"},
            {"OR", "Bitwise OR"},
            {"XOR", "Bitwise XOR"},
            {"NOT", "Bitwise NOT"},
            {"BYTE", "Retrieve byte from word"},
            {"SHL", "Left shift"},
            {"SHR", "Right shift"},
            {"SAR", "Arithmetic shift right"},
            {"SHA3", "SHA3-256 hashing"},
            {"ADDRESS", "Get address of executing contract"},
            {"BALANCE", "Get account balance"},
            {"CALLER", "Get message sender"},
            {"CALLVALUE", "Get sent value"},
            {"CALLDATALOAD", "Load 32 bytes from call data"},
            {"CALLDATASIZE", "Get size of call data"},
            {"CALLDATACOPY", "Copy call data to memory"},
            {"CODESIZE", "Get size of contract code"},
            {"CODECOPY", "Copy contract code to memory"},
            {"GASPRICE", "Get transaction gas price"},
            {"EXTCODESIZE", "Get external contract code size"},
            {"EXTCODECOPY", "Copy external contract code to memory"},
            {"RETURNDATASIZE", "Get size of returned data from last message call"},
            {"RETURNDATACOPY", "Copy returned data to memory"},
            {"EXTCODEHASH", "Get hash of external contract code"},
            {"BLOCKHASH", "Get hash of block"},
            {"COINBASE", "Get coinbase address (block beneficiary)"},
            {"TIMESTAMP", "Get timestamp"},
            {"NUMBER", "Get block number"},
            {"DIFFICULTY", "Get difficulty"},
            {"GASLIMIT", "Get block gas limit"},
            {"CHAINID", "Get chain ID"},
            {"SELFBALANCE", "Get contract's balance"},
            {"BASEFEE", "Get base fee per gas"},
            {"POP", "Remove item from stack"},
            {"MLOAD", "Load word from memory"},
            {"MSTORE", "Store word to memory"},
            {"MSTORE8", "Store byte to memory"},
            {"SLOAD", "Load from storage"},
            {"SSTORE", "Store to storage"},
            {"JUMP", "Jump to address"},
            {"JUMPI", "Conditional jump"},
            {"PC", "Get program counter"},
            {"MSIZE", "Get current memory size"},
            {"GAS", "Get available gas"},
            {"JUMPDEST", "Jump destination"},
            {"PUSH1", "Push 1 byte onto stack"},
            {"PUSH2", "Push 2 bytes onto stack"},
            {"PUSH3", "Push 3 bytes onto stack"},
            {"PUSH4", "Push 4 bytes onto stack"},
            {"PUSH5", "Push 5 bytes onto stack"},
            {"PUSH6", "Push 6 bytes onto stack"},
            {"PUSH7", "Push 7 bytes onto stack"},
            {"PUSH8", "Push 8 bytes onto stack"},
            {"PUSH9", "Push 9 bytes onto stack"},
            {"PUSH10", "Push 10 bytes onto stack"},
            {"PUSH11", "Push 11 bytes onto stack"},
            {"PUSH12", "Push 12 bytes onto stack"},
            {"PUSH13", "Push 13 bytes onto stack"},
            {"PUSH14", "Push 14 bytes onto stack"},
            {"PUSH15", "Push 15 bytes onto stack"},
            {"PUSH16", "Push 16 bytes onto stack"},
            {"PUSH17", "Push 17 bytes onto stack"},
            {"PUSH18", "Push 18 bytes onto stack"},
            {"PUSH19", "Push 19 bytes onto stack"},
            {"PUSH20", "Push 20 bytes onto stack"},
            {"PUSH21", "Push 21 bytes onto stack"},
            {"PUSH22", "Push 22 bytes onto stack"},
            {"PUSH23", "Push 23 bytes onto stack"},
            {"PUSH24", "Push 24 bytes onto stack"},
            {"PUSH25", "Push 25 bytes onto stack"},
            {"PUSH26", "Push 26 bytes onto stack"},
            {"PUSH27", "Push 27 bytes onto stack"},
            {"PUSH28", "Push 28 bytes onto stack"},
            {"PUSH29", "Push 29 bytes onto stack"},
            {"PUSH30", "Push 30 bytes onto stack"},
            {"PUSH31", "Push 31 bytes onto stack"},
            {"PUSH32", "Push 32 bytes onto stack"},
            {"DUP1", "Duplicate item 1 on stack"},
            {"DUP2", "Duplicate item 2 on stack"},
            {"DUP3", "Duplicate item 3 on stack"},
            {"DUP4", "Duplicate item 4 on stack"},
            {"DUP5", "Duplicate item 5 on stack"},
            {"DUP6", "Duplicate item 6 on stack"},
            {"DUP7", "Duplicate item 7 on stack"},
            {"DUP8", "Duplicate item 8 on stack"},
            {"DUP9", "Duplicate item 9 on stack"},
            {"DUP10", "Duplicate item 10 on stack"},
            {"DUP11", "Duplicate item 11 on stack"},
            {"DUP12", "Duplicate item 12 on stack"},
            {"DUP13", "Duplicate item 13 on stack"},
            {"DUP14", "Duplicate item 14 on stack"},
            {"DUP15", "Duplicate item 15 on stack"},
            {"DUP16", "Duplicate item 16 on stack"},
            {"SWAP1", "Swap item 1 and 2 on stack"},
            {"SWAP2", "Swap item 2 and 3 on stack"},
            {"SWAP3", "Swap item 3 and 4 on stack"},
            {"SWAP4", "Swap item 4 and 5 on stack"},
            {"SWAP5", "Swap item 5 and 6 on stack"},
            {"SWAP6", "Swap item 6 and 7 on stack"},
            {"SWAP7", "Swap item 7 and 8 on stack"},
            {"SWAP8", "Swap item 8 and 9 on stack"},
            {"SWAP9", "Swap item 9 and 10 on stack"},
            {"SWAP10", "Swap item 10 and 11 on stack"},
            {"SWAP11", "Swap item 11 and 12 on stack"},
            {"SWAP12", "Swap item 12 and 13 on stack"},
            {"SWAP13", "Swap item 13 and 14 on stack"},
            {"SWAP14", "Swap item 14 and 15 on stack"},
            {"SWAP15", "Swap item 15 and 16 on stack"},
            {"SWAP16", "Swap item 16 and 17 on stack"},
            {"LOG0", "Append log, topics=0, data size=0"},
            {"LOG1", "Append log, topics=1, data size=0"},
            {"LOG2", "Append log, topics=2, data size=0"},
            {"LOG3", "Append log, topics=3, data size=0"},
            {"LOG4", "Append log, topics=4, data size=0"},
            {"CREATE", "Create a new contract"},
            {"CALL", "External contract call"},
            {"CALLCODE", "External contract code execution (using contract's code)"},
            {"RETURN", "Stop execution and return data"},
            {"DELEGATECALL", "Delegate call to another contract"},
            {"CREATE2", "Create a new contract with deterministic address"},
            {"STATICCALL", "External contract call in static context"},
            {"REVERT", "Stop execution and revert state changes"},
            {"INVALID", "Invalid opcode"},
            {"SELFDESTRUCT", "Destroy contract and send balance to address"}
        };

        public static string GetOpcodeName(byte opcode)
        {
            if (OpcodeNames.TryGetValue(opcode, out var name))
            {
                return name;
            }
            return $"UNKNOWN ({opcode:X2})";
        }

        public static string MapToHumanReadableConcept(string opcodeName)
        {
            if (HighLevelOpcodeMap.TryGetValue(opcodeName, out var concept))
            {
                return concept;
            }
            return $"Custom/Unknown Operation ({opcodeName})";
        }

        public static string GetHighLevelConcept(byte opcode)
        {
            var name = GetOpcodeName(opcode);
            return MapToHumanReadableConcept(name);
        }
    }
}
