/*
 * Copyright 2024 [Your Company Name]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// =================================================================================
// AGENT METADATA
// This block is machine-readable and used for self-discovery and orchestration.
// =================================================================================

export const agent_metadata = {
  purpose: "Translates unstructured narrative text into structured data formats suitable for client-side visualization libraries like D3.js or Three.js. It balances creative interpretation with literal fidelity based on user-defined parameters.",
  dependencies: {
    core: ["core-sdk", "shared-auth", "event-bus"],
    external_apis: ["OpenAI", "Anthropic", "GoogleVertexAI"],
    libraries: ["express", "d3-force", "ajv"],
  },
  invalidation_conditions: [
    "Major breaking changes in integrated AI provider APIs (e.g., structured output format changes).",
    "Deprecation of target visualization formats (e.g., a new version of D3 requires a different JSON structure).",
    "Significant drift in LLM interpretation of core concepts without prompt updates.",
  ],
  adjacent_apps: [
    "APP_58_Narrative_ModelExplainabilityUI", // Can visualize the outputs of this service.
    "APP_37_Governance_AuditTrailEngine", // Consumes events generated by this service.
    "APP_01_Inference_CostRouter", // This service can be a client of the cost router to optimize LLM calls.
    "APP_14_Agents_MultiModelOrchestrator", // Could use this service as a tool for generating visual outputs.
  ],
};

// =================================================================================
// IMPORTS
// =================================================================================

import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import {
  config,
  logger,
  ServiceError,
  AuthMiddleware,
  EventBusClient,
  Ontology,
  getCorrelationId,
  AuditLogger,
} from '@ecosystem/core-sdk';

import { VisualizationEngine } from './engine/visualizationEngine';
import { VisualizationRequest, VisualizationResponse } from './types/api';
import { validateRequest } from './middleware/validation';
import { visualizationRequestSchema } from './schemas/visualizationRequestSchema';
import { getSystemAssumptions, getFailureModes, getUpdateTriggers } from './system/introspection';

// =================================================================================
// CONFIGURATION & INITIALIZATION
// =================================================================================

const SERVICE_NAME = config.get('service.name', 'APP_59_Narrative_MindseyeVisualizer');
const PORT = config.get('service.port', 8059);
const API_VERSION = 'v1';

const app = express();
const authMiddleware = new AuthMiddleware();
const eventBus = new EventBusClient({ serviceName: SERVICE_NAME });
const auditLogger = new AuditLogger({ serviceName: SERVICE_NAME, eventBus });
const visualizationEngine = new VisualizationEngine({ auditLogger });

// =================================================================================
// MIDDLEWARE
// =================================================================================

app.use(helmet());
app.use(cors(config.get('service.corsOptions', {})));
app.use(express.json({ limit: '5mb' }));

// Custom Morgan token for correlation ID
morgan.token('correlation-id', (req: Request) => getCorrelationId(req) || 'N/A');
app.use(morgan(':remote-addr - :remote-user [:date[clf]] ":method :url HTTP/:http-version" :status :res[content-length] ":referrer" ":user-agent" - :response-time ms [correlation-id: :correlation-id]', {
  stream: {
    write: (message) => logger.info(message.trim(), { service: SERVICE_NAME }),
  },
}));

// =================================================================================
// API ROUTES
// =================================================================================

const apiRouter = express.Router();

/**
 * @swagger
 * /api/v1/visualize:
 *   post:
 *     summary: Generate visualization data from a narrative
 *     description: Takes a narrative text and parameters to generate a structured JSON output for client-side rendering.
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/VisualizationRequest'
 *     responses:
 *       200:
 *         description: Successful generation of visualization data.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/VisualizationResponse'
 *       400:
 *         description: Invalid request body.
 *       422:
 *         description: Unprocessable entity, e.g., narrative is too complex or ambiguous.
 *       500:
 *         description: Internal server error.
 */
apiRouter.post(
  '/visualize',
  authMiddleware.verifyToken.bind(authMiddleware),
  authMiddleware.requirePermission('narrative:visualize').bind(authMiddleware),
  validateRequest(visualizationRequestSchema),
  async (req: Request, res: Response, next: NextFunction) => {
    const correlationId = getCorrelationId(req);
    try {
      const requestBody: VisualizationRequest = req.body;
      logger.info(`Processing visualization request`, { correlationId, narrativeLength: requestBody.narrative.length, format: requestBody.output_format });

      const result: VisualizationResponse = await visualizationEngine.generate(requestBody, {
        userId: (req as any).user.sub,
        organizationId: (req as any).user.org_id,
        correlationId,
      });

      await auditLogger.log({
        event: Ontology.Narrative.VisualizationGenerated.eventName,
        actor: { type: 'user', id: (req as any).user.sub },
        resource: { type: 'visualization', id: result.visualization_id },
        details: {
            ...result.metadata.cost,
            ...result.metadata.latency,
            interpretationFidelityTradeoff: requestBody.parameters.interpretation_fidelity_tradeoff,
            outputFormat: requestBody.output_format,
        },
        correlationId,
      });

      res.status(200).json(result);
    } catch (error) {
      next(error);
    }
  }
);

app.use(`/api/${API_VERSION}`, apiRouter);

// =================================================================================
// SELF-QUERYING AGENT ENDPOINTS
// =================================================================================

app.get('/introspect', (req: Request, res: Response) => {
  res.status(200).json({
    service_name: SERVICE_NAME,
    version: process.env.npm_package_version || '0.1.0',
    agent_metadata,
    api_endpoints: [
      { path: `/api/${API_VERSION}/visualize`, method: 'POST', description: 'Generates visualization data from narrative text.' }
    ],
    tension: "Interpretation vs. Fidelity: The system balances the AI's creative freedom to generate compelling abstract visualizations against the user's need for a literal, precise representation of the narrative. This is controlled via the 'interpretation_fidelity_tradeoff' parameter, which directly influences prompt complexity, model selection, and post-processing steps, creating a direct trade-off between cost/latency and representational accuracy."
  });
});

app.get('/assumptions', (req: Request, res: Response) => {
  res.status(200).json(getSystemAssumptions());
});

app.get('/failure-modes', (req: Request, res: Response) => {
  res.status(200).json(getFailureModes());
});

app.get('/update-triggers', (req: Request, res: Response) => {
  res.status(200).json(getUpdateTriggers());
});

// =================================================================================
// HEALTH CHECK & ERROR HANDLING
// =================================================================================

app.get('/health', (req: Request, res: Response) => {
  res.status(200).json({ status: 'ok', service: SERVICE_NAME, timestamp: new Date().toISOString() });
});

// Global error handler
app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  const correlationId = getCorrelationId(req);
  if (err instanceof ServiceError) {
    logger.warn(err.message, {
      correlationId,
      service: SERVICE_NAME,
      statusCode: err.statusCode,
      errorCode: err.errorCode,
      details: err.details,
    });
    res.status(err.statusCode).json({
      error: {
        code: err.errorCode,
        message: err.message,
        details: err.details,
        correlationId,
      },
    });
  } else {
    logger.error('Unhandled exception', {
      correlationId,
      service: SERVICE_NAME,
      error: err.message,
      stack: err.stack,
    });
    res.status(500).json({
      error: {
        code: 'INTERNAL_SERVER_ERROR',
        message: 'An unexpected error occurred.',
        correlationId,
      },
    });
  }
});

// =================================================================================
// SERVER STARTUP
// =================================================================================

const server = app.listen(PORT, async () => {
  try {
    await eventBus.connect();
    logger.info(`Successfully connected to event bus.`, { service: SERVICE_NAME });
    logger.info(`${SERVICE_NAME} listening on port ${PORT}`, { service: SERVICE_NAME });
    // Publish a startup event
    await eventBus.publish(Ontology.System.ServiceStarted.eventName, {
        serviceName: SERVICE_NAME,
        version: process.env.npm_package_version || '0.1.0',
        port: PORT,
        timestamp: new Date().toISOString(),
    });
  } catch (error) {
    logger.error('Failed to connect to event bus during startup.', { service: SERVICE_NAME, error });
    // Depending on policy, we might want to exit if the event bus is critical
    // process.exit(1);
  }
});

const gracefulShutdown = async (signal: string) => {
  logger.info(`Received ${signal}. Shutting down gracefully...`, { service: SERVICE_NAME });
  server.close(async () => {
    logger.info('HTTP server closed.', { service: SERVICE_NAME });
    try {
      await eventBus.publish(Ontology.System.ServiceStopped.eventName, {
          serviceName: SERVICE_NAME,
          reason: `Received ${signal}`,
          timestamp: new Date().toISOString(),
      });
      await eventBus.disconnect();
      logger.info('Event bus disconnected.', { service: SERVICE_NAME });
    } catch (error) {
      logger.error('Error during event bus disconnection.', { service: SERVICE_NAME, error });
    }
    process.exit(0);
  });
};

process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));

export default app;