/*
 * Copyright 2024 Autonomous Software Architect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ================================================================================
// Main Entry Point for APP_31_Data_SyntheticDataForge
//
// Orchestrates generative models (from Stability AI, Midjourney, etc.) to
// produce synthetic data. Includes quality control and domain adaptation
// features to ensure the data is useful for downstream tasks like model training
// or simulation.
// ================================================================================

import express, { Express, Request, Response, NextFunction } from 'express';
import helmet from 'helmet';
import cors from 'cors';
import { v4 as uuidv4 } from 'uuid';
import { z } from 'zod';

// --- Shared Ecosystem SDK Mocks/Imports ---
// In a real environment, this would be from a shared npm package '@ecosystem/core-sdk'
import {
    initializeLogger,
    Logger,
    AppConfig,
    loadConfig,
    authMiddleware,
    AuthRequest,
    EventBusClient,
    createEventBusClient,
    EcosystemEvent,
    ServiceDiscovery,
    BaseError,
    ErrorCodes,
} from '@ecosystem/core-sdk';

// ================================================================================
// AGENT METADATA (Machine-Readable)
// ================================================================================

/**
 * @agent_metadata
 * purpose: "Orchestrates multi-provider generative AI models to produce high-quality, domain-specific synthetic datasets. Manages the full lifecycle from job creation, generation, quality control, to delivery, balancing cost, quality, and speed."
 * dependencies: [
 *   "APP_01_Inference_CostRouter for optimal model selection.",
 *   "APP_05_Auth_IdentityService for user and service authentication.",
 *   "APP_11_Storage_VectorCache for storing and retrieving generated data embeddings.",
 *   "APP_25_Billing_UsageTracker for metering generation costs.",
 *   "APP_42_Evaluation_MetricStore for storing quality control results."
 * ]
 * invalidation_conditions: [
 *   "Major breaking changes in integrated generative model provider APIs (e.g., Stability AI, Midjourney, OpenAI DALL-E).",
 *   "Significant drift in the cost-performance characteristics of underlying models, requiring recalibration of the cost/quality optimizer.",
 *   "Deprecation of a core data format (e.g., a specific image or tabular data format)."
 * ]
 * adjacent_apps: [
 *   "APP_32_Data_DatasetManager: Consumes datasets generated by this service.",
 *   "APP_51_Finetuning_Orchestrator: Uses synthetic data from this service for model fine-tuning jobs.",
 *   "APP_63_Simulation_RedTeamEngine: Uses synthetic data to create adversarial test cases."
 * ]
 */
export const agentMetadata = {
  purpose: "Orchestrates multi-provider generative AI models to produce high-quality, domain-specific synthetic datasets. Manages the full lifecycle from job creation, generation, quality control, to delivery, balancing cost, quality, and speed.",
  dependencies: [
    "APP_01_Inference_CostRouter for optimal model selection.",
    "APP_05_Auth_IdentityService for user and service authentication.",
    "APP_11_Storage_VectorCache for storing and retrieving generated data embeddings.",
    "APP_25_Billing_UsageTracker for metering generation costs.",
    "APP_42_Evaluation_MetricStore for storing quality control results."
  ],
  invalidation_conditions: [
    "Major breaking changes in integrated generative model provider APIs (e.g., Stability AI, Midjourney, OpenAI DALL-E).",
    "Significant drift in the cost-performance characteristics of underlying models, requiring recalibration of the cost/quality optimizer.",
    "Deprecation of a core data format (e.g., a specific image or tabular data format)."
  ],
  adjacent_apps: [
    "APP_32_Data_DatasetManager: Consumes datasets generated by this service.",
    "APP_51_Finetuning_Orchestrator: Uses synthetic data from this service for model fine-tuning jobs.",
    "APP_63_Simulation_RedTeamEngine: Uses synthetic data to create adversarial test cases."
  ]
};


// ================================================================================
// TYPE DEFINITIONS AND SCHEMAS
// ================================================================================

// --- Data Types ---
type DataType = 'image' | 'text' | 'tabular' | 'audio';
type JobStatus = 'pending' | 'running' | 'completed' | 'failed' | 'partially_completed';
type GenerationPolicyMode = 'cost_optimized' | 'quality_optimized' | 'balanced' | 'latency_optimized';
type RejectionAction = 'regenerate' | 'flag' | 'discard';
type AdaptationStrategy = 'prompt_refinement' | 'style_transfer' | 'data_augmentation';

// --- Zod Schemas for Validation ---
const GenerationPolicySchema = z.object({
    mode: z.enum(['cost_optimized', 'quality_optimized', 'balanced', 'latency_optimized']),
    preferredProviders: z.array(z.string()).optional(),
    fallbackProviders: z.array(z.string()).optional(),
    maxCostPerUnit: z.number().positive().optional(),
    timeoutSeconds: z.number().int().positive().optional(),
});

const QualityMetricSchema = z.object({
    type: z.string(),
    minThreshold: z.number().optional(),
    maxThreshold: z.number().optional(),
    params: z.record(z.any()).optional(),
});

const QualityControlSchema = z.object({
    enabled: z.boolean(),
    metrics: z.array(QualityMetricSchema),
    rejectionAction: z.enum(['regenerate', 'flag', 'discard']),
    maxRegenerationAttempts: z.number().int().min(0).max(5).default(2),
});

const DomainAdaptationSchema = z.object({
    enabled: z.boolean(),
    targetDatasetId: z.string().optional(),
    adaptationStrategy: z.enum(['prompt_refinement', 'style_transfer', 'data_augmentation']),
});

const CreateJobSchema = z.object({
    name: z.string().min(3).max(100),
    description: z.string().max(500).optional(),
    dataType: z.enum(['image', 'text', 'tabular', 'audio']),
    schema: z.record(z.any()),
    quantity: z.number().int().positive().max(100000), // Safety limit
    generationConfig: z.object({
        promptTemplate: z.string(),
        promptInputs: z.array(z.record(z.any())),
        policy: GenerationPolicySchema,
    }),
    qualityControl: QualityControlSchema,
    domainAdaptation: DomainAdaptationSchema.optional(),
    tags: z.record(z.string()).optional(),
});

type CreateJobPayload = z.infer<typeof CreateJobSchema>;

// --- Core Application Interfaces ---
interface SyntheticDataJob {
    id: string;
    name: string;
    ownerId: string; // orgId or userId
    status: JobStatus;
    createdAt: Date;
    updatedAt: Date;
    config: CreateJobPayload;
    progress: {
        total: number;
        completed: number;
        failed: number;
        quality_rejected: number;
    };
    resultsLocation?: string; // e.g., S3 URI
    error?: string;
}

interface GeneratedDataItem {
    id: string;
    jobId: string;
    sourcePrompt: string;
    provider: string;
    model: string;
    data: any; // The actual generated content (e.g., image URL, text)
    metadata: Record<string, any>; // Cost, latency, seed, etc.
    qualityScore?: number;
    passedQc: boolean;
}

interface AppDependencies {
    logger: Logger;
    config: AppConfig;
    syntheticDataService: SyntheticDataService;
    jobRepository: JobRepository;
    eventBus: EventBusClient;
    agentMetadata: typeof agentMetadata;
}

// ================================================================================
// DATA PERSISTENCE LAYER (Repository)
// ================================================================================

/**
 * Manages the persistence of synthetic data generation jobs.
 * In a production environment, this would be backed by a robust database like
 * PostgreSQL or a NoSQL equivalent like DynamoDB. For this example, we use an
 * in-memory store to demonstrate the interface.
 */
class JobRepository {
    private jobs: Map<string, SyntheticDataJob> = new Map();
    private logger: Logger;

    constructor(dbConfig: any, logger: Logger) {
        this.logger = logger;
        this.logger.info(`Initializing JobRepository with config: ${JSON.stringify(dbConfig.type)}`);
        if (dbConfig.type !== 'in-memory') {
            this.logger.warn('In-memory repository is not suitable for production. Please configure a persistent database.');
        }
    }

    async create(job: SyntheticDataJob): Promise<SyntheticDataJob> {
        if (this.jobs.has(job.id)) {
            throw new BaseError(ErrorCodes.CONFLICT, `Job with ID ${job.id} already exists.`);
        }
        this.jobs.set(job.id, job);
        this.logger.info(`Created job ${job.id}`);
        return job;
    }

    async findById(id: string): Promise<SyntheticDataJob | null> {
        const job = this.jobs.get(id);
        return job ? { ...job } : null; // Return a copy
    }

    async findByOwner(ownerId: string): Promise<SyntheticDataJob[]> {
        return Array.from(this.jobs.values()).filter(job => job.ownerId === ownerId);
    }

    async update(id: string, updates: Partial<SyntheticDataJob>): Promise<SyntheticDataJob | null> {
        const job = this.jobs.get(id);
        if (!job) {
            return null;
        }
        const updatedJob = { ...job, ...updates, updatedAt: new Date() };
        this.jobs.set(id, updatedJob);
        this.logger.debug(`Updated job ${id}`);
        return updatedJob;
    }
}

// ================================================================================
// GENERATIVE PROVIDER ABSTRACTION (Adapters)
// ================================================================================

interface GenerationRequest {
    prompt: string;
    dataType: DataType;
    schema: Record<string, any>;
    jobId: string;
    policy: z.infer<typeof GenerationPolicySchema>;
}

interface GenerationResponse {
    provider: string;
    model: string;
    data: any;
    cost: number;
    latencyMs: number;
    metadata: Record<string, any>;
}

/**
 * Interface for a generative model provider adapter.
 * This allows for a plug-and-play architecture for different AI vendors.
 */
interface IGenerationProvider {
    readonly name: string;
    supports(dataType: DataType): boolean;
    generate(request: GenerationRequest): Promise<GenerationResponse>;
}

/**
 * Mock adapter for Stability AI's image generation API.
 */
class StabilityAiAdapter implements IGenerationProvider {
    readonly name = 'stability-ai';
    private logger: Logger;
    private apiKey: string;

    constructor(config: { apiKey: string }, logger: Logger) {
        this.apiKey = config.apiKey;
        this.logger = logger;
        if (!this.apiKey) {
            throw new Error('Stability AI API key is required.');
        }
    }

    supports(dataType: DataType): boolean {
        return dataType === 'image';
    }

    async generate(request: GenerationRequest): Promise<GenerationResponse> {
        const startTime = Date.now();
        this.logger.info(`[${this.name}] Generating image for job ${request.jobId}`);
        
        // Mock API call to Stability AI
        await new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 1000));

        const latencyMs = Date.now() - startTime;
        const cost = 0.008; // Example cost per image

        return {
            provider: this.name,
            model: 'stable-diffusion-xl-1.0',
            data: `https://fake-stability-cdn.com/${uuidv4()}.png`,
            cost,
            latencyMs,
            metadata: { seed: Math.floor(Math.random() * 1e9) },
        };
    }
}

/**
 * Mock adapter for a hypothetical Midjourney API.
 * Midjourney doesn't have a public API, so this demonstrates how one would be integrated.
 */
class MidjourneyAdapter implements IGenerationProvider {
    readonly name = 'midjourney';
    private logger: Logger;

    constructor(config: any, logger: Logger) {
        this.logger = logger;
    }

    supports(dataType: DataType): boolean {
        return dataType === 'image';
    }

    async generate(request: GenerationRequest): Promise<GenerationResponse> {
        const startTime = Date.now();
        this.logger.info(`[${this.name}] Generating image for job ${request.jobId}`);
        
        // Mock API call to a Midjourney wrapper/API
        await new Promise(resolve => setTimeout(resolve, 5000 + Math.random() * 3000));

        const latencyMs = Date.now() - startTime;
        const cost = 0.03; // Midjourney is typically higher quality and cost

        return {
            provider: this.name,
            model: 'midjourney-v6',
            data: `https://fake-midjourney-cdn.com/${uuidv4()}.png`,
            cost,
            latencyMs,
            metadata: { seed: Math.floor(Math.random() * 1e9), upscaled: true },
        };
    }
}

/**
 * Mock adapter for OpenAI's text generation (GPT-4).
 */
class OpenAiTextAdapter implements IGenerationProvider {
    readonly name = 'openai';
    private logger: Logger;

    constructor(config: { apiKey: string }, logger: Logger) {
        this.logger = logger;
    }

    supports(dataType: DataType): boolean {
        return dataType === 'text';
    }

    async generate(request: GenerationRequest): Promise<GenerationResponse> {
        const startTime = Date.now();
        this.logger.info(`[${this.name}] Generating text for job ${request.jobId}`);
        
        await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 500));

        const latencyMs = Date.now() - startTime;
        const outputText = `This is a synthetic text generated based on the prompt: "${request.prompt.substring(0, 50)}..."`;
        const cost = (outputText.length / 1000) * 0.03; // Example pricing

        return {
            provider: this.name,
            model: 'gpt-4-turbo',
            data: outputText,
            cost,
            latencyMs,
            metadata: { tokens: outputText.length },
        };
    }
}


// ================================================================================
// CORE BUSINESS LOGIC (Services)
// ================================================================================

/**
 * Service for performing quality control on generated data.
 */
class QualityControlService {
    private logger: Logger;
    // private metricStoreApp: ServiceDiscovery.Service;

    constructor(deps: { logger: Logger; /* metricStoreApp: ServiceDiscovery.Service */ }) {
        this.logger = deps.logger;
        // this.metricStoreApp = deps.metricStoreApp;
    }

    async evaluate(item: GeneratedDataItem, metrics: z.infer<typeof QualityMetricSchema>[]): Promise<{ passed: boolean; score: number; details: any }> {
        this.logger.debug(`Running QC for item ${item.id} from job ${item.jobId}`);
        let overallScore = 0;
        let passed = true;
        const details: any = {};

        for (const metric of metrics) {
            // In a real system, this would call out to specialized models or services.
            // For example, calling APP_42_Evaluation_MetricStore
            const { passed: metricPassed, score: metricScore } = this.runMockMetric(item, metric);
            details[metric.type] = { passed: metricPassed, score: metricScore };
            overallScore += metricScore;
            if (!metricPassed) {
                passed = false;
            }
        }

        const finalScore = overallScore / metrics.length;
        this.logger.info(`QC for item ${item.id}: ${passed ? 'PASSED' : 'FAILED'} with score ${finalScore.toFixed(2)}`);
        return { passed, score: finalScore, details };
    }

    private runMockMetric(item: GeneratedDataItem, metric: z.infer<typeof QualityMetricSchema>): { passed: boolean; score: number } {
        // Simulate metric evaluation
        const score = Math.random() * 10;
        let passed = true;
        if (metric.minThreshold && score < metric.minThreshold) passed = false;
        if (metric.maxThreshold && score > metric.maxThreshold) passed = false;
        return { passed, score };
    }
}

/**
 * Service for adapting generation prompts to a specific domain.
 */
class DomainAdaptationService {
    private logger: Logger;
    // private datasetManagerApp: ServiceDiscovery.Service;

    constructor(deps: { logger: Logger; /* datasetManagerApp: ServiceDiscovery.Service */ }) {
        this.logger = deps.logger;
        // this.datasetManagerApp = deps.datasetManagerApp;
    }

    async adaptPrompt(prompt: string, config: z.infer<typeof DomainAdaptationSchema>): Promise<string> {
        if (!config.enabled) {
            return prompt;
        }
        this.logger.debug(`Adapting prompt for strategy: ${config.adaptationStrategy}`);
        
        // In a real system, this would fetch data from APP_32_Data_DatasetManager
        // and use it to refine the prompt, e.g., by few-shot examples.
        switch (config.adaptationStrategy) {
            case 'prompt_refinement':
                return `${prompt}, in the style of a high-end e-commerce product photo, with clean lighting and a neutral background.`;
            case 'style_transfer':
                // This would involve more complex logic, maybe even another model call
                return `${prompt} --style <retrieved_style_id_from_${config.targetDatasetId}>`;
            default:
                return prompt;
        }
    }
}

/**
 * The main service orchestrating the entire synthetic data generation process.
 * This class embodies the core tension of the application: Cost vs. Quality.
 */
class SyntheticDataService {
    private logger: Logger;
    private config: AppConfig;
    private jobRepository: JobRepository;
    private qualityControlService: QualityControlService;
    private domainAdaptationService: DomainAdaptationService;
    private eventBus: EventBusClient;
    private providers: Map<string, IGenerationProvider> = new Map();
    // private costRouterApp: ServiceDiscovery.Service;
    // private usageTrackerApp: ServiceDiscovery.Service;

    constructor(deps: {
        logger: Logger;
        config: AppConfig;
        jobRepository: JobRepository;
        qualityControlService: QualityControlService;
        domainAdaptationService: DomainAdaptationService;
        eventBus: EventBusClient;
        // costRouterApp: ServiceDiscovery.Service;
        // usageTrackerApp: ServiceDiscovery.Service;
    }) {
        this.logger = deps.logger;
        this.config = deps.config;
        this.jobRepository = deps.jobRepository;
        this.qualityControlService = deps.qualityControlService;
        this.domainAdaptationService = deps.domainAdaptationService;
        this.eventBus = deps.eventBus;
        // this.costRouterApp = deps.costRouterApp;
        // this.usageTrackerApp = deps.usageTrackerApp;

        this.registerProviders();
    }

    private registerProviders() {
        // In a real system, this would be dynamic based on configuration
        const stabilityAdapter = new StabilityAiAdapter({ apiKey: this.config.providers.stability.apiKey }, this.logger);
        this.providers.set(stabilityAdapter.name, stabilityAdapter);

        const midjourneyAdapter = new MidjourneyAdapter({}, this.logger);
        this.providers.set(midjourneyAdapter.name, midjourneyAdapter);

        const openaiAdapter = new OpenAiTextAdapter({ apiKey: this.config.providers.openai.apiKey }, this.logger);
        this.providers.set(openaiAdapter.name, openaiAdapter);

        this.logger.info(`Registered providers: ${Array.from(this.providers.keys()).join(', ')}`);
    }

    async createJob(payload: CreateJobPayload, ownerId: string): Promise<SyntheticDataJob> {
        const job: SyntheticDataJob = {
            id: `job-${uuidv4()}`,
            name: payload.name,
            ownerId,
            status: 'pending',
            createdAt: new Date(),
            updatedAt: new Date(),
            config: payload,
            progress: {
                total: payload.quantity,
                completed: 0,
                failed: 0,
                quality_rejected: 0,
            },
        };

        const createdJob = await this.jobRepository.create(job);
        
        // Asynchronously start processing the job to avoid blocking the API response
        this.processJob(createdJob.id).catch(err => {
            this.logger.error(`Unhandled error in job processing for ${createdJob.id}:`, err);
        });

        await this.eventBus.publish('synthetic_data.job.created', {
            jobId: createdJob.id,
            ownerId,
            timestamp: new Date().toISOString(),
        });

        return createdJob;
    }

    /**
     * This is the core orchestration logic. It runs asynchronously.
     */
    private async processJob(jobId: string): Promise<void> {
        const job = await this.jobRepository.findById(jobId);
        if (!job || job.status !== 'pending') {
            this.logger.warn(`Job ${jobId} not found or not in pending state.`);
            return;
        }

        await this.jobRepository.update(jobId, { status: 'running' });
        this.logger.info(`Started processing job ${jobId}`);

        const { quantity, generationConfig, qualityControl, domainAdaptation } = job.config;
        const generatedItems: GeneratedDataItem[] = [];

        try {
            for (let i = 0; i < quantity; i++) {
                const promptInput = generationConfig.promptInputs[i % generationConfig.promptInputs.length];
                let sourcePrompt = this.hydratePrompt(generationConfig.promptTemplate, promptInput);

                if (domainAdaptation) {
                    sourcePrompt = await this.domainAdaptationService.adaptPrompt(sourcePrompt, domainAdaptation);
                }

                let item: GeneratedDataItem | null = null;
                let attempts = 0;
                const maxAttempts = qualityControl.enabled ? qualityControl.maxRegenerationAttempts + 1 : 1;

                while (!item && attempts < maxAttempts) {
                    attempts++;
                    const generationRequest: GenerationRequest = {
                        prompt: sourcePrompt,
                        dataType: job.config.dataType,
                        schema: job.config.schema,
                        jobId,
                        policy: generationConfig.policy,
                    };

                    const provider = await this.selectProvider(generationRequest);
                    const response = await provider.generate(generationRequest);

                    // Metering call to billing service
                    // await this.usageTrackerApp.post('/track', { ... });

                    let qcPassed = true;
                    let qcScore: number | undefined = undefined;

                    if (qualityControl.enabled) {
                        const tempItem: GeneratedDataItem = {
                            id: `item-${uuidv4()}`,
                            jobId,
                            sourcePrompt,
                            provider: response.provider,
                            model: response.model,
                            data: response.data,
                            metadata: response.metadata,
                            passedQc: false, // Will be updated
                        };
                        const qcResult = await this.qualityControlService.evaluate(tempItem, qualityControl.metrics);
                        qcPassed = qcResult.passed;
                        qcScore = qcResult.score;
                    }

                    if (qcPassed) {
                        item = {
                            id: `item-${uuidv4()}`,
                            jobId,
                            sourcePrompt,
                            provider: response.provider,
                            model: response.model,
                            data: response.data,
                            metadata: { ...response.metadata, cost: response.cost, latencyMs: response.latencyMs },
                            qualityScore: qcScore,
                            passedQc: true,
                        };
                        generatedItems.push(item);
                        job.progress.completed++;
                    } else {
                        job.progress.quality_rejected++;
                        this.logger.warn(`Item for job ${jobId} failed QC. Attempt ${attempts}/${maxAttempts}. Action: ${qualityControl.rejectionAction}`);
                        if (qualityControl.rejectionAction !== 'regenerate') {
                            break; // Stop trying for this item
                        }
                    }
                }

                if (!item) {
                    job.progress.failed++;
                }

                // Update progress periodically
                if (i % 10 === 0) {
                    await this.jobRepository.update(jobId, { progress: job.progress });
                }
            }

            // Finalize job
            const finalStatus: JobStatus = job.progress.failed > 0 ? 'partially_completed' : 'completed';
            await this.jobRepository.update(jobId, { status: finalStatus, progress: job.progress, resultsLocation: `s3://synthetic-data-forge/${jobId}` });
            this.logger.info(`Finished processing job ${jobId} with status: ${finalStatus}`);
            await this.eventBus.publish('synthetic_data.job.completed', { jobId, status: finalStatus });

        } catch (error: any) {
            this.logger.error(`Job ${jobId} failed with error:`, error);
            await this.jobRepository.update(jobId, { status: 'failed', error: error.message });
            await this.eventBus.publish('synthetic_data.job.failed', { jobId, error: error.message });
        }
    }

    /**
     * Selects a provider based on the job's policy. This is where the
     * Cost vs. Quality vs. Latency tension is resolved.
     */
    private async selectProvider(request: GenerationRequest): Promise<IGenerationProvider> {
        const { policy, dataType } = request;
        const availableProviders = Array.from(this.providers.values()).filter(p => p.supports(dataType));

        // In a real system, this would be a call to APP_01_Inference_CostRouter
        // which maintains real-time data on provider cost, latency, and quality scores.
        // For now, we use a simplified logic.
        
        switch (policy.mode) {
            case 'cost_optimized':
                // Mock logic: Stability is cheaper than Midjourney
                return this.providers.get('stability-ai')!;
            case 'quality_optimized':
                // Mock logic: Midjourney is higher quality
                return this.providers.get('midjourney')!;
            case 'latency_optimized':
                 // Mock logic: Stability is faster
                return this.providers.get('stability-ai')!;
            case 'balanced':
            default:
                // Simple balanced approach: alternate or random
                return Math.random() > 0.5 ? this.providers.get('stability-ai')! : this.providers.get('midjourney')!;
        }
    }

    private hydratePrompt(template: string, inputs: Record<string, any>): string {
        return template.replace(/\{(\w+)\}/g, (_, key) => inputs[key] || `{${key}}`);
    }
}

// ================================================================================
// API LAYER (Routes and Controllers)
// ================================================================================

/**
 * Registers all API routes for the application.
 * @param app The Express application instance.
 * @param deps The application dependencies.
 */
export function registerRoutes(app: Express, deps: AppDependencies) {
    const { syntheticDataService, jobRepository, logger, agentMetadata } = deps;

    // --- Job Management Endpoints ---
    app.post('/v1/jobs', async (req: AuthRequest, res: Response, next: NextFunction) => {
        try {
            const payload = CreateJobSchema.parse(req.body);
            const ownerId = req.auth?.orgId || req.auth?.userId;
            if (!ownerId) {
                return res.status(401).json({ error: 'Authentication required' });
            }
            const job = await syntheticDataService.createJob(payload, ownerId);
            res.status(202).json(job);
        } catch (error) {
            next(error);
        }
    });

    app.get('/v1/jobs/:jobId', async (req: AuthRequest, res: Response, next: NextFunction) => {
        try {
            const { jobId } = req.params;
            const job = await jobRepository.findById(jobId);
            if (!job) {
                return res.status(404).json({ error: 'Job not found' });
            }
            // Authorization check
            if (job.ownerId !== (req.auth?.orgId || req.auth?.userId)) {
                return res.status(403).json({ error: 'Forbidden' });
            }
            res.status(200).json(job);
        } catch (error) {
            next(error);
        }
    });

    app.get('/v1/jobs', async (req: AuthRequest, res: Response, next: NextFunction) => {
        try {
            const ownerId = req.auth?.orgId || req.auth?.userId;
            if (!ownerId) {
                return res.status(401).json({ error: 'Authentication required' });
            }
            const jobs = await jobRepository.findByOwner(ownerId);
            res.status(200).json(jobs);
        } catch (error) {
            next(error);
        }
    });

    // --- Self-Querying Agent Endpoints ---
    app.get('/introspect', (req: Request, res: Response) => {
        res.status(200).json({
            appName: 'APP_31_Data_SyntheticDataForge',
            description: 'Service for orchestrating multi-provider generative AI to create synthetic datasets.',
            version: '1.0.0',
            apiSurface: [
                { path: '/v1/jobs', method: 'POST', description: 'Create a new synthetic data generation job.' },
                { path: '/v1/jobs', method: 'GET', description: 'List all jobs for the authenticated principal.' },
                { path: '/v1/jobs/:jobId', method: 'GET', description: 'Get the status and details of a specific job.' },
            ],
            agentMetadata,
        });
    });

    app.get('/assumptions', (req: Request, res: Response) => {
        res.status(200).json({
            assumptions: [
                { id: 'A01', assumption: 'Provider APIs (Stability, OpenAI, etc.) are available and adhere to their documented contracts.', consequence: 'API unavailability or breaking changes will cause generation failures.' },
                { id: 'A02', assumption: 'The cost model for providers is relatively stable.', consequence: 'Sudden price hikes could lead to budget overruns for long-running jobs.' },
                { id: 'A03', assumption: 'The underlying shared SDK services (Auth, EventBus) are operational.', consequence: 'Failure of core services will lead to application-wide outages.' },
                { id: 'A04', assumption: 'Quality control metrics are a reasonable proxy for the utility of the synthetic data.', consequence: 'Poorly chosen metrics may lead to generation of data that passes QC but is useless for the target application.' },
                { id: 'A05', assumption: 'The `cost-router` service provides accurate, up-to-date recommendations.', consequence: 'Stale or inaccurate routing data will lead to suboptimal provider selection, violating job policies.' },
            ]
        });
    });

    app.get('/failure-modes', (req: Request, res: Response) => {
        res.status(200).json({
            failureModes: [
                { id: 'F01', mode: 'Provider API Rate Limiting', detection: 'Monitoring 429 HTTP responses from provider APIs.', mitigation: 'Implement exponential backoff, distribute requests across multiple API keys, route to alternative providers.' },
                { id: 'F02', mode: 'Cascading QC Rejections', detection: 'High `quality_rejected` count for a job.', mitigation: 'Automatic job pausing, alert user to review prompts and QC metrics, suggest using a higher-quality model.' },
                { id: 'F03', mode: 'Prompt Injection/Abuse', detection: 'Content moderation filters on prompts and generated outputs.', mitigation: 'Input validation, sanitization, and use of provider safety features.' },
                { id: 'F04', mode: 'Job Processing Deadlock', detection: 'Jobs stuck in "running" state for an excessive duration.', mitigation: 'Implement job timeouts, dead-letter queues for failed processing tasks, and automated recovery mechanisms.' },
                { id: 'F05', mode: 'Configuration Error', detection: 'Validation errors at job creation time (Zod).', mitigation: 'Provide clear error messages to the user; for runtime, have sensible defaults.' },
            ]
        });
    });

    app.get('/update-triggers', (req: Request, res: Response) => {
        res.status(200).json({
            updateTriggers: [
                { id: 'T01', trigger: 'New Generative AI Provider Emerges', action: 'Develop a new provider adapter and integrate it into the `selectProvider` logic.' },
                { id: 'T02', trigger: 'Provider Deprecates a Model Version', action: 'Update provider adapter to use the new model version, test for regressions in quality and performance.' },
                { id: 'T03', trigger: 'New Data Modality Support Required (e.g., Video)', action: 'Extend `DataType` enum, create new provider adapters for video, update job schema and processing logic.' },
                { id: 'T04', trigger: 'Change in Data Privacy Regulations (e.g., GDPR)', action: 'Update data handling logic, implement jurisdictional feature flags, enhance audit logging for compliance.' },
            ]
        });
    });

    logger.info('API routes registered.');
}

// ================================================================================
// MIDDLEWARE
// ================================================================================

function errorHandler(logger: Logger) {
    return (err: Error, req: Request, res: Response, next: NextFunction) => {
        logger.error(`[${(req as any).id}] Unhandled error: ${err.message}`, { stack: err.stack });

        if (err instanceof z.ZodError) {
            return res.status(400).json({ error: 'Invalid request payload', details: err.errors });
        }
        if (err instanceof BaseError) {
            return res.status(err.statusCode).json({ error: err.message, code: err.errorCode });
        }

        res.status(500).json({ error: 'Internal Server Error' });
    };
}

function auditLogger(deps: { eventBus: EventBusClient }) {
    return (req: AuthRequest, res: Response, next: NextFunction) => {
        const start = Date.now();
        res.on('finish', () => {
            const event: EcosystemEvent = {
                id: `evt-${uuidv4()}`,
                source: 'APP_31_Data_SyntheticDataForge',
                type: 'api.request.audited',
                timestamp: new Date().toISOString(),
                specversion: '1.0',
                data: {
                    requestId: (req as any).id,
                    method: req.method,
                    path: req.originalUrl,
                    statusCode: res.statusCode,
                    durationMs: Date.now() - start,
                    principal: req.auth,
                    ip: req.ip,
                },
            };
            deps.eventBus.publish(event.type, event.data).catch(err => console.error('Failed to publish audit event', err));
        });
        next();
    };
}

// ================================================================================
// APPLICATION BOOTSTRAP
// ================================================================================

class SyntheticDataForgeApp {
    public app: Express;
    private logger: Logger;
    private config: AppConfig;
    private dependencies!: AppDependencies;

    constructor() {
        // In a real app, loadConfig would read from files, env vars, etc.
        this.config = {
            server: { port: 3031, corsOptions: { origin: '*' } },
            logging: { level: 'info' },
            database: { type: 'in-memory' },
            providers: {
                stability: { apiKey: process.env.STABILITY_API_KEY || 'sk-dummy' },
                openai: { apiKey: process.env.OPENAI_API_KEY || 'sk-dummy' },
            },
        } as unknown as AppConfig; // Mocking AppConfig structure
        this.logger = initializeLogger(this.config.logging);
        this.app = express();
    }

    public async start(): Promise<void> {
        this.logger.info('--- Starting APP_31_Data_SyntheticDataForge ---');
        
        await this.initializeDependencies();
        this.setupMiddleware();
        this.setupRoutes();
        this.setupErrorHandling();

        const port = this.config.server.port || 3031;
        this.app.listen(port, () => {
            this.logger.info(`🚀 Server listening on port ${port}`);
            this.logger.info(`✅ Application startup complete.`);
        });
    }

    private async initializeDependencies(): Promise<void> {
        this.logger.info('Initializing application dependencies...');

        const eventBus = { publish: async (topic: string, payload: any) => { this.logger.debug(`EventBus: Publishing to ${topic}`, payload); } } as EventBusClient;
        const jobRepository = new JobRepository(this.config.database, this.logger);
        const qualityControlService = new QualityControlService({ logger: this.logger });
        const domainAdaptationService = new DomainAdaptationService({ logger: this.logger });
        const syntheticDataService = new SyntheticDataService({
            logger: this.logger,
            config: this.config,
            jobRepository,
            qualityControlService,
            domainAdaptationService,
            eventBus,
        });

        this.dependencies = {
            logger: this.logger,
            config: this.config,
            syntheticDataService,
            jobRepository,
            eventBus,
            agentMetadata,
        };
        this.logger.info('Dependencies initialized successfully.');
    }

    private setupMiddleware(): void {
        this.logger.info('Setting up middleware...');
        this.app.use(helmet());
        this.app.use(cors(this.config.server.corsOptions));
        this.app.use(express.json({ limit: '10mb' }));
        
        this.app.use((req: Request, res: Response, next: NextFunction) => {
            (req as any).id = uuidv4();
            this.logger.info(`[${(req as any).id}] --> ${req.method} ${req.originalUrl}`);
            next();
        });

        // Mock auth middleware for standalone running
        const mockAuth = (req: AuthRequest, res: Response, next: NextFunction) => {
            req.auth = { userId: 'user-123', orgId: 'org-abc', roles: ['user'] };
            next();
        };
        this.app.use(mockAuth);
        this.app.use(auditLogger({ eventBus: this.dependencies.eventBus }));
    }

    private setupRoutes(): void {
        this.logger.info('Setting up API routes...');
        registerRoutes(this.app, this.dependencies);
    }

    private setupErrorHandling(): void {
        this.app.use(errorHandler(this.logger));
    }
}

// Main execution block
if (require.main === module) {
    const server = new SyntheticDataForgeApp();
    server.start().catch(error => {
        const emergencyLogger = console;
        emergencyLogger.error('💥 CRITICAL: Failed to start application:', error);
        process.exit(1);
    });
}