import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

/**
 * @file AuditLogger.ts
 * @description Implements a tamper-evident, cryptographically chained audit logging system.
 * Designed for high-compliance environments (SOC2, HIPAA, GDPR) and AI-specific observability.
 * 
 * CORE FEATURES:
 * - SHA-256 Hash Chaining (Blockchain-lite) for tamper evidence.
 * - PII/PHI Redaction hooks.
 * - Explicit cost and latency tracking for unit economics.
 * - Jurisdictional tagging for sovereignty controls.
 * - Legal defensibility headers in every record.
 */

// -----------------------------------------------------------------------------
// Types & Interfaces
// -----------------------------------------------------------------------------

export type Jurisdiction = 'US' | 'EU' | 'APAC' | 'GLOBAL' | 'UNKNOWN';

export enum AuditSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
  FATAL = 'FATAL',
}

export enum AuditEventType {
  SYSTEM_BOOT = 'SYSTEM_BOOT',
  MODEL_INFERENCE = 'MODEL_INFERENCE',
  TOOL_EXECUTION = 'TOOL_EXECUTION',
  DATA_ACCESS = 'DATA_ACCESS',
  IDENTITY_AUTH = 'IDENTITY_AUTH',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  CONFIGURATION_CHANGE = 'CONFIGURATION_CHANGE',
  FINANCIAL_TRANSACTION = 'FINANCIAL_TRANSACTION',
  LEGAL_HOLD = 'LEGAL_HOLD',
}

export interface PrincipalIdentity {
  userId: string;
  orgId: string;
  role: string;
  ipAddress?: string;
  userAgent?: string;
  authMethod: 'API_KEY' | 'OAUTH' | 'JWT' | 'INTERNAL';
}

export interface AIModelMetadata {
  provider: string; // e.g., 'OpenAI', 'Anthropic'
  modelName: string; // e.g., 'gpt-4-turbo'
  modelVersion?: string;
  endpoint?: string;
}

export interface InferenceMetrics {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  latencyMs: number;
  timeToFirstTokenMs?: number;
  costUSD: number;
  finishReason?: string;
}

export interface ComplianceContext {
  jurisdiction: Jurisdiction;
  gdprSubjectId?: string;
  dataClassification: 'PUBLIC' | 'INTERNAL' | 'CONFIDENTIAL' | 'RESTRICTED';
  legalHoldActive: boolean;
}

export interface AuditPayload {
  [key: string]: any;
}

/**
 * The immutable record structure.
 */
export interface AuditLogEntry {
  id: string; // UUID v4
  timestamp: string; // ISO 8601
  sequenceNumber: number;
  
  // Event Classification
  eventType: AuditEventType;
  severity: AuditSeverity;
  
  // Context
  principal: PrincipalIdentity;
  compliance: ComplianceContext;
  
  // AI Specifics (Optional)
  modelMeta?: AIModelMetadata;
  metrics?: InferenceMetrics;
  
  // Data
  payload: AuditPayload; // Redacted/Sanitized
  promptHash?: string; // SHA-256 of the input prompt (never store raw prompt in audit if sensitive)
  completionHash?: string; // SHA-256 of the output
  
  // Integrity
  previousHash: string; // Pointer to previous entry
  hash: string; // SHA-256(id + timestamp + prevHash + payload + ...)
  
  // Legal Defensibility
  legalDisclaimer: string;
  systemVersion: string;
}

export interface AuditLoggerConfig {
  storagePath?: string; // Local file path for ledger (if file-based)
  transport?: (entry: AuditLogEntry) => Promise<void>; // External transport (S3, Splunk, etc.)
  encryptionKey?: string; // For encrypting sensitive payload fields
  environment: 'development' | 'staging' | 'production';
  strictMode: boolean; // If true, throws errors on logging failures
}

// -----------------------------------------------------------------------------
// Constants & Defaults
// -----------------------------------------------------------------------------

const LEGAL_DISCLAIMER_TEXT = 
  "Generated by AI System. No guarantee of accuracy. Not financial or legal advice. " +
  "Audit record is immutable. Subject to retention policies.";

const DEFAULT_JURISDICTION: Jurisdiction = 'US';

// -----------------------------------------------------------------------------
// Core Implementation
// -----------------------------------------------------------------------------

export class AuditLogger {
  private config: AuditLoggerConfig;
  private lastHash: string;
  private sequence: number;
  private ledgerStream: fs.WriteStream | null = null;
  private isInitialized: boolean = false;

  // Self-Querying Agent Metadata
  public readonly agent_metadata = {
    purpose: "Immutable ledger for system actions, ensuring traceability and compliance.",
    dependencies: ["fs", "crypto"],
    invalidation_conditions: ["Corrupted hash chain", "Write permission loss"],
    adjacent_apps: ["APP_37_Governance_AuditTrailEngine", "APP_01_Inference_CostRouter"]
  };

  constructor(config: AuditLoggerConfig) {
    this.config = config;
    this.lastHash = '0000000000000000000000000000000000000000000000000000000000000000'; // Genesis hash
    this.sequence = 0;
  }

  /**
   * Initialize the logger.
   * If using file storage, opens the stream and reads the last line to recover the hash chain.
   */
  public async initialize(): Promise<void> {
    if (this.isInitialized) return;

    if (this.config.storagePath) {
      // Ensure directory exists
      const dir = path.dirname(this.config.storagePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // Recover state from existing log
      if (fs.existsSync(this.config.storagePath)) {
        await this.recoverChainState();
      }

      this.ledgerStream = fs.createWriteStream(this.config.storagePath, { flags: 'a' });
    }

    this.isInitialized = true;
    
    // Log system boot
    await this.log({
      eventType: AuditEventType.SYSTEM_BOOT,
      severity: AuditSeverity.INFO,
      principal: {
        userId: 'system',
        orgId: 'system',
        role: 'daemon',
        authMethod: 'INTERNAL'
      },
      compliance: {
        jurisdiction: DEFAULT_JURISDICTION,
        dataClassification: 'INTERNAL',
        legalHoldActive: false
      },
      payload: {
        message: 'Audit Logger Initialized',
        config: {
          env: this.config.environment,
          strict: this.config.strictMode
        }
      }
    });
  }

  /**
   * Reads the last line of the file to recover the sequence number and hash.
   * This is a naive implementation; production systems might use a dedicated index or DB.
   */
  private async recoverChainState(): Promise<void> {
    return new Promise((resolve, reject) => {
      if (!this.config.storagePath) return resolve();

      // Read file backwards or just stream it. For simplicity, we assume reasonable size or log rotation.
      // In a real 1MB constraint, we'd use a robust 'read-last-lines' approach.
      const stream = fs.createReadStream(this.config.storagePath, { encoding: 'utf8' });
      let lastLine = '';
      
      stream.on('data', (chunk) => {
        const lines = chunk.toString().split('\n').filter(l => l.trim().length > 0);
        if (lines.length > 0) {
          lastLine = lines[lines.length - 1];
        }
      });

      stream.on('end', () => {
        if (lastLine) {
          try {
            const entry = JSON.parse(lastLine) as AuditLogEntry;
            this.lastHash = entry.hash;
            this.sequence = entry.sequenceNumber;
          } catch (e) {
            console.error('Failed to recover audit chain state. Log file may be corrupted.', e);
            // In strict mode, we might want to crash here.
          }
        }
        resolve();
      });

      stream.on('error', (err) => reject(err));
    });
  }

  /**
   * Core logging method.
   * Constructs the entry, calculates hash, writes to storage, and invokes transport.
   */
  public async log(params: {
    eventType: AuditEventType;
    severity: AuditSeverity;
    principal: PrincipalIdentity;
    compliance: ComplianceContext;
    payload: AuditPayload;
    modelMeta?: AIModelMetadata;
    metrics?: InferenceMetrics;
    promptText?: string; // Will be hashed, not stored raw unless specified in payload
    completionText?: string; // Will be hashed
  }): Promise<string> {
    if (!this.isInitialized) await this.initialize();

    this.sequence++;
    const timestamp = new Date().toISOString();
    const id = crypto.randomUUID();

    // Calculate content hashes for verification without storage
    const promptHash = params.promptText 
      ? crypto.createHash('sha256').update(params.promptText).digest('hex') 
      : undefined;
    
    const completionHash = params.completionText 
      ? crypto.createHash('sha256').update(params.completionText).digest('hex') 
      : undefined;

    // Sanitize Payload (PII Redaction Stub)
    const sanitizedPayload = this.redactPayload(params.payload);

    // Construct the entry object *before* hashing the entry itself
    const entryCandidate: Omit<AuditLogEntry, 'hash'> = {
      id,
      timestamp,
      sequenceNumber: this.sequence,
      eventType: params.eventType,
      severity: params.severity,
      principal: params.principal,
      compliance: params.compliance,
      modelMeta: params.modelMeta,
      metrics: params.metrics,
      payload: sanitizedPayload,
      promptHash,
      completionHash,
      previousHash: this.lastHash,
      legalDisclaimer: LEGAL_DISCLAIMER_TEXT,
      systemVersion: '1.0.0'
    };

    // Calculate Integrity Hash
    // Hash = SHA256( previousHash + JSON(fields) )
    const entryString = JSON.stringify(entryCandidate);
    const hash = crypto.createHash('sha256').update(entryString).digest('hex');

    const finalEntry: AuditLogEntry = {
      ...entryCandidate,
      hash
    };

    // Update state
    this.lastHash = hash;

    // Persist
    await this.writeToStorage(finalEntry);

    // External Transport
    if (this.config.transport) {
      try {
        await this.config.transport(finalEntry);
      } catch (e) {
        console.error('Audit transport failed:', e);
        if (this.config.strictMode) throw e;
      }
    }

    return id;
  }

  /**
   * Specialized logger for AI Model Inference.
   * Enforces capture of cost, tokens, and model identity.
   */
  public async logInference(
    principal: PrincipalIdentity,
    modelMeta: AIModelMetadata,
    metrics: InferenceMetrics,
    prompt: string,
    completion: string,
    metadata: Record<string, any> = {}
  ): Promise<string> {
    return this.log({
      eventType: AuditEventType.MODEL_INFERENCE,
      severity: AuditSeverity.INFO,
      principal,
      compliance: {
        jurisdiction: DEFAULT_JURISDICTION, // Should be derived from principal/config
        dataClassification: 'CONFIDENTIAL',
        legalHoldActive: false
      },
      modelMeta,
      metrics,
      promptText: prompt,
      completionText: completion,
      payload: {
        ...metadata,
        note: 'Inference execution'
      }
    });
  }

  /**
   * Specialized logger for Policy Violations (e.g., Jailbreak attempts).
   */
  public async logViolation(
    principal: PrincipalIdentity,
    violationType: string,
    details: any
  ): Promise<string> {
    return this.log({
      eventType: AuditEventType.POLICY_VIOLATION,
      severity: AuditSeverity.WARNING,
      principal,
      compliance: {
        jurisdiction: DEFAULT_JURISDICTION,
        dataClassification: 'RESTRICTED',
        legalHoldActive: true // Violations might trigger auto-hold
      },
      payload: {
        violationType,
        details
      }
    });
  }

  /**
   * Writes the entry to the local ledger stream.
   */
  private async writeToStorage(entry: AuditLogEntry): Promise<void> {
    if (!this.ledgerStream) return;

    const line = JSON.stringify(entry) + '\n';
    const canWrite = this.ledgerStream.write(line);

    if (!canWrite) {
      // Handle backpressure if necessary, though unlikely for audit logs
      await new Promise<void>(resolve => this.ledgerStream!.once('drain', resolve));
    }
  }

  /**
   * Redacts sensitive keys from the payload.
   * This is a basic implementation. In production, use a dedicated library or schema-based redaction.
   */
  private redactPayload(payload: any): any {
    if (!payload || typeof payload !== 'object') return payload;

    const sensitiveKeys = ['password', 'secret', 'api_key', 'ssn', 'credit_card', 'auth_token'];
    const redacted = { ...payload };

    for (const key of Object.keys(redacted)) {
      const lowerKey = key.toLowerCase();
      if (sensitiveKeys.some(sk => lowerKey.includes(sk))) {
        redacted[key] = '[REDACTED]';
      } else if (typeof redacted[key] === 'object') {
        redacted[key] = this.redactPayload(redacted[key]);
      }
    }

    return redacted;
  }

  /**
   * Verifies the integrity of a list of log entries.
   * Recomputes hashes and checks the chain.
   */
  public static verifyChain(entries: AuditLogEntry[]): { valid: boolean; brokenIndex: number } {
    if (entries.length === 0) return { valid: true, brokenIndex: -1 };

    // Sort by sequence
    const sorted = [...entries].sort((a, b) => a.sequenceNumber - b.sequenceNumber);

    for (let i = 0; i < sorted.length; i++) {
      const entry = sorted[i];
      
      // 1. Verify internal hash
      const { hash, ...content } = entry;
      const calculatedHash = crypto.createHash('sha256').update(JSON.stringify(content)).digest('hex');
      
      if (calculatedHash !== hash) {
        return { valid: false, brokenIndex: i };
      }

      // 2. Verify chain link (skip genesis/first loaded entry if we don't have context)
      if (i > 0) {
        const prev = sorted[i - 1];
        if (entry.previousHash !== prev.hash) {
          return { valid: false, brokenIndex: i };
        }
      }
    }

    return { valid: true, brokenIndex: -1 };
  }

  /**
   * Introspection for the Agentic Framework.
   */
  public introspect(): any {
    return {
      status: this.isInitialized ? 'active' : 'pending',
      sequence: this.sequence,
      lastHash: this.lastHash,
      storage: this.config.storagePath ? 'file' : 'memory-only',
      metadata: this.agent_metadata
    };
  }
}

// -----------------------------------------------------------------------------
// Singleton Export (Optional usage pattern)
// -----------------------------------------------------------------------------

let globalLogger: AuditLogger | null = null;

export const getAuditLogger = (config?: AuditLoggerConfig): AuditLogger => {
  if (!globalLogger) {
    if (!config) throw new Error("AuditLogger not initialized and no config provided.");
    globalLogger = new AuditLogger(config);
  }
  return globalLogger;
};