import { v4 as uuidv4 } from 'uuid';

/**
 * Represents the supported cloud providers for billing normalization.
 */
export type CloudProvider = 'AWS' | 'GCP' | 'Azure' | 'Other';

/**
 * Represents the possible statuses for an expected payment.
 */
export type PaymentStatus = 'pending' | 'paid' | 'overdue' | 'cancelled';

/**
 * Defines the structure of an Expected Payment record in the database.
 */
export interface ExpectedPayment {
  id: string;
  cloudProvider: CloudProvider;
  accountId: string; // The cloud account ID (e.g., AWS Account ID, GCP Project ID, Azure Subscription ID)
  service: string; // The cloud service associated with the payment (e.g., 'EC2', 'Compute Engine', 'Virtual Machines', 'S3', 'Storage')
  amount: number; // The expected amount of the payment
  currency: string; // The currency of the expected payment (e.g., 'USD', 'EUR')
  dueDate: Date; // The date by which the payment is expected
  status: PaymentStatus; // The current status of the payment
  description?: string; // An optional description for the payment
  createdAt: Date; // Timestamp when the record was created
  updatedAt: Date; // Timestamp when the record was last updated
}

/**
 * Type for creating a new Expected Payment record.
 * 'id', 'createdAt', 'updatedAt' are generated by the repository.
 * 'status' can be optionally provided, defaulting to 'pending'.
 */
export type CreateExpectedPaymentInput = Omit<ExpectedPayment, 'id' | 'createdAt' | 'updatedAt' | 'status'> & {
  status?: PaymentStatus;
};

/**
 * Type for updating an existing Expected Payment record.
 * 'id' and 'createdAt' cannot be updated.
 */
export type UpdateExpectedPaymentInput = Partial<Omit<ExpectedPayment, 'id' | 'createdAt'>>;

/**
 * Options for listing Expected Payment records, including filtering, pagination, and sorting.
 */
export interface ListExpectedPaymentsOptions {
  limit?: number; // Maximum number of records to return
  offset?: number; // Number of records to skip
  sortBy?: keyof ExpectedPayment; // Field to sort by
  sortOrder?: 'asc' | 'desc'; // Sort order
  cloudProvider?: CloudProvider; // Filter by cloud provider
  accountId?: string; // Filter by cloud account ID
  status?: PaymentStatus; // Filter by payment status
  dueDateBefore?: Date; // Filter payments due before this date
  dueDateAfter?: Date; // Filter payments due after this date
}

/**
 * Represents the result structure returned by a generic database query.
 * Assumes a common interface like that of 'pg' or 'mysql2' clients.
 */
export interface QueryResult<T> {
  rows: T[];
  rowCount: number; // Number of rows affected by a DML statement or returned by a SELECT statement
  // Other properties like command, oid, fields, etc., can be added if needed.
}

/**
 * Abstract interface for a database client, allowing for dependency injection
 * and easier testing. This assumes a SQL-like database with parameterized queries.
 */
export interface DatabaseClient {
  /**
   * Executes a SQL query with optional parameters.
   * @param sql The SQL query string.
   * @param params An array of parameters to be safely injected into the query.
   * @returns A Promise resolving to a QueryResult containing the fetched rows and row count.
   */
  query<T>(sql: string, params?: any[]): Promise<QueryResult<T>>;
}

/**
 * `ExpectedPaymentsRepository` provides a data access layer for performing
 * CRUD operations on `ExpectedPayment` records in the database.
 * It abstracts away the underlying database specifics, using a generic `DatabaseClient`.
 */
export class ExpectedPaymentsRepository {
  private readonly db: DatabaseClient;
  private readonly tableName: string = 'expected_payments'; // The name of the database table

  /**
   * Creates an instance of ExpectedPaymentsRepository.
   * @param dbClient The database client instance to use for operations.
   */
  constructor(dbClient: DatabaseClient) {
    this.db = dbClient;
  }

  /**
   * Creates a new expected payment record in the database.
   * @param paymentData The data for the new payment.
   * @returns A Promise resolving to the newly created ExpectedPayment record.
   * @throws Error if the database operation fails or no record is returned.
   */
  public async create(paymentData: CreateExpectedPaymentInput): Promise<ExpectedPayment> {
    const now = new Date();
    const newPayment: ExpectedPayment = {
      id: uuidv4(),
      ...paymentData,
      status: paymentData.status || 'pending', // Default status to 'pending'
      createdAt: now,
      updatedAt: now,
    };

    // Quote column names to handle camelCase in SQL (e.g., PostgreSQL)
    const columns = Object.keys(newPayment).map(col => `"${col}"`).join(', ');
    const values = Object.values(newPayment);
    const placeholders = values.map((_, i) => `$${i + 1}`).join(', ');

    const sql = `INSERT INTO ${this.tableName} (${columns}) VALUES (${placeholders}) RETURNING *;`;

    try {
      const result = await this.db.query<ExpectedPayment>(sql, values);
      if (result.rows.length === 0) {
        throw new Error('Failed to create expected payment: No record returned.');
      }
      return result.rows[0];
    } catch (error) {
      console.error(`Error creating expected payment: ${error}`);
      throw new Error(`Database error creating expected payment: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Finds an expected payment record by its unique ID.
   * @param id The ID of the payment to find.
   * @returns A Promise resolving to the ExpectedPayment record, or null if not found.
   * @throws Error if the database operation fails.
   */
  public async findById(id: string): Promise<ExpectedPayment | null> {
    const sql = `SELECT * FROM ${this.tableName} WHERE id = $1;`;
    try {
      const result = await this.db.query<ExpectedPayment>(sql, [id]);
      return result.rows.length > 0 ? result.rows[0] : null;
    } catch (error) {
      console.error(`Error finding expected payment by ID ${id}: ${error}`);
      throw new Error(`Database error finding expected payment: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Finds all expected payment records associated with a specific cloud account ID.
   * @param accountId The cloud account ID to filter by.
   * @returns A Promise resolving to an array of ExpectedPayment records.
   * @throws Error if the database operation fails.
   */
  public async findByAccountId(accountId: string): Promise<ExpectedPayment[]> {
    const sql = `SELECT * FROM ${this.tableName} WHERE "accountId" = $1 ORDER BY "dueDate" ASC;`;
    try {
      const result = await this.db.query<ExpectedPayment>(sql, [accountId]);
      return result.rows;
    } catch (error) {
      console.error(`Error finding expected payments by account ID ${accountId}: ${error}`);
      throw new Error(`Database error finding expected payments: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Finds all expected payment records for a specific cloud provider and account ID.
   * @param cloudProvider The cloud provider to filter by.
   * @param accountId The cloud account ID to filter by.
   * @returns A Promise resolving to an array of ExpectedPayment records.
   * @throws Error if the database operation fails.
   */
  public async findByProviderAndAccount(cloudProvider: CloudProvider, accountId: string): Promise<ExpectedPayment[]> {
    const sql = `SELECT * FROM ${this.tableName} WHERE "cloudProvider" = $1 AND "accountId" = $2 ORDER BY "dueDate" ASC;`;
    try {
      const result = await this.db.query<ExpectedPayment>(sql, [cloudProvider, accountId]);
      return result.rows;
    } catch (error) {
      console.error(`Error finding expected payments by provider ${cloudProvider} and account ${accountId}: ${error}`);
      throw new Error(`Database error finding expected payments: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Updates an existing expected payment record.
   * @param id The ID of the payment to update.
   * @param updates An object containing the fields to update.
   * @returns A Promise resolving to the updated ExpectedPayment record, or null if the record was not found.
   * @throws Error if the database operation fails.
   */
  public async update(id: string, updates: UpdateExpectedPaymentInput): Promise<ExpectedPayment | null> {
    if (Object.keys(updates).length === 0) {
      return this.findById(id); // No updates provided, return current record
    }

    const now = new Date();
    const updateFields = { ...updates, updatedAt: now };

    const setClauses: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const key in updateFields) {
      if (Object.prototype.hasOwnProperty.call(updateFields, key)) {
        setClauses.push(`"${key}" = $${paramIndex}`); // Quote column names
        values.push((updateFields as any)[key]);
        paramIndex++;
      }
    }

    values.push(id); // Add ID for the WHERE clause

    const sql = `UPDATE ${this.tableName} SET ${setClauses.join(', ')} WHERE id = $${paramIndex} RETURNING *;`;

    try {
      const result = await this.db.query<ExpectedPayment>(sql, values);
      return result.rows.length > 0 ? result.rows[0] : null;
    } catch (error) {
      console.error(`Error updating expected payment ID ${id}: ${error}`);
      throw new Error(`Database error updating expected payment: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Deletes an expected payment record by its ID.
   * @param id The ID of the payment to delete.
   * @returns A Promise resolving to true if the payment was deleted, false if not found.
   * @throws Error if the database operation fails.
   */
  public async delete(id: string): Promise<boolean> {
    const sql = `DELETE FROM ${this.tableName} WHERE id = $1 RETURNING id;`; // Return ID of deleted row
    try {
      const result = await this.db.query<{ id: string }>(sql, [id]);
      return result.rowCount > 0; // Check rowCount to confirm deletion
    } catch (error) {
      console.error(`Error deleting expected payment ID ${id}: ${error}`);
      throw new Error(`Database error deleting expected payment: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Lists expected payment records with optional filtering, pagination, and sorting.
   * @param options Filtering, pagination, and sorting options.
   * @returns A Promise resolving to an array of ExpectedPayment records.
   * @throws Error if the database operation fails.
   */
  public async list(options: ListExpectedPaymentsOptions = {}): Promise<ExpectedPayment[]> {
    const {
      limit = 100,
      offset = 0,
      sortBy = 'dueDate',
      sortOrder = 'asc',
      cloudProvider,
      accountId,
      status,
      dueDateBefore,
      dueDateAfter,
    } = options;

    let sql = `SELECT * FROM ${this.tableName}`;
    const conditions: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    if (cloudProvider) {
      conditions.push(`"cloudProvider" = $${paramIndex++}`);
      values.push(cloudProvider);
    }
    if (accountId) {
      conditions.push(`"accountId" = $${paramIndex++}`);
      values.push(accountId);
    }
    if (status) {
      conditions.push(`"status" = $${paramIndex++}`);
      values.push(status);
    }
    if (dueDateBefore) {
      conditions.push(`"dueDate" <= $${paramIndex++}`);
      values.push(dueDateBefore);
    }
    if (dueDateAfter) {
      conditions.push(`"dueDate" >= $${paramIndex++}`);
      values.push(dueDateAfter);
    }

    if (conditions.length > 0) {
      sql += ` WHERE ${conditions.join(' AND ')}`;
    }

    // Ensure sortBy is a valid column name and quoted
    const validSortByColumns: (keyof ExpectedPayment)[] = [
      'id', 'cloudProvider', 'accountId', 'service', 'amount', 'currency',
      'dueDate', 'status', 'description', 'createdAt', 'updatedAt'
    ];
    const finalSortBy = validSortByColumns.includes(sortBy) ? sortBy : 'dueDate';

    sql += ` ORDER BY "${finalSortBy}" ${sortOrder.toUpperCase()}`;
    sql += ` LIMIT $${paramIndex++}`;
    values.push(limit);
    sql += ` OFFSET $${paramIndex++}`;
    values.push(offset);
    sql += `;`;

    try {
      const result = await this.db.query<ExpectedPayment>(sql, values);
      return result.rows;
    } catch (error) {
      console.error(`Error listing expected payments: ${error}`);
      throw new Error(`Database error listing expected payments: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
}