/**
 * Represents a single normalized billing record from any cloud provider.
 */
export interface NormalizedBillingRecord {
  id: string; // Unique ID for the record (e.g., UUID)
  cloudProvider: 'AWS' | 'GCP' | 'Azure' | string; // Cloud provider name
  accountId: string; // Cloud provider account/project ID
  service: string; // e.g., 'EC2', 'Compute Engine', 'Virtual Machines'
  resourceId: string; // ID of the specific resource (e.g., instance ID, VM ID, disk ID)
  resourceName?: string; // Optional human-readable name or description of the resource
  usageType: string; // e.g., 'DataTransfer-Out', 'CPUUsage', 'Storage', 'Requests'
  cost: number; // Cost in the specified currency
  currency: string; // e.g., 'USD', 'EUR'
  usageStartDate: Date; // Start time of the usage period
  usageEndDate: Date; // End time of the usage period
  region: string; // e.g., 'us-east-1', 'us-central1', 'eastus'
  unit?: string; // Unit of measurement for the amount (e.g., 'Hours', 'GB', 'Requests')
  amount?: number; // Quantity of usage for the given unit
  tags?: { [key: string]: string }; // Key-value tags/labels applied to the resource
  invoiceId?: string; // Optional ID of the invoice this record belongs to
  billingPeriod?: string; // e.g., '2023-10' for monthly billing period
  createdAt: Date; // Timestamp when the record was created in the system
  updatedAt: Date; // Timestamp when the record was last updated in the system
}

/**
 * Defines criteria for querying normalized billing records.
 */
export interface BillingQueryCriteria {
  cloudProvider?: 'AWS' | 'GCP' | 'Azure' | string;
  accountId?: string;
  service?: string;
  resourceId?: string;
  region?: string;
  startDate?: Date; // Records where usageStartDate >= startDate
  endDate?: Date;   // Records where usageEndDate <= endDate
  minCost?: number;
  maxCost?: number;
  currency?: string;
  tags?: { [key: string]: string }; // Partial tag match: all specified tags must match
}

/**
 * Abstract interface for a generic database client.
 * This allows the repository to be database-agnostic.
 */
export interface IDatabaseClient<T extends { id: string }> {
  /**
   * Inserts one or more records into the database.
   * @param data The record(s) to insert.
   * @returns A promise that resolves to the inserted record(s).
   */
  insert(data: T | T[]): Promise<T[]>;

  /**
   * Finds a single record by its unique ID.
   * @param id The ID of the record to find.
   * @returns A promise that resolves to the found record or null if not found.
   */
  findById(id: string): Promise<T | null>;

  /**
   * Finds records based on simple equality criteria.
   * For complex queries (e.g., date ranges, min/max), the repository should handle filtering.
   * @param criteria A partial object representing the fields to match.
   * @returns A promise that resolves to an array of matching records.
   */
  find(criteria: Partial<T>): Promise<T[]>;

  /**
   * Updates an existing record by its ID.
   * @param id The ID of the record to update.
   * @param data The partial data to update.
   * @returns A promise that resolves to the updated record or null if not found.
   */
  update(id: string, data: Partial<T>): Promise<T | null>;

  /**
   * Deletes a record by its unique ID.
   * @param id The ID of the record to delete.
   * @returns A promise that resolves to true if deleted, false otherwise.
   */
  delete(id: string): Promise<boolean>;
}

/**
 * A concrete (mock) implementation of IDatabaseClient for in-memory storage.
 * Useful for testing or as a placeholder before integrating with a real database.
 */
class InMemoryDatabaseClient<T extends { id: string }> implements IDatabaseClient<T> {
  private store: Map<string, T> = new Map();

  async insert(data: T | T[]): Promise<T[]> {
    const records = Array.isArray(data) ? data : [data];
    records.forEach(record => {
      if (!record.id) {
        // In a real scenario, ID would be generated by DB or a UUID library
        record.id = `mock-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
      }
      this.store.set(record.id, { ...record }); // Store a shallow copy
    });
    return records.map(record => this.store.get(record.id)!);
  }

  async findById(id: string): Promise<T | null> {
    const record = this.store.get(id);
    return record ? { ...record } : null; // Return a shallow copy
  }

  async find(criteria: Partial<T>): Promise<T[]> {
    const results: T[] = [];
    for (const record of this.store.values()) {
      let match = true;
      for (const key in criteria) {
        if (criteria.hasOwnProperty(key)) {
          // Basic equality check for properties
          if (record[key as keyof T] !== (criteria as any)[key]) {
            match = false;
            break;
          }
        }
      }
      if (match) {
        results.push({ ...record }); // Return a shallow copy
      }
    }
    return results;
  }

  async update(id: string, data: Partial<T>): Promise<T | null> {
    const existing = this.store.get(id);
    if (!existing) {
      return null;
    }
    const updated = { ...existing, ...data, id, updatedAt: new Date() } as T; // Ensure ID is preserved and updatedAt is set
    this.store.set(id, updated);
    return { ...updated }; // Return a shallow copy
  }

  async delete(id: string): Promise<boolean> {
    return this.store.delete(id);
  }
}

/**
 * Data access layer for performing CRUD operations on normalized billing records.
 * It abstracts database-specific queries and provides a consistent interface.
 */
export class NormalizedBillingRepository {
  private dbClient: IDatabaseClient<NormalizedBillingRecord>;

  /**
   * Creates an instance of NormalizedBillingRepository.
   * @param dbClient The database client implementation to use (e.g., a real ORM client or an InMemoryDatabaseClient).
   */
  constructor(dbClient: IDatabaseClient<NormalizedBillingRecord>) {
    this.dbClient = dbClient;
  }

  /**
   * Inserts one or more normalized billing records into the database.
   * Automatically assigns a unique ID and sets `createdAt` and `updatedAt` timestamps.
   * @param records The record(s) to insert, excluding `id`, `createdAt`, and `updatedAt`.
   * @returns A promise that resolves to the inserted record(s) with their generated IDs and timestamps.
   */
  async create(
    records: Omit<NormalizedBillingRecord, 'id' | 'createdAt' | 'updatedAt'> | Omit<NormalizedBillingRecord, 'id' | 'createdAt' | 'updatedAt'>[]
  ): Promise<NormalizedBillingRecord[]> {
    const recordsToInsert = (Array.isArray(records) ? records : [records]).map(record => ({
      ...record,
      id: `nbl-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`, // Generate a unique ID (can be replaced by DB-generated UUID)
      createdAt: new Date(),
      updatedAt: new Date(),
    }));
    return this.dbClient.insert(recordsToInsert);
  }

  /**
   * Finds a normalized billing record by its unique ID.
   * @param id The ID of the record to find.
   * @returns A promise that resolves to the record if found, otherwise null.
   */
  async findById(id: string): Promise<NormalizedBillingRecord | null> {
    return this.dbClient.findById(id);
  }

  /**
   * Finds normalized billing records based on various criteria.
   * This method performs in-memory filtering for complex criteria if the underlying
   * `IDatabaseClient` only supports simple equality matches. For a real ORM,
   * this logic would be pushed down to the database query.
   * @param criteria The filtering criteria.
   * @returns A promise that resolves to an array of matching records.
   */
  async findByCriteria(criteria: BillingQueryCriteria): Promise<NormalizedBillingRecord[]> {
    // For a real database, this would translate `criteria` into a complex query.
    // For our generic IDatabaseClient and InMemoryDatabaseClient, we fetch all
    // and filter in memory for criteria beyond simple equality.
    const allRecords = await this.dbClient.find({}); // Fetch all records (or a subset based on simple criteria if supported)

    return allRecords.filter(record => {
      let match = true;

      if (criteria.cloudProvider && record.cloudProvider !== criteria.cloudProvider) match = false;
      if (match && criteria.accountId && record.accountId !== criteria.accountId) match = false;
      if (match && criteria.service && record.service !== criteria.service) match = false;
      if (match && criteria.resourceId && record.resourceId !== criteria.resourceId) match = false;
      if (match && criteria.region && record.region !== criteria.region) match = false;
      if (match && criteria.currency && record.currency !== criteria.currency) match = false;

      // Date range filtering
      if (match && criteria.startDate && record.usageStartDate < criteria.startDate) match = false;
      if (match && criteria.endDate && record.usageEndDate > criteria.endDate) match = false;

      // Cost range filtering
      if (match && criteria.minCost !== undefined && record.cost < criteria.minCost) match = false;
      if (match && criteria.maxCost !== undefined && record.cost > criteria.maxCost) match = false;

      // Tag matching: all specified criteria tags must be present in record tags with matching values
      if (match && criteria.tags) {
        for (const key in criteria.tags) {
          if (criteria.tags.hasOwnProperty(key)) {
            if (!record.tags || record.tags[key] !== criteria.tags[key]) {
              match = false;
              break;
            }
          }
        }
      }

      return match;
    });
  }

  /**
   * Updates an existing normalized billing record.
   * Automatically updates the `updatedAt` timestamp.
   * @param id The ID of the record to update.
   * @param updates The partial record data to apply. Fields like `id`, `createdAt` cannot be updated this way.
   * @returns A promise that resolves to the updated record if found, otherwise null.
   */
  async update(
    id: string,
    updates: Partial<Omit<NormalizedBillingRecord, 'id' | 'createdAt' | 'updatedAt'>>
  ): Promise<NormalizedBillingRecord | null> {
    return this.dbClient.update(id, updates);
  }

  /**
   * Deletes a normalized billing record by its unique ID.
   * @param id The ID of the record to delete.
   * @returns A promise that resolves to true if the record was successfully deleted, false otherwise.
   */
  async delete(id: string): Promise<boolean> {
    return this.dbClient.delete(id);
  }
}

// Export the InMemoryDatabaseClient for testing or local development purposes if needed
export { InMemoryDatabaseClient };