# Copyright 2024 Unchained Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import asyncio
import uuid
import time
import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional, Union, Callable
from contextlib import asynccontextmanager
from enum import Enum

import yaml
from fastapi import FastAPI, HTTPException, Depends, Request, BackgroundTasks
from pydantic import BaseModel, Field, SecretStr, HttpUrl
from aiohttp import ClientSession, ClientError

# --- Core SDK Imports ---
# These would be part of the shared 'core_sdk' package distributed to all apps.
# For this standalone file, we will use placeholder implementations.
from core_sdk.auth import APISecurity, get_current_principal
from core_sdk.events import EventBus, Event
from core_sdk.ontology.data import MarketDataTick, EnrichedMarketData, SentimentAnalysis, AnomalyDetectionResult
from core_sdk.logging import AuditableLogger, log_audit_event
from core_sdk.config import get_settings, BaseAppSettings
from core_sdk.observability import (
    instrument, 
    get_tracer, 
    setup_metrics, 
    api_request_counter, 
    processed_message_counter,
    processing_latency_histogram
)
from core_sdk.exceptions import CoreServiceError, ConfigurationError
from core_sdk.feature_flags import FeatureFlagClient, get_feature_flag_client

# --- Agent Metadata ---
AGENT_METADATA = """
agent_metadata:
  app_name: APP_11_Data_MarketFeedIngestor
  purpose: "To ingest, process, and enrich real-time market data feeds from various providers, balancing the tension between low-latency raw data delivery and high-value AI-driven enrichment."
  dependencies:
    - core_sdk: For auth, events, logging, and ontology.
    - External Market Data APIs (e.g., Polygon, Alpha Vantage, custom WebSockets).
    - AI Enrichment Provider APIs (e.g., OpenAI, Anthropic for sentiment; AWS Bedrock for anomaly detection).
    - Shared Event Bus (e.g., Kafka, NATS, Pulsar).
    - Shared Configuration Service.
  invalidation_conditions:
    - Significant changes to external data provider API schemas.
    - Deprecation of integrated AI model versions.
    - Changes in the core_sdk event bus protocol or data ontology.
    - Regulatory changes affecting the processing or storage of financial data.
  adjacent_apps:
    - APP_01_Inference_CostRouter: Could be used to select the most cost-effective enrichment model.
    - APP_14_Agents_MultiModelOrchestrator: Could consume enriched data to make trading decisions.
    - APP_37_Governance_AuditTrailEngine: Consumes audit logs generated by this service.
    - APP_52_Evaluation_TimeSeriesForecaster: Consumes raw or enriched data to build predictive models.
"""

# --- Configuration Management ---

class AppSettings(BaseAppSettings):
    """Defines the application's configuration settings."""
    app_name: str = "APP_11_Data_MarketFeedIngestor"
    allowed_origins: List[str] = Field(default=["*"], description="CORS allowed origins.")
    
    # Provider API Keys - loaded from environment
    polygon_api_key: Optional[SecretStr] = Field(None, env="POLYGON_API_KEY")
    openai_api_key: Optional[SecretStr] = Field(None, env="OPENAI_API_KEY")
    anthropic_api_key: Optional[SecretStr] = Field(None, env="ANTHROPIC_API_KEY")
    aws_bedrock_region: Optional[str] = Field(None, env="AWS_BEDROCK_REGION")
    aws_access_key_id: Optional[SecretStr] = Field(None, env="AWS_ACCESS_KEY_ID")
    aws_secret_access_key: Optional[SecretStr] = Field(None, env="AWS_SECRET_ACCESS_KEY")

    # Cost tracking parameters
    cost_per_openai_token_sentiment: float = 0.000002  # Example cost for gpt-3.5-turbo
    cost_per_anthropic_token_sentiment: float = 0.000008 # Example cost for Claude 3 Haiku
    cost_per_bedrock_invocation_anomaly: float = 0.001 # Example cost for a Bedrock model

settings = get_settings(AppSettings)
logger = AuditableLogger(service_name=settings.app_name)

# --- Core Service Logic ---

class ProcessingMode(str, Enum):
    LATENCY = "LATENCY"
    ENRICHMENT = "ENRICHMENT"

class DataSourceType(str, Enum):
    POLYGON_STOCKS = "POLYGON_STOCKS"
    MOCK_STREAM = "MOCK_STREAM"
    # Future: BINANCE_CRYPTO, ALPHA_VANTAGE_FOREX, etc.

class AIProvider(str, Enum):
    OPENAI = "OPENAI"
    ANTHROPIC = "ANTHROPIC"
    AWS_BEDROCK = "AWS_BEDROCK"

class SourceConfig(BaseModel):
    source_id: str = Field(default_factory=lambda: f"src_{uuid.uuid4().hex[:12]}")
    source_type: DataSourceType
    symbols: List[str]
    processing_mode: ProcessingMode = ProcessingMode.LATENCY
    enrichment_providers: List[AIProvider] = Field(default=[], description="AI providers to use in ENRICHMENT mode.")
    is_active: bool = True
    # Jurisdictional control feature flag
    jurisdiction: Optional[str] = Field(None, description="ISO 3166-1 alpha-2 country code for jurisdiction-specific rules.")

# In-memory store for active sources and tasks. In a production system, this would be a distributed store like Redis or a database.
ACTIVE_SOURCES: Dict[str, Dict[str, Any]] = {}

class CostTracker:
    """Tracks the operational costs of data ingestion and enrichment."""
    def __init__(self):
        self.total_cost = 0.0
        self.messages_processed = 0
        self.enrichment_costs = {}

    @instrument
    def record_ingestion(self, num_messages: int = 1):
        self.messages_processed += num_messages
        # A base cost could be added here for compute/network if desired

    @instrument
    def record_enrichment(self, provider: AIProvider, tokens: int = 0, invocations: int = 0):
        cost = 0.0
        if provider == AIProvider.OPENAI:
            cost = tokens * settings.cost_per_openai_token_sentiment
        elif provider == AIProvider.ANTHROPIC:
            cost = tokens * settings.cost_per_anthropic_token_sentiment
        elif provider == AIProvider.AWS_BEDROCK:
            cost = invocations * settings.cost_per_bedrock_invocation_anomaly
        
        self.total_cost += cost
        self.enrichment_costs[provider] = self.enrichment_costs.get(provider, 0.0) + cost
        logger.info(f"Cost recorded for {provider}: ${cost:.8f}. Total cost: ${self.total_cost:.8f}")

    def get_metrics(self) -> Dict[str, Any]:
        return {
            "total_cost_usd": self.total_cost,
            "total_messages_processed": self.messages_processed,
            "average_cost_per_message": self.total_cost / self.messages_processed if self.messages_processed > 0 else 0,
            "enrichment_cost_breakdown": self.enrichment_costs
        }

cost_tracker = CostTracker()

# --- AI Enrichment Adapters ---
# This demonstrates the adapter pattern for integrating multiple AI vendors.

class BaseEnrichmentAdapter:
    def __init__(self, provider: AIProvider, session: ClientSession):
        self.provider = provider
        self.session = session

    async def enrich(self, data: MarketDataTick) -> Dict[str, Any]:
        raise NotImplementedError

class OpenAISentimentAdapter(BaseEnrichmentAdapter):
    def __init__(self, session: ClientSession):
        super().__init__(AIProvider.OPENAI, session)
        if not settings.openai_api_key:
            raise ConfigurationError("OPENAI_API_KEY is not configured.")
        self.api_key = settings.openai_api_key.get_secret_value()
        self.endpoint = "https://api.openai.com/v1/chat/completions"

    @instrument
    async def enrich(self, data: MarketDataTick) -> Optional[SentimentAnalysis]:
        if not data.related_news:
            return None
        
        prompt = f"""Analyze the sentiment of the following news headline regarding the stock {data.symbol}. 
        Classify it as 'positive', 'negative', or 'neutral' and provide a confidence score from 0.0 to 1.0.
        Headline: "{data.related_news.title}"
        Respond ONLY with a JSON object in the format {{"sentiment": "...", "score": ...}}.
        """
        
        payload = {
            "model": "gpt-3.5-turbo",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.1,
            "response_format": {"type": "json_object"}
        }
        headers = {"Authorization": f"Bearer {self.api_key}"}

        try:
            async with self.session.post(self.endpoint, json=payload, headers=headers) as response:
                response.raise_for_status()
                result = await response.json()
                content = json.loads(result['choices'][0]['message']['content'])
                cost_tracker.record_enrichment(self.provider, tokens=result['usage']['total_tokens'])
                return SentimentAnalysis(
                    provider=self.provider.value,
                    sentiment=content.get('sentiment', 'unknown'),
                    score=content.get('score', 0.0)
                )
        except (ClientError, json.JSONDecodeError, KeyError) as e:
            logger.error(f"Error with OpenAI enrichment for {data.symbol}: {e}")
            return None

class BedrockAnomalyAdapter(BaseEnrichmentAdapter):
    # This is a simplified example. A real implementation would use boto3/aiobotocore
    # and likely a more complex model invocation for time-series anomaly detection.
    def __init__(self, session: ClientSession):
        super().__init__(AIProvider.AWS_BEDROCK, session)
        if not all([settings.aws_bedrock_region, settings.aws_access_key_id, settings.aws_secret_access_key]):
            raise ConfigurationError("AWS Bedrock credentials are not fully configured.")

    @instrument
    async def enrich(self, data: MarketDataTick) -> Optional[AnomalyDetectionResult]:
        # Mocking the call to a Bedrock model for anomaly detection
        # A real implementation would involve passing a window of recent data points.
        is_anomaly = (data.volume > 1_000_000 and abs(data.price - data.open_price) / data.open_price > 0.05)
        
        # Simulate cost and latency of a real call
        await asyncio.sleep(0.05) 
        cost_tracker.record_enrichment(self.provider, invocations=1)

        if is_anomaly:
            return AnomalyDetectionResult(
                provider=self.provider.value,
                is_anomaly=True,
                score=0.95,
                details=f"High volume ({data.volume}) and significant price move detected."
            )
        return AnomalyDetectionResult(provider=self.provider.value, is_anomaly=False, score=0.1)

# --- Ingestion Pipeline ---
# This class embodies the core tension: Latency vs. Enrichment.

class IngestionPipeline:
    def __init__(self, config: SourceConfig, event_bus: EventBus, http_session: ClientSession):
        self.config = config
        self.event_bus = event_bus
        self.http_session = http_session
        self.enrichers: List[BaseEnrichmentAdapter] = []
        self._setup_enrichers()

    def _setup_enrichers(self):
        if self.config.processing_mode == ProcessingMode.ENRICHMENT:
            for provider in self.config.enrichment_providers:
                if provider == AIProvider.OPENAI:
                    self.enrichers.append(OpenAISentimentAdapter(self.http_session))
                elif provider == AIProvider.AWS_BEDROCK:
                    self.enrichers.append(BedrockAnomalyAdapter(self.http_session))
                # Add other providers like Anthropic here
                else:
                    logger.warning(f"Enrichment provider '{provider}' not implemented.")

    @instrument
    async def process(self, raw_data: Dict[str, Any]):
        """Processes a single data point through the configured pipeline."""
        start_time = time.perf_counter()
        try:
            # 1. Standardization to Core Ontology
            tick = MarketDataTick.from_provider_format(self.config.source_type.value, raw_data)
            
            # 2. Routing based on the core architectural tension
            if self.config.processing_mode == ProcessingMode.LATENCY:
                await self._fast_path(tick)
            elif self.config.processing_mode == ProcessingMode.ENRICHMENT:
                await self._enrichment_path(tick)

            cost_tracker.record_ingestion()
            processed_message_counter.labels(
                source_type=self.config.source_type.value, 
                mode=self.config.processing_mode.value
            ).inc()

        except Exception as e:
            logger.error(f"Error processing message for source {self.config.source_id}: {e}", exc_info=True)
        finally:
            latency = time.perf_counter() - start_time
            processing_latency_histogram.labels(
                source_type=self.config.source_type.value,
                mode=self.config.processing_mode.value
            ).observe(latency)

    async def _fast_path(self, tick: MarketDataTick):
        """Low-latency path: standardize and publish immediately."""
        event = Event(
            event_id=f"evt_{uuid.uuid4().hex}",
            event_type="market.data.tick.raw",
            source_app=settings.app_name,
            data=tick.model_dump()
        )
        await self.event_bus.publish("raw_market_data", event)
        logger.debug(f"Fast path: Published raw tick for {tick.symbol}")

    async def _enrichment_path(self, tick: MarketDataTick):
        """High-enrichment path: apply AI models before publishing."""
        enriched_data = EnrichedMarketData(tick_data=tick)
        
        enrichment_tasks = [enricher.enrich(tick) for enricher in self.enrichers]
        results = await asyncio.gather(*enrichment_tasks)

        for result in results:
            if isinstance(result, SentimentAnalysis):
                enriched_data.sentiment = result
            elif isinstance(result, AnomalyDetectionResult):
                enriched_data.anomaly_detection = result
        
        event = Event(
            event_id=f"evt_{uuid.uuid4().hex}",
            event_type="market.data.tick.enriched",
            source_app=settings.app_name,
            data=enriched_data.model_dump()
        )
        await self.event_bus.publish("enriched_market_data", event)
        logger.debug(f"Enrichment path: Published enriched data for {tick.symbol}")


# --- Data Source Connectors ---
# Extensible connectors for different market data providers.

class BaseSourceConnector:
    def __init__(self, config: SourceConfig, pipeline: IngestionPipeline):
        self.config = config
        self.pipeline = pipeline
        self._task: Optional[asyncio.Task] = None

    async def start(self):
        if self._task is None or self._task.done():
            self._task = asyncio.create_task(self._run())
            logger.info(f"Started connector for source {self.config.source_id}")

    async def stop(self):
        if self._task and not self._task.done():
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            logger.info(f"Stopped connector for source {self.config.source_id}")
        self._task = None

    async def _run(self):
        raise NotImplementedError

    def is_running(self) -> bool:
        return self._task is not None and not self._task.done()

class MockStreamConnector(BaseSourceConnector):
    """A mock connector for testing and demonstration."""
    async def _run(self):
        import random
        base_prices = {symbol: random.uniform(100, 500) for symbol in self.config.symbols}
        news_headlines = [
            "Announces record profits for Q3",
            "Faces new regulatory scrutiny",
            "Launches innovative new product line",
            "CEO unexpectedly resigns",
            "Downgraded by major analyst firm"
        ]
        
        while True:
            try:
                for symbol in self.config.symbols:
                    price = base_prices[symbol] * (1 + random.uniform(-0.01, 0.01))
                    base_prices[symbol] = price
                    volume = random.randint(1000, 5000000)
                    
                    mock_tick = {
                        "ev": "T",
                        "sym": symbol,
                        "p": round(price, 2),
                        "s": random.randint(1, 100),
                        "t": int(time.time() * 1000),
                        "o": round(price * (1 + random.uniform(-0.005, 0.005)), 2),
                        "v": volume,
                        "news": {
                            "title": f"{symbol} {random.choice(news_headlines)}"
                        } if random.random() > 0.8 else None
                    }
                    await self.pipeline.process(mock_tick)
                await asyncio.sleep(1) # Simulate real-time feed
            except asyncio.CancelledError:
                logger.info(f"Mock stream for {self.config.source_id} cancelled.")
                break
            except Exception as e:
                logger.error(f"Error in mock stream for {self.config.source_id}: {e}", exc_info=True)
                await asyncio.sleep(5) # Backoff on error

# --- Source Management ---

class DataSourceManager:
    def __init__(self, event_bus: EventBus, http_session: ClientSession):
        self.event_bus = event_bus
        self.http_session = http_session
        self.feature_flags = get_feature_flag_client()

    async def add_source(self, config: SourceConfig) -> str:
        if config.source_id in ACTIVE_SOURCES:
            raise ValueError(f"Source with ID {config.source_id} already exists.")

        # Enterprise Upsell Path: Check feature flags for advanced features
        if config.processing_mode == ProcessingMode.ENRICHMENT and not self.feature_flags.is_enabled("advanced-enrichment"):
            raise PermissionError("AI Enrichment is an enterprise feature. Please upgrade your plan.")
        
        # Jurisdictional Control Example
        if config.jurisdiction and self.feature_flags.is_enabled(f"geo-block-{config.jurisdiction.lower()}"):
             raise PermissionError(f"Data ingestion from jurisdiction '{config.jurisdiction}' is restricted.")

        pipeline = IngestionPipeline(config, self.event_bus, self.http_session)
        
        connector: BaseSourceConnector
        if config.source_type == DataSourceType.MOCK_STREAM:
            connector = MockStreamConnector(config, pipeline)
        # Add other connectors like Polygon.io here
        # elif config.source_type == DataSourceType.POLYGON_STOCKS:
        #     connector = PolygonConnector(config, pipeline)
        else:
            raise NotImplementedError(f"Source type {config.source_type} not supported.")

        if config.is_active:
            await connector.start()

        ACTIVE_SOURCES[config.source_id] = {"config": config, "connector": connector}
        log_audit_event("source.added", {"source_id": config.source_id, "config": config.model_dump()})
        return config.source_id

    async def remove_source(self, source_id: str):
        if source_id not in ACTIVE_SOURCES:
            raise ValueError(f"Source with ID {source_id} not found.")
        
        source_info = ACTIVE_SOURCES.pop(source_id)
        await source_info["connector"].stop()
        log_audit_event("source.removed", {"source_id": source_id})

    def get_source_status(self, source_id: str) -> Dict[str, Any]:
        if source_id not in ACTIVE_SOURCES:
            raise ValueError(f"Source with ID {source_id} not found.")
        
        source_info = ACTIVE_SOURCES[source_id]
        return {
            "config": source_info["config"].model_dump(),
            "is_running": source_info["connector"].is_running()
        }

    def list_sources(self) -> List[Dict[str, Any]]:
        return [self.get_source_status(sid) for sid in ACTIVE_SOURCES.keys()]

    async def shutdown(self):
        logger.info("Shutting down all active source connectors...")
        tasks = [info["connector"].stop() for info in ACTIVE_SOURCES.values()]
        await asyncio.gather(*tasks)
        ACTIVE_SOURCES.clear()
        logger.info("All connectors stopped.")


# --- FastAPI Application Setup ---

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    logger.info("Starting APP_11_Data_MarketFeedIngestor...")
    
    # Setup shared resources
    app.state.http_session = ClientSession()
    app.state.event_bus = EventBus() # Connects to Kafka/NATS via core_sdk
    await app.state.event_bus.connect()
    
    app.state.source_manager = DataSourceManager(app.state.event_bus, app.state.http_session)
    
    setup_metrics(app, service_name=settings.app_name)
    logger.info("Service started successfully.")
    
    yield
    
    # Shutdown
    logger.info("Shutting down service...")
    await app.state.source_manager.shutdown()
    await app.state.event_bus.disconnect()
    await app.state.http_session.close()
    logger.info("Service shutdown complete.")

app = FastAPI(
    title="APP_11_Data_MarketFeedIngestor",
    description="Ingests and enriches real-time market data feeds.",
    version="1.0.0",
    lifespan=lifespan,
    dependencies=[Depends(APISecurity())] # Apply shared auth model
)

# --- API Endpoints ---

@app.post("/v1/sources", status_code=201, response_model=SourceConfig)
async def create_source(
    config: SourceConfig,
    request: Request,
    principal: Dict[str, Any] = Depends(get_current_principal)
):
    """
    Configure and activate a new market data source.
    - **Revenue Surface**: Charged per active source, per message, and/or per enrichment call.
    - **Enterprise Upsell**: Higher throughput, more source types, advanced AI enrichment models.
    """
    try:
        manager: DataSourceManager = request.app.state.source_manager
        await manager.add_source(config)
        return config
    except (ValueError, NotImplementedError) as e:
        raise HTTPException(status_code=400, detail=str(e))
    except PermissionError as e:
        raise HTTPException(status_code=403, detail=str(e))
    except Exception as e:
        logger.error(f"Failed to create source: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal server error while creating source.")

@app.get("/v1/sources", response_model=List[Dict[str, Any]])
async def list_all_sources(request: Request):
    """List all configured data sources and their status."""
    manager: DataSourceManager = request.app.state.source_manager
    return manager.list_sources()

@app.get("/v1/sources/{source_id}", response_model=Dict[str, Any])
async def get_source(source_id: str, request: Request):
    """Get the status and configuration of a specific data source."""
    try:
        manager: DataSourceManager = request.app.state.source_manager
        return manager.get_source_status(source_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

@app.delete("/v1/sources/{source_id}", status_code=204)
async def delete_source(source_id: str, request: Request):
    """Deactivate and remove a data source configuration."""
    try:
        manager: DataSourceManager = request.app.state.source_manager
        await manager.remove_source(source_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

# --- Self-Querying Agent Endpoints ---

@app.get("/system/introspect", tags=["Agent"])
def introspect():
    """Provides a high-level overview of the application's state and purpose."""
    return {
        "app_name": settings.app_name,
        "purpose": "Ingest, process, and enrich real-time market data feeds.",
        "active_sources_count": len(ACTIVE_SOURCES),
        "active_source_ids": list(ACTIVE_SOURCES.keys()),
        "cost_metrics": cost_tracker.get_metrics(),
        "architectural_tension": "Latency vs. Enrichment. The service explicitly routes data through a fast, raw path or a slower, more expensive AI-enriched path, forcing a deliberate trade-off."
    }

@app.get("/system/assumptions", tags=["Agent"])
def assumptions():
    """Lists the key assumptions the system operates under."""
    return {
        "data_format_stability": "Assumes that upstream provider data schemas are relatively stable. Schema changes require adapter updates.",
        "network_reliability": "Assumes reliable network connectivity to both data providers and AI enrichment services.",
        "cost_model_accuracy": "Assumes the configured costs per token/invocation are accurate for financial tracking.",
        "ontology_consistency": "Assumes the `core_sdk.ontology` provides a stable, canonical representation for market data across the ecosystem.",
        "statelessness": "The core processing logic is stateless. State (source configurations) is managed externally or in-memory for this implementation."
    }

@app.get("/system/failure-modes", tags=["Agent"])
def failure_modes():
    """Describes potential failure modes and their impact."""
    return {
        "data_provider_outage": {
            "description": "An external market data provider API is unavailable.",
            "impact": "Data flow for sources using that provider ceases. No data loss for other sources.",
            "mitigation": "Connectors have built-in retry and backoff logic. System health checks should alert on persistent failures."
        },
        "enrichment_api_failure": {
            "description": "An AI provider's API (e.g., OpenAI) is down or returning errors.",
            "impact": "Enrichment path fails for messages. Depending on configuration, messages may be dropped or routed to a dead-letter queue. Raw data path is unaffected.",
            "mitigation": "Circuit breakers, timeouts, and fallbacks to alternative providers (if configured via APP_01_Inference_CostRouter)."
        },
        "event_bus_unavailability": {
            "description": "The shared event bus (e.g., Kafka) is unreachable.",
            "impact": "System-wide data propagation failure. Processed data cannot be delivered to downstream consumers.",
            "mitigation": "The `core_sdk.EventBus` should implement a resilient publisher with retries and a local buffer/dead-letter queue."
        },
        "poison_pill_message": {
            "description": "A malformed message from a provider causes the processing pipeline to crash.",
            "impact": "The specific connector task may enter a crash loop, affecting one source.",
            "mitigation": "Robust validation and error handling (try/except blocks) around data parsing and processing steps."
        }
    }

@app.get("/system/update-triggers", tags=["Agent"])
def update_triggers():
    """Defines conditions that should trigger a review or update of this application."""
    return {
        "code_updates": [
            "Release of a new major version of the `core_sdk`.",
            "Deprecation of an API from an integrated data or AI provider.",
            "Addition of a new, required enrichment type to the `EnrichedMarketData` ontology."
        ],
        "operational_events": [
            "Sustained increase in processing latency above SLOs.",
            "Significant deviation of actual enrichment costs from projected costs.",
            "High rate of parsing or validation errors from a specific data source, indicating a schema change."
        ]
    }

@app.get("/system/agent_metadata", tags=["Agent"], response_model=Dict[str, Any])
def get_agent_metadata():
    """Returns the machine-readable agent metadata block."""
    return yaml.safe_load(AGENT_METADATA)


if __name__ == "__main__":
    import uvicorn
    # This allows running the app directly for development.
    # In production, a process manager like Gunicorn or Uvicorn's workers would be used.
    uvicorn.run(app, host="0.0.0.0", port=8011)