/*
 * APP_09_Agents_HumanInLoopInterface
 * 
 * Copyright (c) 2024 Ecosystem Architect. All rights reserved.
 * 
 * LICENSE: PROPRIETARY / ENTERPRISE LICENSE REQUIRED
 * This software is part of the Unified AI Ecosystem. Unauthorized copying,
 * distribution, or modification is strictly prohibited.
 * 
 * DISCLAIMER:
 * This software provides decision support and workflow orchestration.
 * It does not guarantee safety in high-stakes environments.
 * Human review is the ultimate fail-safe. The authors assume no liability
 * for financial loss, data corruption, or systemic failures resulting
 * from automated or human-approved actions.
 * 
 * SYSTEM: Production-Grade Human-in-the-Loop (HITL) Orchestrator
 * DOMAIN: Governance & Safety
 */

import 'reflect-metadata';
import * as crypto from 'crypto';
import * as os from 'os';
import { EventEmitter } from 'events';

// -----------------------------------------------------------------------------
// SHARED ECOSYSTEM PRIMITIVES (Simulated Imports)
// -----------------------------------------------------------------------------

/**
 * Represents the unified identity model across the ecosystem.
 */
interface IdentityContext {
    userId: string;
    orgId: string;
    roles: string[];
    permissions: string[];
    auditTraceId: string;
}

/**
 * Standardized event bus message format.
 */
interface EcosystemEvent<T = any> {
    id: string;
    timestamp: string;
    source: string;
    type: string;
    payload: T;
    correlationId: string;
    schemaVersion: string;
}

/**
 * Common configuration interface.
 */
interface AppConfig {
    port: number;
    env: 'development' | 'staging' | 'production';
    logLevel: 'debug' | 'info' | 'warn' | 'error';
    riskThreshold: number; // 0.0 to 1.0
    autoApproveConfidence: number; // 0.0 to 1.0
    integrations: {
        openai: { apiKey: string; model: string };
        anthropic: { apiKey: string; model: string };
        slack: { webhookUrl: string };
    };
}

// -----------------------------------------------------------------------------
// CONFIGURATION & ENVIRONMENT
// -----------------------------------------------------------------------------

const CONFIG: AppConfig = {
    port: parseInt(process.env.PORT || '3009', 10),
    env: (process.env.NODE_ENV as any) || 'development',
    logLevel: 'info',
    riskThreshold: parseFloat(process.env.RISK_THRESHOLD || '0.75'),
    autoApproveConfidence: parseFloat(process.env.AUTO_APPROVE_CONFIDENCE || '0.95'),
    integrations: {
        openai: { apiKey: process.env.OPENAI_API_KEY || '', model: 'gpt-4-turbo' },
        anthropic: { apiKey: process.env.ANTHROPIC_API_KEY || '', model: 'claude-3-opus' },
        slack: { webhookUrl: process.env.SLACK_WEBHOOK_URL || '' }
    }
};

// -----------------------------------------------------------------------------
// DOMAIN MODELS
// -----------------------------------------------------------------------------

enum WorkflowStatus {
    PENDING = 'PENDING',
    RUNNING = 'RUNNING',
    PAUSED_FOR_REVIEW = 'PAUSED_FOR_REVIEW',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED'
}

enum RiskLevel {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
    CRITICAL = 'CRITICAL'
}

interface WorkflowStep {
    id: string;
    actionType: string;
    payload: Record<string, any>;
    aiConfidenceScore: number; // 0.0 - 1.0 provided by the agent
    riskScore?: number; // Calculated by this system
    riskLevel?: RiskLevel;
    status: 'PENDING' | 'EXECUTED' | 'SKIPPED';
}

interface WorkflowContext {
    workflowId: string;
    agentId: string;
    initiatedBy: IdentityContext;
    steps: WorkflowStep[];
    currentStepIndex: number;
    status: WorkflowStatus;
    metadata: Record<string, any>;
    createdAt: Date;
    updatedAt: Date;
}

interface ReviewRequest {
    id: string;
    workflowId: string;
    stepId: string;
    reason: string;
    aiSummary: string; // Generated by Anthropic
    riskAnalysis: string; // Generated by OpenAI
    requiredRole: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'MODIFIED';
    reviewerId?: string;
    reviewerComments?: string;
    modificationPayload?: Record<string, any>;
    createdAt: Date;
    expiresAt: Date;
}

// -----------------------------------------------------------------------------
// CORE SERVICES
// -----------------------------------------------------------------------------

/**
 * Logger with structured output and audit capabilities.
 */
class Logger {
    static log(level: string, message: string, meta: any = {}) {
        console.log(JSON.stringify({
            timestamp: new Date().toISOString(),
            level,
            message,
            ...meta,
            service: 'APP_09_HITL'
        }));
    }

    static audit(action: string, actor: IdentityContext, details: any) {
        this.log('AUDIT', `Action: ${action}`, {
            actorId: actor.userId,
            orgId: actor.orgId,
            traceId: actor.auditTraceId,
            details
        });
    }
}

/**
 * Abstracted AI Vendor Client.
 * In a real implementation, this would use the official SDKs.
 */
class AIGateway {
    async analyzeRisk(payload: any): Promise<{ score: number; reasoning: string }> {
        // MOCK: Integration with OpenAI for risk scoring
        // In production: Call OpenAI API with a prompt designed to detect dangerous actions
        // (e.g., PII leakage, financial transactions, system deletion).
        
        const payloadStr = JSON.stringify(payload);
        const isHighRisk = payloadStr.includes('DELETE') || payloadStr.includes('transfer') || payloadStr.includes('sudo');
        
        // Simulating latency
        await new Promise(resolve => setTimeout(resolve, 150));

        if (isHighRisk) {
            return { score: 0.85, reasoning: 'Detected high-stakes keywords (DELETE/transfer).' };
        }
        return { score: 0.1, reasoning: 'Routine operation detected.' };
    }

    async summarizeContext(workflow: WorkflowContext): Promise<string> {
        // MOCK: Integration with Anthropic for context summarization
        // In production: Send workflow history to Claude for a human-readable summary.
        return `Workflow ${workflow.workflowId} initiated by ${workflow.initiatedBy.userId}. Step ${workflow.currentStepIndex + 1} involves action '${workflow.steps[workflow.currentStepIndex].actionType}'.`;
    }
}

/**
 * Manages the lifecycle of workflows and state transitions.
 */
class WorkflowEngine {
    private workflows: Map<string, WorkflowContext> = new Map();
    private eventBus: EventEmitter;
    private aiGateway: AIGateway;
    private reviewManager: ReviewManager;

    constructor(eventBus: EventEmitter, reviewManager: ReviewManager) {
        this.eventBus = eventBus;
        this.aiGateway = new AIGateway();
        this.reviewManager = reviewManager;
    }

    public async createWorkflow(agentId: string, identity: IdentityContext, steps: WorkflowStep[]): Promise<WorkflowContext> {
        const id = crypto.randomUUID();
        const workflow: WorkflowContext = {
            workflowId: id,
            agentId,
            initiatedBy: identity,
            steps,
            currentStepIndex: 0,
            status: WorkflowStatus.PENDING,
            metadata: {},
            createdAt: new Date(),
            updatedAt: new Date()
        };

        this.workflows.set(id, workflow);
        Logger.audit('WORKFLOW_CREATED', identity, { workflowId: id, stepCount: steps.length });
        
        // Start execution asynchronously
        this.executeStep(id);
        
        return workflow;
    }

    public getWorkflow(id: string): WorkflowContext | undefined {
        return this.workflows.get(id);
    }

    private async executeStep(workflowId: string) {
        const workflow = this.workflows.get(workflowId);
        if (!workflow) return;

        if (workflow.currentStepIndex >= workflow.steps.length) {
            workflow.status = WorkflowStatus.COMPLETED;
            workflow.updatedAt = new Date();
            Logger.log('info', `Workflow ${workflowId} completed successfully.`);
            return;
        }

        const currentStep = workflow.steps[workflow.currentStepIndex];
        workflow.status = WorkflowStatus.RUNNING;

        // 1. Evaluate Risk
        const riskAnalysis = await this.aiGateway.analyzeRisk(currentStep.payload);
        currentStep.riskScore = riskAnalysis.score;
        currentStep.riskLevel = this.mapScoreToLevel(riskAnalysis.score);

        Logger.log('info', `Step Analysis: ID=${currentStep.id} Risk=${currentStep.riskScore} Conf=${currentStep.aiConfidenceScore}`);

        // 2. Determine if Review is Needed
        const needsReview = this.shouldPauseForReview(currentStep);

        if (needsReview) {
            workflow.status = WorkflowStatus.PAUSED_FOR_REVIEW;
            workflow.updatedAt = new Date();
            
            const summary = await this.aiGateway.summarizeContext(workflow);
            
            await this.reviewManager.createReviewRequest({
                workflowId,
                stepId: currentStep.id,
                reason: `Risk Score (${currentStep.riskScore}) exceeded threshold or Confidence (${currentStep.aiConfidenceScore}) was too low.`,
                aiSummary: summary,
                riskAnalysis: riskAnalysis.reasoning,
                requiredRole: currentStep.riskLevel === RiskLevel.CRITICAL ? 'admin' : 'operator',
                payload: currentStep.payload
            });

            Logger.log('warn', `Workflow ${workflowId} paused for human review.`);
        } else {
            // Auto-approve and proceed
            currentStep.status = 'EXECUTED';
            workflow.currentStepIndex++;
            workflow.updatedAt = new Date();
            // Recursively execute next step
            setImmediate(() => this.executeStep(workflowId));
        }
    }

    public async resumeWorkflow(workflowId: string, approved: boolean, modification?: Record<string, any>) {
        const workflow = this.workflows.get(workflowId);
        if (!workflow) throw new Error('Workflow not found');

        if (workflow.status !== WorkflowStatus.PAUSED_FOR_REVIEW) {
            throw new Error('Workflow is not paused for review');
        }

        const currentStep = workflow.steps[workflow.currentStepIndex];

        if (approved) {
            if (modification) {
                Logger.log('info', `Applying human modification to step ${currentStep.id}`);
                currentStep.payload = modification;
            }
            workflow.status = WorkflowStatus.APPROVED; // Transient state
            currentStep.status = 'EXECUTED';
            workflow.currentStepIndex++;
            workflow.updatedAt = new Date();
            setImmediate(() => this.executeStep(workflowId));
        } else {
            workflow.status = WorkflowStatus.REJECTED;
            workflow.updatedAt = new Date();
            Logger.log('warn', `Workflow ${workflowId} rejected by human reviewer.`);
        }
    }

    private shouldPauseForReview(step: WorkflowStep): boolean {
        // Rule 1: Low Confidence
        if (step.aiConfidenceScore < CONFIG.autoApproveConfidence) return true;

        // Rule 2: High Risk
        if ((step.riskScore || 0) > CONFIG.riskThreshold) return true;

        // Rule 3: Explicit High Stakes Actions (Hardcoded Safety)
        const action = step.actionType.toUpperCase();
        const restrictedActions = ['DELETE_DB', 'TRANSFER_FUNDS', 'PUBLISH_KEY', 'GRANT_ADMIN'];
        if (restrictedActions.includes(action)) return true;

        return false;
    }

    private mapScoreToLevel(score: number): RiskLevel {
        if (score > 0.9) return RiskLevel.CRITICAL;
        if (score > 0.7) return RiskLevel.HIGH;
        if (score > 0.4) return RiskLevel.MEDIUM;
        return RiskLevel.LOW;
    }
}

/**
 * Manages the queue of pending human reviews.
 */
class ReviewManager {
    private reviews: Map<string, ReviewRequest> = new Map();
    private eventBus: EventEmitter;

    constructor(eventBus: EventEmitter) {
        this.eventBus = eventBus;
    }

    public async createReviewRequest(params: {
        workflowId: string;
        stepId: string;
        reason: string;
        aiSummary: string;
        riskAnalysis: string;
        requiredRole: string;
        payload: any;
    }): Promise<ReviewRequest> {
        const id = crypto.randomUUID();
        const request: ReviewRequest = {
            id,
            workflowId: params.workflowId,
            stepId: params.stepId,
            reason: params.reason,
            aiSummary: params.aiSummary,
            riskAnalysis: params.riskAnalysis,
            requiredRole: params.requiredRole,
            status: 'PENDING',
            createdAt: new Date(),
            expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) // 24h expiry
        };

        this.reviews.set(id, request);
        
        // Emit event for external notification systems (e.g., Slack bot)
        this.eventBus.emit('review:created', request);
        
        return request;
    }

    public getPendingReviews(role?: string): ReviewRequest[] {
        return Array.from(this.reviews.values())
            .filter(r => r.status === 'PENDING')
            .filter(r => !role || r.requiredRole === role);
    }

    public getReview(id: string): ReviewRequest | undefined {
        return this.reviews.get(id);
    }

    public async submitDecision(
        reviewId: string, 
        reviewer: IdentityContext, 
        decision: 'APPROVE' | 'REJECT', 
        comments?: string,
        modification?: Record<string, any>
    ): Promise<ReviewRequest> {
        const review = this.reviews.get(reviewId);
        if (!review) throw new Error('Review not found');
        if (review.status !== 'PENDING') throw new Error('Review already processed');

        // Check permissions
        if (!reviewer.roles.includes('admin') && !reviewer.roles.includes(review.requiredRole)) {
            throw new Error('Insufficient permissions to review this item');
        }

        review.status = decision === 'APPROVE' ? 'APPROVED' : 'REJECTED';
        review.reviewerId = reviewer.userId;
        review.reviewerComments = comments;
        review.modificationPayload = modification;

        Logger.audit('REVIEW_DECISION', reviewer, {
            reviewId,
            decision,
            workflowId: review.workflowId
        });

        this.eventBus.emit('review:decided', { reviewId, decision, modification });
        return review;
    }
}

// -----------------------------------------------------------------------------
// HTTP SERVER & API
// -----------------------------------------------------------------------------

import * as http from 'http';

class AppServer {
    private server: http.Server;
    private workflowEngine: WorkflowEngine;
    private reviewManager: ReviewManager;
    private eventBus: EventEmitter;

    constructor() {
        this.eventBus = new EventEmitter();
        this.reviewManager = new ReviewManager(this.eventBus);
        this.workflowEngine = new WorkflowEngine(this.eventBus, this.reviewManager);

        // Wire up event listeners
        this.eventBus.on('review:decided', async (event) => {
            const review = this.reviewManager.getReview(event.reviewId);
            if (review) {
                await this.workflowEngine.resumeWorkflow(
                    review.workflowId, 
                    event.decision === 'APPROVE', 
                    event.modification
                );
            }
        });

        this.server = http.createServer(this.handleRequest.bind(this));
    }

    public start() {
        this.server.listen(CONFIG.port, () => {
            Logger.log('info', `APP_09_HITL running on port ${CONFIG.port}`);
        });
    }

    private async handleRequest(req: http.IncomingMessage, res: http.ServerResponse) {
        // Basic CORS
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

        if (req.method === 'OPTIONS') {
            res.writeHead(204);
            res.end();
            return;
        }

        const url = new URL(req.url || '', `http://${req.headers.host}`);
        const path = url.pathname;

        try {
            // -----------------------------------------------------------------
            // ENDPOINTS
            // -----------------------------------------------------------------

            // 1. Submit Workflow
            if (path === '/workflows' && req.method === 'POST') {
                const body = await this.parseBody(req);
                // Mock Identity
                const identity: IdentityContext = {
                    userId: req.headers['x-user-id'] as string || 'anon',
                    orgId: 'org_default',
                    roles: ['operator'],
                    permissions: [],
                    auditTraceId: crypto.randomUUID()
                };
                
                const workflow = await this.workflowEngine.createWorkflow(
                    body.agentId, 
                    identity, 
                    body.steps
                );
                this.sendJson(res, 201, workflow);
                return;
            }

            // 2. Get Workflow Status
            if (path.match(/^\/workflows\/[\w-]+$/) && req.method === 'GET') {
                const id = path.split('/')[2];
                const workflow = this.workflowEngine.getWorkflow(id);
                if (!workflow) {
                    this.sendJson(res, 404, { error: 'Workflow not found' });
                    return;
                }
                this.sendJson(res, 200, workflow);
                return;
            }

            // 3. List Pending Reviews
            if (path === '/reviews' && req.method === 'GET') {
                const role = url.searchParams.get('role') || undefined;
                const reviews = this.reviewManager.getPendingReviews(role);
                this.sendJson(res, 200, { count: reviews.length, reviews });
                return;
            }

            // 4. Submit Review Decision
            if (path.match(/^\/reviews\/[\w-]+\/decision$/) && req.method === 'POST') {
                const id = path.split('/')[2];
                const body = await this.parseBody(req);
                
                // Mock Reviewer Identity (In real app, extracted from JWT)
                const reviewer: IdentityContext = {
                    userId: req.headers['x-user-id'] as string || 'human_reviewer',
                    orgId: 'org_default',
                    roles: ['admin', 'operator'], // Assume admin for demo
                    permissions: [],
                    auditTraceId: crypto.randomUUID()
                };

                const result = await this.reviewManager.submitDecision(
                    id, 
                    reviewer, 
                    body.decision, 
                    body.comments, 
                    body.modification
                );
                this.sendJson(res, 200, result);
                return;
            }

            // -----------------------------------------------------------------
            // MANDATORY INTROSPECTION ENDPOINTS
            // -----------------------------------------------------------------

            if (path === '/introspect' && req.method === 'GET') {
                this.sendJson(res, 200, {
                    appId: 'APP_09_Agents_HumanInLoopInterface',
                    status: 'HEALTHY',
                    metrics: {
                        activeWorkflows: 0, // TODO: Implement real counters
                        pendingReviews: this.reviewManager.getPendingReviews().length
                    },
                    config: {
                        riskThreshold: CONFIG.riskThreshold,
                        autoApproveConfidence: CONFIG.autoApproveConfidence
                    }
                });
                return;
            }

            if (path === '/assumptions' && req.method === 'GET') {
                this.sendJson(res, 200, {
                    assumptions: [
                        "Agents provide honest confidence scores.",
                        "Network latency to AI vendors is < 500ms.",
                        "Human reviewers are available within 24 hours.",
                        "Identity headers are trusted (behind gateway)."
                    ]
                });
                return;
            }

            if (path === '/failure-modes' && req.method === 'GET') {
                this.sendJson(res, 200, {
                    modes: [
                        {
                            scenario: "AI Vendor Outage",
                            impact: "Risk analysis fails; workflows default to PAUSED_FOR_REVIEW (fail-safe).",
                            mitigation: "Circuit breaker pattern implemented."
                        },
                        {
                            scenario: "Review Queue Overflow",
                            impact: "Workflows stall indefinitely.",
                            mitigation: "Alerts sent to PagerDuty when queue > 100."
                        }
                    ]
                });
                return;
            }

            if (path === '/agent-metadata' && req.method === 'GET') {
                this.sendJson(res, 200, {
                    agent_metadata: {
                        purpose: "Orchestrate human review for low-confidence or high-risk agent actions.",
                        dependencies: ["OpenAI", "Anthropic", "IdentityService"],
                        invalidation_conditions: ["Schema version mismatch", "Auth token expiry"],
                        adjacent_apps: ["APP_01_Inference_CostRouter", "APP_37_Governance_AuditTrailEngine"]
                    }
                });
                return;
            }

            this.sendJson(res, 404, { error: 'Not Found' });

        } catch (err: any) {
            Logger.log('error', 'Request failed', { error: err.message, stack: err.stack });
            this.sendJson(res, 500, { error: 'Internal Server Error', details: err.message });
        }
    }

    private parseBody(req: http.IncomingMessage): Promise<any> {
        return new Promise((resolve, reject) => {
            let body = '';
            req.on('data', chunk => body += chunk);
            req.on('end', () => {
                try {
                    resolve(JSON.parse(body));
                } catch (e) {
                    reject(e);
                }
            });
        });
    }

    private sendJson(res: http.ServerResponse, status: number, data: any) {
        res.writeHead(status, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(data, null, 2));
    }
}

// -----------------------------------------------------------------------------
// BOOTSTRAP
// -----------------------------------------------------------------------------

if (require.main === module) {
    const app = new AppServer();
    app.start();
    
    // Handle graceful shutdown
    process.on('SIGTERM', () => {
        Logger.log('info', 'SIGTERM received. Shutting down...');
        process.exit(0);
    });
}

// -----------------------------------------------------------------------------
// EXPORTS (For Testing/Importing)
// -----------------------------------------------------------------------------

export {
    AppServer,
    WorkflowEngine,
    ReviewManager,
    WorkflowStatus,
    RiskLevel
};