/**
 * Copyright (c) 2024. All rights reserved.
 * 
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 * 
 * File: packages/core-sdk/src/legal/DisclaimerInjector.ts
 * Purpose: Middleware that injects mandatory legal disclaimers and jurisdiction-specific 
 *          warnings into all AI-generated outputs. Ensures no financial advice or 
 *          guarantees are hallucinated.
 */

import { randomUUID } from 'crypto';

// ----------------------------------------------------------------------------
// Types & Interfaces
// ----------------------------------------------------------------------------

export type Jurisdiction = 'US' | 'EU' | 'UK' | 'APAC' | 'GLOBAL';
export type RiskCategory = 'FINANCIAL' | 'MEDICAL' | 'LEGAL' | 'GUARANTEE' | 'PREDICTION';

export interface DisclaimerConfig {
  enableInjection: boolean;
  defaultJurisdiction: Jurisdiction;
  strictMode: boolean; // If true, blocks output containing high-risk keywords instead of just disclaiming
  appendStrategy: 'footer' | 'metadata' | 'wrapper';
  customDisclaimers?: Record<string, string>;
}

export interface InjectionContext {
  userId?: string;
  jurisdiction?: Jurisdiction;
  requestId: string;
  domain?: string; // e.g., 'finance', 'healthcare'
  detectedRisks?: RiskCategory[];
}

export interface ProcessedOutput<T> {
  data: T;
  meta: {
    disclaimers: string[];
    jurisdiction: Jurisdiction;
    timestamp: string;
    riskAssessment: RiskCategory[];
    legalHash: string; // Hash of the disclaimers for audit
  };
}

// ----------------------------------------------------------------------------
// Constants & Dictionaries
// ----------------------------------------------------------------------------

const BASE_DISCLAIMER = 
  "DISCLAIMER: This content was generated by an artificial intelligence system. " +
  "It is provided for informational purposes only and does not constitute professional advice. " +
  "Verify all information independently.";

const JURISDICTION_SPECIFIC_WARNINGS: Record<Jurisdiction, string> = {
  US: "LIMITATION OF LIABILITY: To the maximum extent permitted by applicable law, the provider disclaims all liability for damages arising from the use of this AI output.",
  EU: "AI NOTICE: This output is generated by an automated system (AI Act Compliance). Human oversight is recommended for critical decisions.",
  UK: "NOTICE: This content is AI-generated. Not a substitute for professional consultation.",
  APAC: "NOTICE: Automated content. Use at your own risk.",
  GLOBAL: "NOTICE: AI-generated content. No warranties express or implied."
};

const RISK_DISCLAIMERS: Record<RiskCategory, string> = {
  FINANCIAL: "NOT FINANCIAL ADVICE: This system does not provide financial, investment, or tax advice. Do not make financial decisions based on this output.",
  MEDICAL: "NOT MEDICAL ADVICE: This output is not a substitute for professional medical advice, diagnosis, or treatment.",
  LEGAL: "NOT LEGAL ADVICE: This output is for informational purposes only and does not create an attorney-client relationship.",
  GUARANTEE: "NO GUARANTEE: Past performance or simulated predictions do not guarantee future results.",
  PREDICTION: "FORWARD-LOOKING STATEMENTS: Predictions generated by this model are probabilistic and may be incorrect."
};

const RISK_PATTERNS: Record<RiskCategory, RegExp[]> = {
  FINANCIAL: [
    /\b(buy|sell|short|long)\b.*\b(stock|crypto|token|asset)\b/i,
    /\b(guaranteed return|roi|profit)\b/i,
    /\b(invest in|financial advice)\b/i
  ],
  MEDICAL: [
    /\b(diagnose|treat|cure|prescription|symptom)\b/i,
    /\b(doctor|physician|patient)\b/i
  ],
  LEGAL: [
    /\b(sue|lawsuit|liable|contractual obligation)\b/i,
    /\b(attorney|lawyer|legal advice)\b/i
  ],
  GUARANTEE: [
    /\b(guarantee|promise|certainty|100%)\b/i,
    /\b(will definitely|always)\b/i
  ],
  PREDICTION: [
    /\b(predict|forecast|future value)\b/i,
    /\b(market will|price will)\b/i
  ]
};

// ----------------------------------------------------------------------------
// Core Implementation
// ----------------------------------------------------------------------------

export class DisclaimerInjector {
  private config: DisclaimerConfig;

  constructor(config?: Partial<DisclaimerConfig>) {
    this.config = {
      enableInjection: true,
      defaultJurisdiction: 'GLOBAL',
      strictMode: false,
      appendStrategy: 'metadata',
      ...config
    };
  }

  /**
   * Main entry point to process any output (string or object).
   * Injects necessary legal text based on content analysis and context.
   */
  public process<T>(output: T, context: InjectionContext): T | ProcessedOutput<T> | string {
    if (!this.config.enableInjection) {
      return output;
    }

    const jurisdiction = context.jurisdiction || this.config.defaultJurisdiction;
    const contentString = this.extractContentString(output);
    const risks = this.analyzeRisks(contentString, context.domain);

    // In strict mode, if high risks are detected, we might redact or throw
    if (this.config.strictMode && (risks.includes('FINANCIAL') || risks.includes('MEDICAL'))) {
      // For the purpose of this SDK, we replace content rather than throwing, to maintain stability
      if (typeof output === 'string') {
        return "[CONTENT REDACTED: HIGH RISK CATEGORY DETECTED IN STRICT MODE]";
      }
    }

    const disclaimers = this.assembleDisclaimers(jurisdiction, risks);

    if (this.config.appendStrategy === 'wrapper') {
      return this.wrapOutput(output, disclaimers, jurisdiction, risks);
    } else if (this.config.appendStrategy === 'footer' && typeof output === 'string') {
      return this.appendFooter(output, disclaimers);
    } else {
      // Default to metadata wrapper for objects, or footer for strings if metadata impossible
      if (typeof output === 'string') {
        return this.appendFooter(output, disclaimers);
      }
      return this.wrapOutput(output, disclaimers, jurisdiction, risks);
    }
  }

  /**
   * Analyzes text content for risk patterns.
   */
  private analyzeRisks(content: string, domain?: string): RiskCategory[] {
    const detected: Set<RiskCategory> = new Set();

    // Domain-based forcing
    if (domain?.toLowerCase().includes('finance') || domain?.toLowerCase().includes('trading')) {
      detected.add('FINANCIAL');
    }
    if (domain?.toLowerCase().includes('health') || domain?.toLowerCase().includes('medical')) {
      detected.add('MEDICAL');
    }

    // Content-based scanning
    for (const [category, patterns] of Object.entries(RISK_PATTERNS)) {
      for (const pattern of patterns) {
        if (pattern.test(content)) {
          detected.add(category as RiskCategory);
          break; // Found one match for this category, move to next
        }
      }
    }

    return Array.from(detected);
  }

  /**
   * Assembles the list of disclaimer strings.
   */
  private assembleDisclaimers(jurisdiction: Jurisdiction, risks: RiskCategory[]): string[] {
    const list: string[] = [];

    // 1. Base Disclaimer
    list.push(BASE_DISCLAIMER);

    // 2. Jurisdiction Specific
    if (JURISDICTION_SPECIFIC_WARNINGS[jurisdiction]) {
      list.push(JURISDICTION_SPECIFIC_WARNINGS[jurisdiction]);
    }

    // 3. Risk Specific
    risks.forEach(risk => {
      if (RISK_DISCLAIMERS[risk]) {
        list.push(RISK_DISCLAIMERS[risk]);
      }
    });

    // 4. Custom Configured
    if (this.config.customDisclaimers) {
      Object.values(this.config.customDisclaimers).forEach(d => list.push(d));
    }

    return list;
  }

  /**
   * Wraps the output in a standardized envelope with metadata.
   */
  private wrapOutput<T>(data: T, disclaimers: string[], jurisdiction: Jurisdiction, risks: RiskCategory[]): ProcessedOutput<T> {
    return {
      data,
      meta: {
        disclaimers,
        jurisdiction,
        timestamp: new Date().toISOString(),
        riskAssessment: risks,
        legalHash: this.hashDisclaimers(disclaimers)
      }
    };
  }

  /**
   * Appends disclaimers as a footer to a string.
   */
  private appendFooter(text: string, disclaimers: string[]): string {
    const footer = disclaimers.map(d => `[${d}]`).join('\n');
    return `${text}\n\n---\n${footer}`;
  }

  /**
   * Helper to extract string representation for analysis.
   */
  private extractContentString(output: any): string {
    if (typeof output === 'string') return output;
    if (typeof output === 'number') return output.toString();
    if (typeof output === 'object') {
      try {
        return JSON.stringify(output);
      } catch {
        return '';
      }
    }
    return '';
  }

  /**
   * Simple hash for audit trails to verify disclaimer presence without storing full text.
   */
  private hashDisclaimers(disclaimers: string[]): string {
    const content = disclaimers.join('|');
    let hash = 0;
    for (let i = 0; i < content.length; i++) {
      const char = content.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32bit integer
    }
    return hash.toString(16);
  }

  // --------------------------------------------------------------------------
  // Introspection & Self-Querying (Agent Mode)
  // --------------------------------------------------------------------------

  public getAgentMetadata() {
    return {
      purpose: "Inject mandatory legal disclaimers and detect liability risks in AI outputs.",
      dependencies: ["ConfigService", "AuditLogger"],
      invalidation_conditions: [
        "Jurisdiction laws change (e.g., new EU AI Act articles)",
        "New risk categories defined by legal counsel"
      ],
      adjacent_apps: [
        "APP_37_Governance_AuditTrailEngine",
        "APP_58_Narrative_ModelExplainabilityUI"
      ]
    };
  }

  public introspect(): object {
    return {
      config: this.config,
      active_patterns: Object.keys(RISK_PATTERNS).length,
      supported_jurisdictions: Object.keys(JURISDICTION_SPECIFIC_WARNINGS),
      status: "ACTIVE"
    };
  }
}