/**
 * @file src/models/expectedPayments.ts
 * @description TypeScript interfaces and types defining the structure for expected payment records,
 *              including fields like `amount`, `currency`, `dueDate`, and `status`.
 *              These records represent anticipated payments, likely derived from normalized
 *              multi-cloud billing data.
 */

/**
 * Enum for the possible statuses of an expected payment.
 */
export enum PaymentStatus {
  Pending = 'pending',
  Paid = 'paid',
  Overdue = 'overdue',
  Cancelled = 'cancelled',
  PartiallyPaid = 'partially_paid',
  Disputed = 'disputed',
}

/**
 * Interface representing a single expected payment record.
 */
export interface ExpectedPayment {
  /**
   * Unique identifier for the expected payment record.
   */
  id: string;

  /**
   * The monetary amount expected for this payment.
   * Represented as a number, typically in the smallest currency unit (e.g., cents)
   * or as a decimal for larger units, depending on precision requirements.
   */
  amount: number;

  /**
   * The currency code for the payment amount (e.g., 'USD', 'EUR', 'GBP').
   * Should follow ISO 4217 standard.
   */
  currency: string;

  /**
   * The date by which the payment is expected.
   * Stored as an ISO 8601 string (e.g., 'YYYY-MM-DD' or 'YYYY-MM-DDTHH:mm:ssZ').
   */
  dueDate: string;

  /**
   * The current status of the expected payment.
   */
  status: PaymentStatus;

  /**
   * Optional: A reference ID from the original source system (e.g., AWS Invoice ID, GCP Billing Account ID).
   */
  sourceId?: string;

  /**
   * Optional: The cloud provider from which this payment expectation originated (e.g., 'AWS', 'GCP', 'Azure').
   */
  sourceProvider?: string;

  /**
   * Optional: A description or note about the payment.
   */
  description?: string;

  /**
   * Optional: The date and time when this record was created.
   * Stored as an ISO 8601 string.
   */
  createdAt?: string;

  /**
   * Optional: The date and time when this record was last updated.
   * Stored as an ISO 8601 string.
   */
  updatedAt?: string;
}

/**
 * Type for creating a new expected payment.
 * `id` is typically generated by the system, so it's omitted here.
 * `createdAt` and `updatedAt` are also system-managed.
 */
export type CreateExpectedPayment = Omit<ExpectedPayment, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Type for updating an existing expected payment.
 * All fields are optional for partial updates.
 * `id` is required to identify the record to update.
 */
export type UpdateExpectedPayment = Partial<Omit<ExpectedPayment, 'id' | 'createdAt' | 'updatedAt'>> & Pick<ExpectedPayment, 'id'>;