/* eslint-disable */
/**
 * This file was auto-generated by a tool.
 * Do not modify it directly.
 */

// #region ENUMS
export enum BlendMode {
  PASS_THROUGH = "PASS_THROUGH",
  NORMAL = "NORMAL",
  DARKEN = "DARKEN",
  MULTIPLY = "MULTIPLY",
  LINEAR_BURN = "LINEAR_BURN",
  COLOR_BURN = "COLOR_BURN",
  LIGHTEN = "LIGHTEN",
  SCREEN = "SCREEN",
  LINEAR_DODGE = "LINEAR_DODGE",
  COLOR_DODGE = "COLOR_DODGE",
  OVERLAY = "OVERLAY",
  SOFT_LIGHT = "SOFT_LIGHT",
  HARD_LIGHT = "HARD_LIGHT",
  DIFFERENCE = "DIFFERENCE",
  EXCLUSION = "EXCLUSION",
  HUE = "HUE",
  SATURATION = "SATURATION",
  COLOR = "COLOR",
  LUMINOSITY = "LUMINOSITY",
}
export enum StyleType {
  FILL = "FILL",
  TEXT = "TEXT",
  EFFECT = "EFFECT",
  GRID = "GRID",
}
export enum EasingType {
  EASE_IN = "EASE_IN",
  EASE_OUT = "EASE_OUT",
  EASE_IN_AND_OUT = "EASE_IN_AND_OUT",
  LINEAR = "LINEAR",
  EASE_IN_BACK = "EASE_IN_BACK",
  EASE_OUT_BACK = "EASE_OUT_BACK",
  EASE_IN_AND_OUT_BACK = "EASE_IN_AND_OUT_BACK",
  CUSTOM_CUBIC_BEZIER = "CUSTOM_CUBIC_BEZIER",
  GENTLE = "GENTLE",
  QUICK = "QUICK",
  BOUNCY = "BOUNCY",
  SLOW = "SLOW",
  CUSTOM_SPRING = "CUSTOM_SPRING",
}
export enum ComponentPropertyType {
  BOOLEAN = "BOOLEAN",
  INSTANCE_SWAP = "INSTANCE_SWAP",
  TEXT = "TEXT",
  VARIANT = "VARIANT",
}
export enum ShapeType {
  SQUARE = "SQUARE",
  ELLIPSE = "ELLIPSE",
  ROUNDED_RECTANGLE = "ROUNDED_RECTANGLE",
  DIAMOND = "DIAMOND",
  TRIANGLE_UP = "TRIANGLE_UP",
  TRIANGLE_DOWN = "TRIANGLE_DOWN",
  PARALLELOGRAM_RIGHT = "PARALLELOGRAM_RIGHT",
  PARALLELOGRAM_LEFT = "PARALLELOGRAM_LEFT",
  ENG_DATABASE = "ENG_DATABASE",
  ENG_QUEUE = "ENG_QUEUE",
  ENG_FILE = "ENG_FILE",
  ENG_FOLDER = "ENG_FOLDER",
  TRAPEZOID = "TRAPEZOID",
  PREDEFINED_PROCESS = "PREDEFINED_PROCESS",
  SHIELD = "SHIELD",
  DOCUMENT_SINGLE = "DOCUMENT_SINGLE",
  DOCUMENT_MULTIPLE = "DOCUMENT_MULTIPLE",
  MANUAL_INPUT = "MANUAL_INPUT",
  HEXAGON = "HEXAGON",
  CHEVRON = "CHEVRON",
  PENTAGON = "PENTAGON",
  OCTAGON = "OCTAGON",
  STAR = "STAR",
  PLUS = "PLUS",
  ARROW_LEFT = "ARROW_LEFT",
  ARROW_RIGHT = "ARROW_RIGHT",
  SUMMING_JUNCTION = "SUMMING_JUNCTION",
  OR = "OR",
  SPEECH_BUBBLE = "SPEECH_BUBBLE",
  INTERNAL_STORAGE = "INTERNAL_STORAGE",
}
export enum ConnectorLineType {
  STRAIGHT = "STRAIGHT",
  ELBOWED = "ELBOWED",
  CURVED = "CURVED",
}
export enum Navigation {
  NAVIGATE = "NAVIGATE",
  SWAP = "SWAP",
  OVERLAY = "OVERLAY",
  SCROLL_TO = "SCROLL_TO",
  CHANGE_TO = "CHANGE_TO",
}
export enum WebhookV2Event {
  PING = "PING",
  FILE_UPDATE = "FILE_UPDATE",
  FILE_VERSION_UPDATE = "FILE_VERSION_UPDATE",
  FILE_DELETE = "FILE_DELETE",
  LIBRARY_PUBLISH = "LIBRARY_PUBLISH",
  FILE_COMMENT = "FILE_COMMENT",
  DEV_MODE_STATUS_UPDATE = "DEV_MODE_STATUS_UPDATE",
}
export enum WebhookV2Status {
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
}
export enum LinkAccess {
  view = "view",
  edit = "edit",
  org_view = "org_view",
  org_edit = "org_edit",
  inherit = "inherit",
}
export enum Role {
  owner = "owner",
  editor = "editor",
  viewer = "viewer",
}
// #endregion

// #region SCHEMA TYPES
export interface IsLayerTrait {
  /** A string uniquely identifying this node within the document. */
  id: string;
  /** The name given to the node by the user in the tool. */
  name: string;
  /** The type of the node */
  type: string;
  /** Whether or not the node is visible on the canvas. */
  visible?: boolean;
  /** If true, layer is locked and cannot be edited */
  locked?: boolean;
  /** How layer should be treated when the frame is resized */
  scrollBehavior: "SCROLLS" | "FIXED" | "STICKY_SCROLLS";
  /** The rotation of the node, if not 0. */
  rotation?: number;
  /** A mapping of a layer's property to component property name of component properties attached to this node. */
  componentPropertyReferences?: { [key: string]: string };
  /** Data written by plugins that is visible only to the plugin that wrote it. */
  pluginData?: any;
  /** Data written by plugins that is visible to all plugins. */
  sharedPluginData?: any;
  /** A mapping of field to the variables applied to this field. */
  boundVariables?: { [key: string]: any };
  /** A mapping of variable collection ID to mode ID representing the explicitly set modes for this node. */
  explicitVariableModes?: { [key: string]: string };
}

export interface HasChildrenTrait {
  /** An array of nodes that are direct children of this node */
  children: SubcanvasNode[];
}

export interface HasLayoutTrait {
  /** Bounding box of the node in absolute space coordinates. */
  absoluteBoundingBox: Rectangle | null;
  /** The actual bounds of a node accounting for drop shadows, thick strokes, and anything else that may fall outside the node's regular bounding box. */
  absoluteRenderBounds: Rectangle | null;
  /** Keep height and width constrained to same ratio. */
  preserveRatio?: boolean;
  /** Horizontal and vertical layout constraints for node. */
  constraints: LayoutConstraint;
  /** The top two rows of a matrix that represents the 2D transform of this node relative to its parent. */
  relativeTransform?: Transform;
  /** Width and height of element. */
  size?: Vector;
  /** Determines if the layer should stretch along the parent's counter axis. */
  layoutAlign?: "INHERIT" | "STRETCH" | "MIN" | "CENTER" | "MAX";
  /** Determines whether a layer should stretch along the parent's primary axis. */
  layoutGrow?: 0 | 1;
  /** Determines whether a layer's size and position should be determined by auto-layout settings or manually adjustable. */
  layoutPositioning?: "AUTO" | "ABSOLUTE";
  minWidth?: number;
  maxWidth?: number;
  minHeight?: number;
  maxHeight?: number;
  layoutSizingHorizontal?: "FIXED" | "HUG" | "FILL";
  layoutSizingVertical?: "FIXED" | "HUG" | "FILL";
}

export interface HasFramePropertiesTrait {
  /** Whether or not this node clip content outside of its bounds */
  clipsContent: boolean;
  /** An array of layout grids attached to this node. */
  layoutGrids?: LayoutGrid[];
  /** Whether a node has primary axis scrolling, horizontal or vertical. */
  overflowDirection?: "HORIZONTAL_SCROLLING" | "VERTICAL_SCROLLING" | "HORIZONTAL_AND_VERTICAL_SCROLLING" | "NONE";
  /** Whether this layer uses auto-layout to position its children. */
  layoutMode?: "NONE" | "HORIZONTAL" | "VERTICAL" | "GRID";
  /** Whether the primary axis has a fixed length or an automatic length. */
  primaryAxisSizingMode?: "FIXED" | "AUTO";
  /** Whether the counter axis has a fixed length or an automatic length. */
  counterAxisSizingMode?: "FIXED" | "AUTO";
  /** Determines how the auto-layout frame's children should be aligned in the primary axis direction. */
  primaryAxisAlignItems?: "MIN" | "CENTER" | "MAX" | "SPACE_BETWEEN";
  /** Determines how the auto-layout frame's children should be aligned in the counter axis direction. */
  counterAxisAlignItems?: "MIN" | "CENTER" | "MAX" | "BASELINE";
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  paddingBottom?: number;
  itemSpacing?: number;
  itemReverseZIndex?: boolean;
  strokesIncludedInLayout?: boolean;
  layoutWrap?: "NO_WRAP" | "WRAP";
  counterAxisSpacing?: number;
  counterAxisAlignContent?: "AUTO" | "SPACE_BETWEEN";
}

export interface HasBlendModeAndOpacityTrait {
  /** How this node blends with nodes behind it in the scene */
  blendMode: BlendMode;
  /** Opacity of the node */
  opacity?: number;
}

export interface HasExportSettingsTrait {
  /** An array of export settings representing images to export from the node. */
  exportSettings?: ExportSetting[];
}

export interface MinimalFillsTrait {
  /** An array of fill paints applied to the node. */
  fills: Paint[];
  /** A mapping of a StyleType to style ID of styles present on this node. */
  styles?: { [key: string]: string };
}

export interface MinimalStrokesTrait {
  /** An array of stroke paints applied to the node. */
  strokes: Paint[];
  /** The weight of strokes on the node. */
  strokeWeight?: number;
  /** Position of stroke relative to vector outline. */
  strokeAlign?: "INSIDE" | "OUTSIDE" | "CENTER";
  /** Describes how corners in vector paths are rendered. */
  strokeJoin?: "MITER" | "BEVEL" | "ROUND";
  /** An array of floating point numbers describing the pattern of dash length and gap lengths. */
  strokeDashes?: number[];
}

export interface HasGeometryTrait extends MinimalFillsTrait, MinimalStrokesTrait {
  /** Map from ID to PaintOverride for looking up fill overrides. */
  fillOverrideTable?: { [key: string]: PaintOverride | null };
  /** An array of paths representing the object fill. */
  fillGeometry?: Path[];
  /** An array of paths representing the object stroke. */
  strokeGeometry?: Path[];
  /** A string enum describing the end caps of vector paths. */
  strokeCap?: "NONE" | "ROUND" | "SQUARE" | "LINE_ARROW" | "TRIANGLE_ARROW" | "DIAMOND_FILLED" | "CIRCLE_FILLED" | "TRIANGLE_FILLED" | "WASHI_TAPE_1" | "WASHI_TAPE_2" | "WASHI_TAPE_3" | "WASHI_TAPE_4" | "WASHI_TAPE_5" | "WASHI_TAPE_6";
  /** The corner angle, in degrees, below which strokeJoin will be set to "BEVEL". */
  strokeMiterAngle?: number;
}

export interface IndividualStrokesTrait {
  /** An object including the top, bottom, left, and right stroke weights. */
  individualStrokeWeights?: StrokeWeights;
}

export interface CornerTrait {
  /** Radius of each corner if a single radius is set for all corners */
  cornerRadius?: number;
  /** A value that lets you control how "smooth" the corners are. */
  cornerSmoothing?: number;
  /** Array of length 4 of the radius of each corner of the frame. */
  rectangleCornerRadii?: number[];
}

export interface HasEffectsTrait {
  /** An array of effects attached to this node */
  effects: Effect[];
}

export interface HasMaskTrait {
  /** Does this node mask sibling nodes in front of it? */
  isMask?: boolean;
  /** The operation used to mask the layer's siblings. */
  maskType?: "ALPHA" | "VECTOR" | "LUMINANCE";
}

export interface ComponentPropertiesTrait {
  /** A mapping of name to ComponentPropertyDefinition for every component property on this component. */
  componentPropertyDefinitions?: { [key: string]: ComponentPropertyDefinition };
}

export interface TypePropertiesTrait {
  /** The raw characters in the text node. */
  characters: string;
  /** Style of text including font family and weight. */
  style: TypeStyle;
  /** Array of style overrides. */
  characterStyleOverrides: number[];
  /** Map from ID to TypeStyle for looking up style overrides. */
  styleOverrideTable: { [key: string]: TypeStyle };
  /** List type for each line. */
  lineTypes: ("NONE" | "ORDERED" | "UNORDERED")[];
  /** Indentation level for each line. */
  lineIndentations: number[];
}

export interface TransitionSourceTrait {
  /** Node ID of node to transition to in prototyping */
  transitionNodeID?: string;
  /** The duration of the prototyping transition on this node (in milliseconds). */
  transitionDuration?: number;
  /** The easing curve used in the prototyping transition on this node. */
  transitionEasing?: EasingType;
  /** An array of the interactions on this node. */
  interactions?: Interaction[];
}

export interface DevStatusTrait {
  /** Represents whether or not a node has a particular handoff (or dev) status applied to it. */
  devStatus?: {
    type: "NONE" | "READY_FOR_DEV" | "COMPLETED";
    /** An optional field where the designer can add more information about the design and what has changed. */
    description?: string;
  };
}

export interface AnnotationsTrait {}

export interface FrameTraits extends
  IsLayerTrait,
  HasBlendModeAndOpacityTrait,
  HasChildrenTrait,
  HasLayoutTrait,
  HasFramePropertiesTrait,
  CornerTrait,
  HasGeometryTrait,
  HasExportSettingsTrait,
  HasEffectsTrait,
  HasMaskTrait,
  TransitionSourceTrait,
  IndividualStrokesTrait,
  DevStatusTrait,
  AnnotationsTrait {}

export interface DefaultShapeTraits extends
  IsLayerTrait,
  HasBlendModeAndOpacityTrait,
  HasLayoutTrait,
  HasGeometryTrait,
  HasExportSettingsTrait,
  HasEffectsTrait,
  HasMaskTrait,
  TransitionSourceTrait {}

export interface CornerRadiusShapeTraits extends DefaultShapeTraits, CornerTrait {}
export interface RectangularShapeTraits extends DefaultShapeTraits, CornerTrait, IndividualStrokesTrait, AnnotationsTrait {}

export interface DocumentNode extends IsLayerTrait {
  type: "DOCUMENT";
  children: CanvasNode[];
}

export interface CanvasNode extends IsLayerTrait, HasExportSettingsTrait {
  type: "CANVAS";
  children: SubcanvasNode[];
  /** Background color of the canvas. */
  backgroundColor: RGBA;
  /** An array of flow starting points sorted by its position in the prototype settings panel. */
  flowStartingPoints: FlowStartingPoint[];
  /** The device used to view a prototype. */
  prototypeDevice: PrototypeDevice;
  prototypeStartNodeID: string | null;
}

export interface SectionNode extends IsLayerTrait, HasGeometryTrait, HasChildrenTrait, HasLayoutTrait, DevStatusTrait {
  type: "SECTION";
  sectionContentsHidden?: boolean;
}

export interface FrameNode extends FrameTraits {
  type: "FRAME";
}

export interface GroupNode extends FrameTraits {
  type: "GROUP";
}

export interface ComponentNode extends FrameTraits, ComponentPropertiesTrait {
  type: "COMPONENT";
}

export interface ComponentSetNode extends FrameTraits, ComponentPropertiesTrait {
  type: "COMPONENT_SET";
}

export interface VectorNode extends CornerRadiusShapeTraits, AnnotationsTrait {
  type: "VECTOR";
}

export interface StarNode extends CornerRadiusShapeTraits, AnnotationsTrait {
  type: "STAR";
}

export interface LineNode extends DefaultShapeTraits, AnnotationsTrait {
  type: "LINE";
}

export interface EllipseNode extends DefaultShapeTraits, AnnotationsTrait {
  type: "ELLIPSE";
  arcData: ArcData;
}

export interface RegularPolygonNode extends CornerRadiusShapeTraits, AnnotationsTrait {
  type: "REGULAR_POLYGON";
}

export interface RectangleNode extends RectangularShapeTraits {
  type: "RECTANGLE";
}

export interface TextNode extends DefaultShapeTraits, TypePropertiesTrait, AnnotationsTrait {
  type: "TEXT";
}

export interface SliceNode extends IsLayerTrait {
  type: "SLICE";
}

export interface InstanceNode extends FrameTraits {
  type: "INSTANCE";
  /** ID of component that this instance came from. */
  componentId: string;
  /** If true, this node has been marked as exposed to its containing component or component set. */
  isExposedInstance?: boolean;
  /** IDs of instances that have been exposed to this node's level. */
  exposedInstances?: string[];
  /** A mapping of name to ComponentProperty for all component properties on this instance. */
  componentProperties?: { [key: string]: ComponentProperty };
  /** An array of all of the fields directly overridden on this instance. */
  overrides: Overrides[];
}

export interface BooleanOperationNode extends
  IsLayerTrait,
  HasBlendModeAndOpacityTrait,
  HasChildrenTrait,
  HasLayoutTrait,
  HasGeometryTrait,
  HasExportSettingsTrait,
  HasEffectsTrait,
  HasMaskTrait,
  TransitionSourceTrait {
  type: "BOOLEAN_OPERATION";
  /** A string enum indicating the type of boolean operation applied. */
  booleanOperation: "UNION" | "INTERSECT" | "SUBTRACT" | "EXCLUDE";
}

export interface EmbedNode extends IsLayerTrait, HasExportSettingsTrait {
  type: "EMBED";
}

export interface LinkUnfurlNode extends IsLayerTrait, HasExportSettingsTrait {
  type: "LINK_UNFURL";
}

export interface StickyNode extends IsLayerTrait, HasLayoutTrait, HasBlendModeAndOpacityTrait, MinimalFillsTrait, HasMaskTrait, HasEffectsTrait, HasExportSettingsTrait {
  type: "STICKY";
  authorVisible?: boolean;
  characters: string;
}

export interface ShapeWithTextNode extends IsLayerTrait, HasLayoutTrait, HasBlendModeAndOpacityTrait, MinimalFillsTrait, HasMaskTrait, HasEffectsTrait, HasExportSettingsTrait, CornerTrait, MinimalStrokesTrait {
  type: "SHAPE_WITH_TEXT";
  shapeType: ShapeType;
  characters: string;
}

export interface ConnectorNode extends IsLayerTrait, HasLayoutTrait, HasBlendModeAndOpacityTrait, HasEffectsTrait, HasExportSettingsTrait, MinimalStrokesTrait {
  type: "CONNECTOR";
  connectorStart: ConnectorEndpoint;
  connectorEnd: ConnectorEndpoint;
  connectorStartStrokeCap?: "NONE" | "LINE_ARROW" | "TRIANGLE_ARROW" | "DIAMOND_FILLED" | "CIRCLE_FILLED" | "TRIANGLE_FILLED";
  connectorEndStrokeCap?: "NONE" | "LINE_ARROW" | "TRIANGLE_ARROW" | "DIAMOND_FILLED" | "CIRCLE_FILLED" | "TRIANGLE_FILLED";
  connectorLineType: ConnectorLineType;
  textBackground?: ConnectorTextBackground;
  characters: string;
}

export interface WashiTapeNode extends DefaultShapeTraits {
  type: "WASHI_TAPE";
}

export interface WidgetNode extends IsLayerTrait, HasExportSettingsTrait, HasChildrenTrait {
  type: "WIDGET";
}

export interface TableNode extends IsLayerTrait, HasChildrenTrait, HasLayoutTrait, MinimalStrokesTrait, HasEffectsTrait, HasBlendModeAndOpacityTrait, HasExportSettingsTrait {
    type: "TABLE";
}

export interface TableCellNode extends IsLayerTrait, MinimalFillsTrait, HasLayoutTrait {
    type: "TABLE_CELL";
    characters: string;
}

export interface TransformGroupNode extends FrameTraits {
    type: "TRANSFORM_GROUP";
}

export interface TextPathNode extends DefaultShapeTraits {
    type: "TEXT_PATH";
    characters: string;
    style: TextPathTypeStyle;
    characterStyleOverrides: number[];
    styleOverrideTable: { [key: string]: TextPathTypeStyle };
}

export type Node =
  | BooleanOperationNode
  | ComponentNode
  | ComponentSetNode
  | ConnectorNode
  | EllipseNode
  | EmbedNode
  | FrameNode
  | GroupNode
  | InstanceNode
  | LineNode
  | LinkUnfurlNode
  | RectangleNode
  | RegularPolygonNode
  | SectionNode
  | ShapeWithTextNode
  | SliceNode
  | StarNode
  | StickyNode
  | TableNode
  | TableCellNode
  | TextNode
  | TextPathNode
  | TransformGroupNode
  | VectorNode
  | WashiTapeNode
  | WidgetNode
  | DocumentNode
  | CanvasNode;

export type SubcanvasNode =
  | BooleanOperationNode
  | ComponentNode
  | ComponentSetNode
  | ConnectorNode
  | EllipseNode
  | EmbedNode
  | FrameNode
  | GroupNode
  | InstanceNode
  | LineNode
  | LinkUnfurlNode
  | RectangleNode
  | RegularPolygonNode
  | SectionNode
  | ShapeWithTextNode
  | SliceNode
  | StarNode
  | StickyNode
  | TableNode
  | TableCellNode
  | TextNode
  | TextPathNode
  | TransformGroupNode
  | VectorNode
  | WashiTapeNode
  | WidgetNode;


// #region Helper Types
export interface RGBA { r: number; g: number; b: number; a: number; }
export interface RGB { r: number; g: number; b: number; }
export interface Vector { x: number; y: number; }
export interface Rectangle extends Vector { width: number; height: number; }
export type Transform = [[number, number, number], [number, number, number]];
export interface FlowStartingPoint { nodeId: string; name: string; }
export interface Size { width: number; height: number; }
export interface PrototypeDevice { type: "NONE" | "PRESET" | "CUSTOM" | "PRESENTATION"; size?: Size; presetIdentifier?: string; rotation: "NONE" | "CCW_90"; }
export interface Constraint { type: "SCALE" | "WIDTH" | "HEIGHT"; value: number; }
export interface ExportSetting { suffix: string; format: "JPG" | "PNG" | "SVG" | "PDF"; constraint: Constraint; }
export interface ColorStop { position: number; color: RGBA; boundVariables?: { color?: VariableAlias }; }
export interface ImageFilters { exposure?: number; contrast?: number; saturation?: number; temperature?: number; tint?: number; highlights?: number; shadows?: number; }

export interface BasePaint { visible?: boolean; opacity?: number; blendMode: BlendMode; }
export interface SolidPaint extends BasePaint { type: "SOLID"; color: RGBA; boundVariables?: { color?: VariableAlias }; }
export interface GradientPaint extends BasePaint { type: "GRADIENT_LINEAR" | "GRADIENT_RADIAL" | "GRADIENT_ANGULAR" | "GRADIENT_DIAMOND"; gradientHandlePositions: Vector[]; gradientStops: ColorStop[]; }
export interface ImagePaint extends BasePaint { type: "IMAGE"; scaleMode: "FILL" | "FIT" | "TILE" | "STRETCH"; imageRef: string; imageTransform?: Transform; scalingFactor?: number; filters?: ImageFilters; rotation?: number; gifRef?: string; }
export interface PatternPaint extends BasePaint { type: "PATTERN"; sourceNodeId: string; tileType: "RECTANGULAR" | "HORIZONTAL_HEXAGONAL" | "VERTICAL_HEXAGONAL"; scalingFactor: number; spacing: Vector; horizontalAlignment: "START" | "CENTER" | "END"; verticalAlignment: "START" | "CENTER" | "END"; }
export type Paint = SolidPaint | GradientPaint | ImagePaint | PatternPaint;

export interface LayoutConstraint { vertical: "TOP" | "BOTTOM" | "CENTER" | "TOP_BOTTOM" | "SCALE"; horizontal: "LEFT" | "RIGHT" | "CENTER" | "LEFT_RIGHT" | "SCALE"; }
export interface LayoutGrid { pattern: "COLUMNS" | "ROWS" | "GRID"; sectionSize: number; visible: boolean; color: RGBA; alignment: "MIN" | "MAX" | "STRETCH" | "CENTER"; gutterSize: number; offset: number; count: number; }

export interface BaseShadowEffect { color: RGBA; blendMode: BlendMode; offset: Vector; radius: number; spread?: number; visible: boolean; }
export interface DropShadowEffect extends BaseShadowEffect { type: "DROP_SHADOW"; showShadowBehindNode?: boolean; }
export interface InnerShadowEffect extends BaseShadowEffect { type: "INNER_SHADOW"; }
export interface BaseBlurEffect { type: "LAYER_BLUR" | "BACKGROUND_BLUR"; visible: boolean; radius: number; }
export interface NormalBlurEffect extends BaseBlurEffect { blurType: "NORMAL"; }
export type Effect = DropShadowEffect | InnerShadowEffect | BaseBlurEffect;

export interface StrokeWeights { top: number; right: number; bottom: number; left: number; }
export interface PaintOverride { fills: Paint[]; inheritFillStyleId?: string; }
export interface Path { path: string; windingRule: "NONZERO" | "EVENODD"; overrideID?: number; }
export interface ArcData { startingAngle?: number; endingAngle?: number; innerRadius?: number; }
export interface Hyperlink { type: "URL" | "NODE"; url?: string; nodeID?: string; }

export interface BaseTypeStyle {
  fontFamily: string;
  fontPostScriptName: string | null;
  fontStyle: string;
  italic?: boolean;
  fontWeight: number;
  fontSize: number;
  textCase?: "ORIGINAL" | "UPPER" | "LOWER" | "TITLE" | "SMALL_CAPS" | "SMALL_CAPS_FORCED";
  textAlignHorizontal: "LEFT" | "RIGHT" | "CENTER" | "JUSTIFIED";
  textAlignVertical: "TOP" | "CENTER" | "BOTTOM";
  letterSpacing: number;
  fills?: Paint[];
  hyperlink?: Hyperlink;
  opentypeFlags?: { [key: string]: number };
}

export interface TypeStyle extends BaseTypeStyle {
  paragraphSpacing?: number;
  paragraphIndent?: number;
  listSpacing?: number;
  textDecoration?: "NONE" | "STRIKETHROUGH" | "UNDERLINE";
  textAutoResize?: "NONE" | "WIDTH_AND_HEIGHT" | "HEIGHT" | "TRUNCATE";
  textTruncation?: "DISABLED" | "ENDING";
  maxLines?: number;
  lineHeightPx: number;
  lineHeightPercent?: number;
  lineHeightPercentFontSize?: number;
  lineHeightUnit: "PIXELS" | "FONT_SIZE_%" | "INTRINSIC_%";
}

export interface TextPathTypeStyle extends BaseTypeStyle {
    isOverrideOverTextStyle?: boolean;
}

export interface InstanceSwapPreferredValue { type: "COMPONENT" | "COMPONENT_SET"; key: string; }
export interface ComponentPropertyDefinition { type: ComponentPropertyType; defaultValue: boolean | string; variantOptions?: string[]; preferredValues?: InstanceSwapPreferredValue[]; }
export interface ComponentProperty { type: ComponentPropertyType; value: boolean | string; preferredValues?: InstanceSwapPreferredValue[]; }
export interface Overrides { id: string; overriddenFields: string[]; }
export type ConnectorEndpoint = { endpointNodeId: string; position: Vector; } | { endpointNodeId: string; magnet: "AUTO" | "TOP" | "BOTTOM" | "LEFT" | "RIGHT" | "CENTER"; };
export interface ConnectorTextBackground extends CornerTrait, MinimalFillsTrait {}
export interface DocumentationLink { uri: string; }

export interface VariableAlias { type: "VARIABLE_ALIAS"; id: string; }

export interface Interaction { trigger: Trigger | null; actions: Action[]; }

export type Trigger =
  | { type: "ON_CLICK" | "ON_HOVER" | "ON_PRESS" | "ON_DRAG" }
  | { type: "AFTER_TIMEOUT"; timeout: number }
  | { type: "MOUSE_ENTER" | "MOUSE_LEAVE" | "MOUSE_UP" | "MOUSE_DOWN"; delay: number }
  | { type: "ON_KEY_DOWN"; device: "KEYBOARD" | "XBOX_ONE" | "PS4" | "SWITCH_PRO" | "UNKNOWN_CONTROLLER"; keyCodes: number[] }
  | { type: "ON_MEDIA_HIT"; mediaHitTime: number }
  | { type: "ON_MEDIA_END" };

export interface NodeAction {
  type: "NODE";
  destinationId: string | null;
  navigation: Navigation;
  transition: Transition | null;
  preserveScrollPosition: boolean;
  overlayRelativePosition?: Vector;
}
export type Action =
  | { type: "BACK" | "CLOSE" }
  | { type: "URL"; url: string }
  | NodeAction;

export interface Easing {
    type: EasingType;
    easingFunctionCubicBezier?: { x1: number, y1: number, x2: number, y2: number };
}
export type Transition =
  | { type: "DISSOLVE" | "SMART_ANIMATE" | "SCROLL_ANIMATE"; duration: number; easing: Easing }
  | { type: "MOVE_IN" | "MOVE_OUT" | "PUSH" | "SLIDE_IN" | "SLIDE_OUT"; direction: "LEFT" | "RIGHT" | "TOP" | "BOTTOM"; duration: number; easing: Easing; matchLayers: boolean };

export interface FrameInfo { nodeId: string; name: string; backgroundColor: string; pageId: string; pageName: string; }
export interface Component { key: string; name: string; description: string; componentSetId?: string; documentationLinks: DocumentationLink[]; remote: boolean; }
export interface ComponentSet { key: string; name: string; description: string; documentationLinks: DocumentationLink[]; remote: boolean; }
export interface Style { key: string; name: string; description: string; remote: boolean; styleType: StyleType; }
export interface User { id: string; handle: string; img_url: string; }
export interface FrameOffset { node_id: string; node_offset: Vector; }
export interface Version { id: string; created_at: string; label: string | null; description: string | null; user: User; thumbnail_url: string; }

export interface Comment {
  id: string;
  client_meta: Vector | FrameOffset;
  file_key: string;
  parent_id?: string;
  user: User;
  created_at: string;
  resolved_at: string | null;
  message: string;
  order_id: string | null;
  reactions: Reaction[];
}

export interface Reaction {
  user: User;
  emoji: string;
  created_at: string;
}

export interface Project { id: string; name: string; }
export interface FileMeta { key: string; name: string; thumbnail_url: string; last_modified: string; }
export interface DevResource { id: string; name: string; url: string; file_key: string; node_id: string; }

// #endregion


// #region API RESPONSE TYPES

export type GetFileResponse = {
  name: string;
  role: Role;
  lastModified: string;
  editorType: "figma" | "figjam";
  thumbnailUrl: string;
  version: string;
  document: DocumentNode;
  components: { [key: string]: Component };
  componentSets: { [key: string]: ComponentSet };
  schemaVersion: number;
  styles: { [key: string]: Style };
  linkAccess?: string;
  mainFileKey?: string;
  branches?: {
    key: string;
    name: string;
    thumbnail_url: string;
    last_modified: string;
  }[];
};

export type GetFileNodesResponse = {
  name: string;
  role: Role;
  lastModified: string;
  editorType: "figma" | "figjam";
  thumbnailUrl: string;
  version: string;
  nodes: {
    [nodeId: string]: {
      document: Node;
      components: { [key: string]: Component };
      componentSets: { [key: string]: ComponentSet };
      schemaVersion: number;
      styles: { [key: string]: Style };
    } | null;
  };
};

export type GetImagesResponse = {
  err: null;
  images: { [nodeId: string]: string | null };
};

export type GetImageFillsResponse = {
  error: false;
  status: 200;
  meta: {
    images: { [imageRef: string]: string };
  };
};

export type GetFileMetaResponse = {
  name: string;
  folder_name: string;
  last_touched_at: string;
  creator: User;
  last_touched_by: User;
  thumbnail_url: string;
  editorType: "figma" | "figjam" | "slides" | "buzz" | "sites" | "make";
  role: Role;
  link_access: LinkAccess;
  url: string;
  version: string;
};

export type GetTeamProjectsResponse = {
  name: string;
  projects: Project[];
};

export type GetProjectFilesResponse = {
  name: string;
  files: FileMeta[];
};

export type GetFileVersionsResponse = {
  versions: Version[];
  pagination: {
    prev_page: string | null;
    next_page: string | null;
  };
};

export type GetCommentsResponse = {
  comments: Comment[];
};

export type PostCommentResponse = Comment;

export type GetMeResponse = User & { email: string };

export type PublishedComponent = {
  key: string;
  file_key: string;
  node_id: string;
  thumbnail_url: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  user: User;
  containing_frame?: FrameInfo;
};

export type PublishedComponentSet = {
  key: string;
  file_key: string;
  node_id: string;
  thumbnail_url: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  user: User;
  containing_frame?: FrameInfo;
};

export type PublishedStyle = {
  key: string;
  file_key: string;
  node_id: string;
  style_type: StyleType;
  thumbnail_url: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  user: User;
  sort_position: string;
};

type PaginatedResponse<T> = {
  status: 200;
  error: false;
  meta: {
    cursor: { before: number; after: number };
  } & T;
};

export type GetTeamComponentsResponse = PaginatedResponse<{ components: PublishedComponent[] }>;
export type GetFileComponentsResponse = { status: 200; error: false; meta: { components: PublishedComponent[] } };
export type GetComponentResponse = { status: 200; error: false; meta: PublishedComponent };

export type GetTeamComponentSetsResponse = PaginatedResponse<{ component_sets: PublishedComponentSet[] }>;
export type GetFileComponentSetsResponse = { status: 200; error: false; meta: { component_sets: PublishedComponentSet[] } };
export type GetComponentSetResponse = { status: 200; error: false; meta: PublishedComponentSet };

export type GetTeamStylesResponse = PaginatedResponse<{ styles: PublishedStyle[] }>;
export type GetFileStylesResponse = { status: 200; error: false; meta: { styles: PublishedStyle[] } };
export type GetStyleResponse = { status: 200; error: false; meta: PublishedStyle };

export type PostDevResourcesResponse = {
    links_created: DevResource[];
    errors: {
        file_key?: string | null;
        node_id?: string | null;
        error: string;
    }[];
}

export type PutDevResourcesResponse = {
    links_updated: DevResource[];
    errors: {
        id: string;
        error: string;
    }[];
}

// #endregion


export class FigmaApiError extends Error {
  constructor(public status: number, public errorData: any) {
    const message = errorData?.err || errorData?.message || `Figma API request failed with status ${status}`;
    super(message);
    this.name = 'FigmaApiError';
  }
}

export interface FigmaApiClientOptions {
  /** Your personal access token or OAuth2 token */
  apiToken: string;
  /** The base URL for the Figma API */
  baseUrl?: string;
}

export class FigmaApiClient {
  private readonly apiToken: string;
  private readonly baseUrl: string;

  constructor(options: FigmaApiClientOptions) {
    if (!options.apiToken) {
      throw new Error("Figma API token is required.");
    }
    this.apiToken = options.apiToken;
    this.baseUrl = options.baseUrl || 'https://api.figma.com';
  }

  private async request<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    path: string,
    params?: { query?: Record<string, any>; body?: any }
  ): Promise<T> {
    const url = new URL(`${this.baseUrl}${path}`);
    if (params?.query) {
      for (const [key, value] of Object.entries(params.query)) {
        if (value !== undefined && value !== null) {
          url.searchParams.append(key, String(value));
        }
      }
    }

    const response = await fetch(url.toString(), {
      method,
      headers: {
        'Content-Type': 'application/json',
        'X-Figma-Token': this.apiToken,
      },
      body: params?.body ? JSON.stringify(params.body) : undefined,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: response.statusText }));
      throw new FigmaApiError(response.status, errorData);
    }
    
    if (response.status === 204 || response.headers.get('content-length') === '0') {
      return {} as T;
    }

    return response.json() as Promise<T>;
  }

  // #region Files
  /**
   * Returns the document identified by `file_key` as a JSON object.
   */
  public getFile(params: { file_key: string; version?: string; ids?: string; depth?: number; geometry?: string; plugin_data?: string; branch_data?: boolean }): Promise<GetFileResponse> {
    const { file_key, ...query } = params;
    return this.request('GET', `/v1/files/${file_key}`, { query });
  }

  /**
   * Returns the nodes referenced to by `ids` as a JSON object.
   */
  public getFileNodes(params: { file_key: string; ids: string; version?: string; depth?: number; geometry?: string; plugin_data?: string }): Promise<GetFileNodesResponse> {
    const { file_key, ...query } = params;
    return this.request('GET', `/v1/files/${file_key}/nodes`, { query });
  }

  /**
   * Renders images from a file.
   */
  public getImages(params: { file_key: string; ids: string; version?: string; scale?: number; format?: 'jpg' | 'png' | 'svg' | 'pdf'; svg_outline_text?: boolean; svg_include_id?: boolean; svg_include_node_id?: boolean; svg_simplify_stroke?: boolean; contents_only?: boolean; use_absolute_bounds?: boolean }): Promise<GetImagesResponse> {
    const { file_key, ...query } = params;
    return this.request('GET', `/v1/images/${file_key}`, { query });
  }

  /**
   * Returns download links for all images present in image fills in a document.
   */
  public getImageFills(params: { file_key: string }): Promise<GetImageFillsResponse> {
    return this.request('GET', `/v1/files/${params.file_key}/images`);
  }

  /**
   * Get file metadata
   */
  public getFileMeta(params: { file_key: string }): Promise<GetFileMetaResponse> {
      return this.request('GET', `/v1/files/${params.file_key}/meta`);
  }

  /**
   * Fetches the version history of a file.
   */
  public getFileVersions(params: { file_key: string; page_size?: number; before?: number; after?: number }): Promise<GetFileVersionsResponse> {
    const { file_key, ...query } = params;
    return this.request('GET', `/v1/files/${file_key}/versions`, { query });
  }
  // #endregion

  // #region Projects
  /**
   * Get a list of all the Projects within the specified team.
   */
  public getTeamProjects(params: { team_id: string }): Promise<GetTeamProjectsResponse> {
    return this.request('GET', `/v1/teams/${params.team_id}/projects`);
  }

  /**
   * Get a list of all the Files within the specified project.
   */
  public getProjectFiles(params: { project_id: string; branch_data?: boolean }): Promise<GetProjectFilesResponse> {
    const { project_id, ...query } = params;
    return this.request('GET', `/v1/projects/${project_id}/files`, { query });
  }
  // #endregion

  // #region Comments
  /**
   * Gets a list of comments left on the file.
   */
  public getComments(params: { file_key: string; as_md?: boolean }): Promise<GetCommentsResponse> {
    const { file_key, ...query } = params;
    return this.request('GET', `/v1/files/${file_key}/comments`, { query });
  }

  /**
   * Posts a new comment on the file.
   */
  public postComment(params: { file_key: string; message: string; comment_id?: string; client_meta: Vector | FrameOffset }): Promise<PostCommentResponse> {
    const { file_key, ...body } = params;
    return this.request('POST', `/v1/files/${file_key}/comments`, { body });
  }

  /**
   * Deletes a specific comment.
   */
  public deleteComment(params: { file_key: string; comment_id: string }): Promise<void> {
    return this.request('DELETE', `/v1/files/${params.file_key}/comments/${params.comment_id}`);
  }

  /**
   * Posts a new comment reaction on a file comment.
   */
  public postCommentReaction(params: { file_key: string; comment_id: string; emoji: string }): Promise<void> {
    const { file_key, comment_id, ...body } = params;
    return this.request('POST', `/v1/files/${file_key}/comments/${comment_id}/reactions`, { body });
  }

  /**
   * Deletes a specific comment reaction.
   */
  public deleteCommentReaction(params: { file_key: string; comment_id: string; emoji: string }): Promise<void> {
    const { file_key, comment_id, ...query } = params;
    return this.request('DELETE', `/v1/files/${file_key}/comments/${comment_id}/reactions`, { query });
  }
  // #endregion
  
  // #region Users
  /**
   * Returns the user information for the currently authenticated user.
   */
  public getMe(): Promise<GetMeResponse> {
    return this.request('GET', '/v1/me');
  }
  // #endregion
  
  // #region Components & Styles
  /**
   * Get a paginated list of published components within a team library.
   */
  public getTeamComponents(params: { team_id: string; page_size?: number; after?: number; before?: number }): Promise<GetTeamComponentsResponse> {
    const { team_id, ...query } = params;
    return this.request('GET', `/v1/teams/${team_id}/components`, { query });
  }

  /**
   * Get a list of published components within a file library.
   */
  public getFileComponents(params: { file_key: string }): Promise<GetFileComponentsResponse> {
    return this.request('GET', `/v1/files/${params.file_key}/components`);
  }

  /**
   * Get metadata on a component by key.
   */
  public getComponent(params: { key: string }): Promise<GetComponentResponse> {
    return this.request('GET', `/v1/components/${params.key}`);
  }

  /**
   * Get a paginated list of published component sets within a team library.
   */
  public getTeamComponentSets(params: { team_id: string; page_size?: number; after?: number; before?: number }): Promise<GetTeamComponentSetsResponse> {
    const { team_id, ...query } = params;
    return this.request('GET', `/v1/teams/${team_id}/component_sets`, { query });
  }

  /**
   * Get a list of published component sets within a file library.
   */
  public getFileComponentSets(params: { file_key: string }): Promise<GetFileComponentSetsResponse> {
    return this.request('GET', `/v1/files/${params.file_key}/component_sets`);
  }

  /**
   * Get metadata on a published component set by key.
   */
  public getComponentSet(params: { key: string }): Promise<GetComponentSetResponse> {
    return this.request('GET', `/v1/component_sets/${params.key}`);
  }

  /**
   * Get a paginated list of published styles within a team library.
   */
  public getTeamStyles(params: { team_id: string; page_size?: number; after?: number; before?: number }): Promise<GetTeamStylesResponse> {
    const { team_id, ...query } = params;
    return this.request('GET', `/v1/teams/${team_id}/styles`, { query });
  }

  /**
   * Get a list of published styles within a file library.
   */
  public getFileStyles(params: { file_key: string }): Promise<GetFileStylesResponse> {
    return this.request('GET', `/v1/files/${params.file_key}/styles`);
  }

  /**
   * Get metadata on a style by key.
   */
  public getStyle(params: { key: string }): Promise<GetStyleResponse> {
    return this.request('GET', `/v1/styles/${params.key}`);
  }
  // #endregion

  // #region Dev Resources
  /**
    * Get dev resources in a file
    */
  public getDevResources(params: { file_key: string; node_ids?: string }): Promise<{ dev_resources: DevResource[] }> {
    const { file_key, ...query } = params;
    return this.request('GET', `/v1/files/${file_key}/dev_resources`, { query });
  }

  /**
    * Bulk create dev resources across multiple files.
    */
  public postDevResources(body: { dev_resources: { name: string; url: string; file_key: string; node_id: string; }[] }): Promise<PostDevResourcesResponse> {
    return this.request('POST', '/v1/dev_resources', { body });
  }
  
  /**
    * Bulk update dev resources across multiple files.
    */
  public putDevResources(body: { dev_resources: { id: string; name?: string; url?: string; }[] }): Promise<PutDevResourcesResponse> {
    return this.request('PUT', '/v1/dev_resources', { body });
  }
  
  /**
    * Delete a dev resource from a file
    */
  public deleteDevResource(params: { file_key: string; dev_resource_id: string }): Promise<void> {
    return this.request('DELETE', `/v1/files/${params.file_key}/dev_resources/${params.dev_resource_id}`);
  }
  // #endregion
}