export interface AuditEvent {
  /**
   * Mandatory. ISO 8601 timestamp when the event occurred.
   * Automatically generated by the logger.
   */
  timestamp: string;
  /**
   * Identifier of the user or system performing the action.
   * e.g., userId, client_id, service_account_id.
   */
  actorId?: string;
  /**
   * Mandatory. A clear description or code for the action performed.
   * e.g., 'CUSTOMER_PROFILE_UPDATE', 'TOKEN_REFRESH', 'PRODUCT_RETRIEVAL_ATTEMPT'.
   */
  action: string;
  /**
   * The type of entity involved in the action.
   * e.g., 'Customer', 'Account', 'Token', 'Product'.
   */
  entityType?: string;
  /**
   * The ID of the specific entity affected by the action.
   * e.g., accountId, customerId.
   */
  entityId?: string;
  /**
   * Mandatory. The outcome of the action.
   */
  status: 'SUCCESS' | 'FAILURE' | 'INFO' | 'WARNING';
  /**
   * Additional contextual information relevant to the event.
   * Should contain non-sensitive data or securely masked sensitive data.
   */
  details?: Record<string, any>;
  /**
   * A unique identifier to correlate related audit events across a single request or transaction.
   * e.g., uuid from request headers.
   */
  correlationId?: string;
  /**
   * The IP address from which the action originated.
   */
  sourceIp?: string;
  /**
   * The User-Agent string from the client making the request.
   */
  userAgent?: string;
}

/**
 * Service for creating immutable logs of critical system actions for compliance.
 * Implemented as a Singleton to ensure a single point of logging control.
 *
 * In a production environment, this logger would integrate with a robust
 * logging infrastructure (e.g., a dedicated audit log database, SIEM system,
 * or cloud logging service) configured for high availability, immutability,
 * and tamper detection. This current implementation uses console logging
 * for demonstration purposes.
 */
export class AuditLogger {
  private static instance: AuditLogger;

  /**
   * Private constructor to enforce the Singleton pattern.
   * In a real application, this would initialize connections to external
   * logging services or database clients.
   */
  private constructor() {
    console.log('[AuditLogger] Initialized.');
    // Example: Initialize a connection to a database or a logging service client
    // this.auditLogDbClient = new AuditLogDatabaseClient();
    // this.siemConnector = new SiemConnector();
  }

  /**
   * Returns the singleton instance of the AuditLogger.
   */
  public static getInstance(): AuditLogger {
    if (!AuditLogger.instance) {
      AuditLogger.instance = new AuditLogger();
    }
    return AuditLogger.instance;
  }

  /**
   * Logs an audit event to the designated immutable log store.
   *
   * @param event The audit event data. The `timestamp` will be automatically added.
   * @returns A Promise that resolves when the log has been successfully recorded.
   * @throws An error if the audit logging mechanism fails, as this is a critical operation.
   */
  public async log(event: Omit<AuditEvent, 'timestamp'>): Promise<void> {
    const fullEvent: AuditEvent = {
      ...event,
      timestamp: new Date().toISOString(),
    };

    try {
      // In a production environment:
      // 1. Send `fullEvent` to a secure, persistent, and immutable storage.
      //    This might involve:
      //    - Writing to an append-only database table.
      //    - Sending to a cloud logging service (e.g., AWS CloudWatch Logs, Google Cloud Logging)
      //      with retention policies.
      //    - Sending to a Security Information and Event Management (SIEM) system.
      // 2. Consider encrypting sensitive data within `details` before logging.
      // 3. Implement robust retry mechanisms or dead-letter queues for logging failures.

      // For demonstration, log to console in JSON format.
      // console.log emphasizes the importance.
      console.log(`[AUDIT_LOG] ${JSON.stringify(fullEvent)}`);

      // Example of an actual integration (conceptual):
      // await this.auditLogDbClient.insert(fullEvent);
      // await this.siemConnector.send(fullEvent);

    } catch (error) {
      // It is CRITICAL to handle audit logging failures.
      // Depending on compliance requirements, this might necessitate:
      // - Alerting operations staff immediately.
      // - Attempting fallback logging (e.g., writing to a local emergency log file).
      // - Even halting the main transaction if audit logging is a strict dependency.
      console.error(
        `[CRITICAL_AUDIT_ERROR] Failed to log audit event: ${JSON.stringify(fullEvent)}. Error:`,
        error
      );
      // Re-throw the error to indicate that a critical operation failed,
      // allowing higher layers to decide on appropriate error handling (e.g., transaction rollback).
      throw new Error(`Audit logging failed for action: ${event.action}. Original error: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Helper method to log a successful audit event.
   * @param action The action performed.
   * @param actorId The ID of the actor.
   * @param entityType The type of entity.
   * @param entityId The ID of the entity.
   * @param details Additional details.
   * @param correlationId Correlation ID for the request.
   * @param sourceIp Source IP address.
   * @param userAgent User-Agent string.
   */
  public async logSuccess(
    action: string,
    actorId?: string,
    entityType?: string,
    entityId?: string,
    details?: Record<string, any>,
    correlationId?: string,
    sourceIp?: string,
    userAgent?: string,
  ): Promise<void> {
    await this.log({
      action,
      actorId,
      entityType,
      entityId,
      status: 'SUCCESS',
      details,
      correlationId,
      sourceIp,
      userAgent,
    });
  }

  /**
   * Helper method to log a failed audit event.
   * @param action The action that failed.
   * @param actorId The ID of the actor.
   * @param entityType The type of entity.
   * @param entityId The ID of the entity.
   * @param errorMessage A descriptive error message.
   * @param details Additional details, including error specifics.
   * @param correlationId Correlation ID for the request.
   * @param sourceIp Source IP address.
   * @param userAgent User-Agent string.
   */
  public async logFailure(
    action: string,
    actorId?: string,
    entityType?: string,
    entityId?: string,
    errorMessage?: string,
    details?: Record<string, any>,
    correlationId?: string,
    sourceIp?: string,
    userAgent?: string,
  ): Promise<void> {
    await this.log({
      action,
      actorId,
      entityType,
      entityId,
      status: 'FAILURE',
      details: { errorMessage, ...details },
      correlationId,
      sourceIp,
      userAgent,
    });
  }

  /**
   * Helper method to log an informational audit event.
   * @param action The informational action.
   * @param actorId The ID of the actor.
   * @param entityType The type of entity.
   * @param entityId The ID of the entity.
   * @param details Additional details.
   * @param correlationId Correlation ID for the request.
   * @param sourceIp Source IP address.
   * @param userAgent User-Agent string.
   */
  public async logInfo(
    action: string,
    actorId?: string,
    entityType?: string,
    entityId?: string,
    details?: Record<string, any>,
    correlationId?: string,
    sourceIp?: string,
    userAgent?: string,
  ): Promise<void> {
    await this.log({
      action,
      actorId,
      entityType,
      entityId,
      status: 'INFO',
      details,
      correlationId,
      sourceIp,
      userAgent,
    });
  }

  /**
   * Helper method to log a warning audit event.
   * @param action The warning action.
   * @param actorId The ID of the actor.
   * @param entityType The type of entity.
   * @param entityId The ID of the entity.
   * @param details Additional details, including warning specifics.
   * @param correlationId Correlation ID for the request.
   * @param sourceIp Source IP address.
   * @param userAgent User-Agent string.
   */
  public async logWarning(
    action: string,
    actorId?: string,
    entityType?: string,
    entityId?: string,
    warningMessage?: string,
    details?: Record<string, any>,
    correlationId?: string,
    sourceIp?: string,
    userAgent?: string,
  ): Promise<void> {
    await this.log({
      action,
      actorId,
      entityType,
      entityId,
      status: 'WARNING',
      details: { warningMessage, ...details },
      correlationId,
      sourceIp,
      userAgent,
    });
  }
}

// Export a singleton instance for convenient usage across the application
export const auditLogger = AuditLogger.getInstance();