import { XMLParser } from 'fast-xml-parser';

/**
 * Interfaces representing the parsed structure of the XML Schema.
 * These match the structure produced by fast-xml-parser given the provided schema format.
 */

interface XmlAttributeType {
    name: string;
    'dt:type'?: string;
    'dt:values'?: string;
    required?: string;
}

interface XmlElementRef {
    type: string;
    minOccurs?: string;
    maxOccurs?: string;
}

interface XmlAttributeRef {
    type: string;
    required?: string;
}

interface XmlGroup {
    element?: XmlElementRef[] | XmlElementRef;
    order?: string;
}

interface XmlElementType {
    name: string;
    content?: string; // e.g., 'eltOnly', 'textOnly', 'empty'
    model?: string;
    order?: string;
    attribute?: XmlAttributeRef[] | XmlAttributeRef;
    element?: XmlElementRef[] | XmlElementRef;
    group?: XmlGroup[] | XmlGroup;
}

interface ParsedSchema {
    Schema?: {
        AttributeType?: XmlAttributeType[];
        ElementType?: XmlElementType[];
    };
    [key: string]: any;
}

export class TypeDefinitionGenerator {
    private parser: XMLParser;

    constructor() {
        this.parser = new XMLParser({
            ignoreAttributes: false,
            attributeNamePrefix: "",
            allowBooleanAttributes: true,
            parseAttributeValue: false, // Keep values as strings to prevent "1.0" -> 1 conversion
            isArray: (tagName) => {
                // Ensure these tags are always parsed as arrays for consistent iteration
                return ["AttributeType", "ElementType", "attribute", "element", "group"].includes(tagName);
            }
        });
    }

    /**
     * Generates TypeScript code containing Zod schemas and type definitions
     * based on the provided XML schema content.
     * @param xmlContent The raw XML string of the schema.
     * @returns A string containing the generated TypeScript code.
     */
    public generate(xmlContent: string): string {
        const parsed = this.parser.parse(xmlContent) as ParsedSchema;
        
        // Find the Schema root. Fast-xml-parser might keep namespace prefixes or unwrapped roots.
        let schema = parsed.Schema;
        if (!schema) {
            const rootKey = Object.keys(parsed).find(k => k.endsWith(":Schema") || k === "Schema");
            if (rootKey) schema = parsed[rootKey];
        }

        if (!schema) {
            throw new Error("Invalid Schema: Could not locate root <Schema> element.");
        }

        const attributeTypes: XmlAttributeType[] = schema.AttributeType || [];
        const elementTypes: XmlElementType[] = schema.ElementType || [];

        const output: string[] = [];
        
        // --- Header ---
        output.push(`import { z } from 'zod';`);
        output.push(``);
        output.push(`// ---------------------------------------------------------------------------`);
        output.push(`// Auto-generated TypeScript definitions and Zod schemas`);
        output.push(`// Generated by TypeDefinitionGenerator`);
        output.push(`// ---------------------------------------------------------------------------`);
        output.push(``);

        // --- 1. Attribute Schemas (Primitives & Enums) ---
        // Map attribute names to their generated Zod schema variable names
        const attrSchemaMap = new Map<string, string>();

        output.push(`// --- Attribute Types ---`);
        attributeTypes.forEach(attr => {
            const safeName = this.toPascalCase(attr.name);
            const schemaName = `${safeName}AttributeSchema`;
            attrSchemaMap.set(attr.name, schemaName);

            const zodDef = this.mapAttributeToZod(attr);
            
            output.push(`export const ${schemaName} = ${zodDef};`);
            output.push(`export type ${safeName}Attribute = z.infer<typeof ${schemaName}>;`);
            output.push(``);
        });

        // --- 2. Element Schemas (Complex Objects) ---
        const definedElementNames = new Set(elementTypes.map(e => e.name));
        
        output.push(`// --- Element Types ---`);
        elementTypes.forEach(el => {
            const safeName = this.toPascalCase(el.name);
            const schemaName = `${safeName}Schema`;
            const typeName = safeName;

            output.push(`export const ${schemaName} = z.object({`);

            // Handle XML Attributes mapped to Object Properties
            if (el.attribute) {
                const attributes = Array.isArray(el.attribute) ? el.attribute : [el.attribute];
                attributes.forEach(attrRef => {
                    const attrName = attrRef.type;
                    const propKey = this.toCamelCase(attrName);
                    // Use the pre-defined attribute schema or fallback to string
                    const refSchema = attrSchemaMap.get(attrName) || "z.string()";
                    const isRequired = attrRef.required === "yes";

                    output.push(`    ${propKey}: ${refSchema}${isRequired ? "" : ".optional()"},`);
                });
            }

            // Handle Child Elements mapped to Object Properties
            const children = this.flattenChildElements(el);
            children.forEach(child => {
                const childName = child.type;
                const propKey = this.toCamelCase(childName);
                const childSchemaName = `${this.toPascalCase(childName)}Schema`;
                
                // Cardinality
                const minOccurs = child.minOccurs ? parseInt(child.minOccurs, 10) : 1;
                const maxOccursStr = child.maxOccurs || "1";
                const isArray = maxOccursStr === "*" || parseInt(maxOccursStr, 10) > 1;
                const isOptional = minOccurs === 0;

                // Resolve Schema Reference
                // Use z.lazy to handle circular references or hoisting issues
                let zodType = definedElementNames.has(childName)
                    ? `z.lazy(() => ${childSchemaName})`
                    : `z.unknown()`; // Fallback for undefined elements

                if (isArray) {
                    zodType = `z.array(${zodType})`;
                    if (isOptional) zodType += `.optional()`;
                } else {
                    if (isOptional) zodType += `.optional()`;
                }

                output.push(`    ${propKey}: ${zodType},`);
            });

            // Handle Text Content (textOnly)
            // If an element has attributes AND text content, the text is usually in a special property (e.g., _text)
            if (el.content === "textOnly") {
                output.push(`    _text: z.string().optional(),`);
            }

            output.push(`});`);
            output.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
            output.push(``);
        });

        return output.join("\n");
    }

    private mapAttributeToZod(attr: XmlAttributeType): string {
        const type = attr['dt:type'];
        const values = attr['dt:values'];

        // Handle Enumerations
        if (type === 'enumeration' && values) {
            // "yes no" -> ["yes", "no"]
            const enumValues = values.split(/\s+/).map(v => `"${v}"`).join(', ');
            return `z.enum([${enumValues}])`;
        }

        // Handle Primitives
        switch (type) {
            case 'string': return 'z.string()';
            case 'ui1':
            case 'ui2':
            case 'ui4':
            case 'ui8':
            case 'int':
            case 'i1':
            case 'i2':
            case 'i4':
                return 'z.number().int()';
            case 'float':
            case 'r4':
            case 'r8':
            case 'fixed.14.4':
                return 'z.number()';
            case 'boolean': return 'z.boolean()';
            case 'bin.hex': 
            case 'bin.base64':
                return 'z.string()'; // Treat binary as encoded strings
            case 'uuid': return 'z.string().uuid()';
            case 'uri': return 'z.string().url()';
            default: return 'z.string()'; // Conservative fallback
        }
    }

    private flattenChildElements(el: XmlElementType): XmlElementRef[] {
        const refs: XmlElementRef[] = [];

        // Direct elements
        if (el.element) {
            const elements = Array.isArray(el.element) ? el.element : [el.element];
            refs.push(...elements);
        }

        // Groups (sequences, etc.) flattened for simplified Zod object mapping
        if (el.group) {
            const groups = Array.isArray(el.group) ? el.group : [el.group];
            groups.forEach(g => {
                if (g.element) {
                    const gElements = Array.isArray(g.element) ? g.element : [g.element];
                    refs.push(...gElements);
                }
            });
        }

        return refs;
    }

    private toPascalCase(str: string): string {
        if (!str) return "";
        return str.charAt(0).toUpperCase() + str.slice(1).replace(/[^a-zA-Z0-9_]/g, '');
    }

    private toCamelCase(str: string): string {
        if (!str) return "";
        return str.charAt(0).toLowerCase() + str.slice(1).replace(/[^a-zA-Z0-9_]/g, '');
    }
}