import { Schema, model, Document } from 'mongoose';

/**
 * @interface G_Plan
 * @description Defines the core structure for a subscription plan.
 * This interface represents the data shape expected for a plan,
 * both for input and output from the database.
 */
export interface G_Plan {
  _id?: string; // Mongoose ObjectId, optional as it's generated by MongoDB
  name: string; // Unique name for the plan (e.g., "Basic", "Premium", "Enterprise")
  description: string; // A brief, informative description of what the plan offers
  price: number; // The monetary cost of the plan (e.g., 9.99). Stored as a decimal.
  currency: string; // ISO 4217 currency code (e.g., "USD", "EUR").
  interval: 'day' | 'week' | 'month' | 'year'; // The billing period interval.
  intervalCount: number; // The number of intervals (e.g., 1 for "every month", 3 for "every 3 months").
  features: string[]; // An array of strings describing key features included in the plan.
  isActive: boolean; // A boolean indicating if the plan is currently active and available for subscription.
  metadata?: Record<string, any>; // A flexible field for storing additional, unstructured plan data.
  createdAt?: Date; // Timestamp when the plan was created. Automatically managed by Mongoose.
  updatedAt?: Date; // Timestamp when the plan was last updated. Automatically managed by Mongoose.
}

/**
 * @interface AD_PlanDocument
 * @description Extends the G_Plan interface with Mongoose's Document properties.
 * This provides full type safety when working with Mongoose query results and instances.
 */
export interface AD_PlanDocument extends G_Plan, Document {}

/**
 * @const AD_PlanSchema
 * @description Mongoose Schema definition for the AD_Plan (Subscription Plan) model.
 * This schema maps the G_Plan interface to a MongoDB collection structure,
 * including validation rules and indexing.
 */
const AD_PlanSchema = new Schema<AD_PlanDocument>({
  name: {
    type: String,
    required: [true, 'Plan name is required.'],
    trim: true,
    unique: true, // Ensures that each plan has a unique name
    minlength: [3, 'Plan name must be at least 3 characters long.'],
    maxlength: [100, 'Plan name cannot exceed 100 characters.'],
  },
  description: {
    type: String,
    required: [true, 'Plan description is required.'],
    trim: true,
    minlength: [10, 'Plan description must be at least 10 characters long.'],
    maxlength: [500, 'Plan description cannot exceed 500 characters.'],
  },
  price: {
    type: Number,
    required: [true, 'Plan price is required.'],
    min: [0, 'Price cannot be negative.'], // Price must be zero or positive
    // For production-grade financial applications, consider using a dedicated
    // decimal type library or storing prices in the smallest currency unit (e.g., cents).
  },
  currency: {
    type: String,
    required: [true, 'Currency is required.'],
    trim: true,
    uppercase: true,
    // A common subset of ISO 4217 currency codes. Expand this enum as needed
    // based on the supported currencies for your application.
    enum: ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', 'BRL', 'RUB', 'SGD', 'HKD'],
    message: '{VALUE} is not a supported currency code.',
  },
  interval: {
    type: String,
    required: [true, 'Billing interval is required.'],
    enum: ['day', 'week', 'month', 'year'],
    message: '{VALUE} is not a valid billing interval. Must be day, week, month, or year.',
  },
  intervalCount: {
    type: Number,
    required: [true, 'Interval count is required.'],
    min: [1, 'Interval count must be at least 1.'], // e.g., every 1 month, every 3 months
    // Max value can be adjusted based on business logic (e.g., 12 for months/years)
  },
  features: {
    type: [String], // An array of strings
    default: [], // Defaults to an empty array if no features are provided
  },
  isActive: {
    type: Boolean,
    default: true, // Plans are active by default upon creation
  },
  metadata: {
    type: Schema.Types.Mixed, // Allows for flexible, unstructured key-value pairs
    default: {}, // Defaults to an empty object
  },
}, {
  timestamps: true, // Mongoose automatically adds `createdAt` and `updatedAt` fields
  collection: 'ad_plans', // Explicitly names the MongoDB collection for this model
});

/**
 * @const AD_PlanModel
 * @description Mongoose Model for interacting with the 'ad_plans' collection in MongoDB.
 * This model provides the interface for CRUD operations on subscription plan documents.
 */
const AD_PlanModel = model<AD_PlanDocument>('AD_Plan', AD_PlanSchema);

export default AD_PlanModel;