import { Schema, model, Document } from 'mongoose';

/**
 * @interface P_TaxRate
 * @description Defines the properties of a tax rate.
 * This interface represents the plain object structure for a tax rate,
 * useful for DTOs or API payloads.
 */
export interface P_TaxRate {
  _id?: string; // Optional, as it's generated by MongoDB
  name: string; // e.g., "VAT", "Sales Tax CA"
  rate: number; // The tax rate as a decimal (e.g., 0.05 for 5%)
  countryCode: string; // ISO 3166-1 alpha-2 country code (e.g., "US", "DE")
  stateProvinceCode?: string; // Optional, e.g., "CA" for California, "NY" for New York
  zipPostalCode?: string; // Optional, specific postal code for localized taxes
  effectiveDate: Date; // The date from which this tax rate is active
  expirationDate?: Date; // Optional, the date when this tax rate expires
  isDefault: boolean; // True if this is the default tax rate for its region/country
  description?: string; // A brief description of the tax rate
  createdAt?: Date; // Automatically managed by Mongoose timestamps
  updatedAt?: Date; // Automatically managed by Mongoose timestamps
}

/**
 * @interface AL_TaxRateDocument
 * @description Extends P_TaxRate with Mongoose Document properties.
 * This interface represents a tax rate document as stored in MongoDB,
 * including Mongoose-specific methods and properties.
 */
export interface AL_TaxRateDocument extends P_TaxRate, Document {
  _id: string; // Mongoose documents always have an _id
}

/**
 * @const AL_TaxRateSchema
 * @description Mongoose schema definition for the AL_TaxRate model.
 * Defines the structure, types, validations, and indexes for tax rate documents
 * in the MongoDB collection.
 */
const AL_TaxRateSchema = new Schema<AL_TaxRateDocument>({
  name: {
    type: String,
    required: [true, 'Tax rate name is required.'],
    trim: true,
    minlength: [2, 'Tax rate name must be at least 2 characters long.'],
    maxlength: [100, 'Tax rate name cannot exceed 100 characters.'],
  },
  rate: {
    type: Number,
    required: [true, 'Tax rate percentage is required.'],
    min: [0, 'Tax rate cannot be negative.'],
    max: [1, 'Tax rate cannot exceed 100% (1.0).'], // Stored as a decimal (e.g., 0.05 for 5%)
  },
  countryCode: {
    type: String,
    required: [true, 'Country code is required.'],
    trim: true,
    uppercase: true,
    minlength: [2, 'Country code must be 2 characters (ISO 3166-1 alpha-2).'],
    maxlength: [2, 'Country code must be 2 characters (ISO 3166-1 alpha-2).'],
  },
  stateProvinceCode: {
    type: String,
    trim: true,
    uppercase: true,
    minlength: [2, 'State/Province code must be at least 2 characters.'],
    maxlength: [3, 'State/Province code cannot exceed 3 characters.'],
    required: false,
  },
  zipPostalCode: {
    type: String,
    trim: true,
    maxlength: [10, 'Zip/Postal code cannot exceed 10 characters.'],
    required: false,
  },
  effectiveDate: {
    type: Date,
    required: [true, 'Effective date is required.'],
  },
  expirationDate: {
    type: Date,
    required: false,
    validate: {
      validator: function (this: AL_TaxRateDocument, value: Date | undefined) {
        // If an expiration date is provided, it must be on or after the effective date.
        if (value && this.effectiveDate) {
          return value >= this.effectiveDate;
        }
        return true; // No expiration date, or no effective date yet, so valid.
      },
      message: 'Expiration date must be on or after the effective date.',
    },
  },
  isDefault: {
    type: Boolean,
    required: [true, 'Default status is required.'],
    default: false,
  },
  description: {
    type: String,
    trim: true,
    maxlength: [500, 'Description cannot exceed 500 characters.'],
    required: false,
  },
}, {
  timestamps: true, // Automatically adds createdAt and updatedAt fields
  collection: 'al_taxrates', // Explicitly names the MongoDB collection
});

// Add indexes for efficient querying
// Index for finding tax rates by location and effective date (most recent first)
AL_TaxRateSchema.index({ countryCode: 1, stateProvinceCode: 1, zipPostalCode: 1, effectiveDate: -1 });
// Index for finding default tax rates by country
AL_TaxRateSchema.index({ countryCode: 1, isDefault: 1 });
// Index for querying active tax rates within a date range
AL_TaxRateSchema.index({ effectiveDate: 1, expirationDate: 1 });

/**
 * @const AL_TaxRateModel
 * @description Mongoose model for the 'al_taxrates' collection.
 * Provides an interface for interacting with the tax rate data in MongoDB.
 */
const AL_TaxRateModel = model<AL_TaxRateDocument>('AL_TaxRate', AL_TaxRateSchema);

export default AL_TaxRateModel;