import * as crypto from 'crypto';

/**
 * DataVault provides client-side encryption utilities for securely storing sensitive
 * fields and keys using AES-256-GCM authentication encryption.
 */
export class DataVault {
    private readonly algorithm: string = 'aes-256-gcm';
    private readonly encryptionKey: Buffer;

    /**
     * Initializes the DataVault with a master secret.
     * @param secret A high-entropy string used to derive the 32-byte encryption key.
     */
    constructor(secret: string) {
        if (!secret) {
            throw new Error('DataVault requires a secret key for initialization.');
        }
        // Ensure the key is exactly 32 bytes by hashing the secret
        this.encryptionKey = crypto.createHash('sha256').update(secret).digest();
    }

    /**
     * Encrypts a plaintext string.
     * @param text The sensitive string to encrypt.
     * @returns A distinct string containing the IV, AuthTag, and Encrypted Data separated by colons.
     */
    public encrypt(text: string): string {
        try {
            const iv = crypto.randomBytes(16); // Initialization Vector
            const cipher = crypto.createCipheriv(this.algorithm, this.encryptionKey, iv);

            let encrypted = cipher.update(text, 'utf8', 'hex');
            encrypted += cipher.final('hex');

            const authTag = cipher.getAuthTag();

            // Format: iv:authTag:encryptedData
            return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
        } catch (err) {
            throw new Error(`Encryption failed: ${(err as Error).message}`);
        }
    }

    /**
     * Decrypts a ciphertext string generated by the encrypt method.
     * @param encryptedData The string containing IV, AuthTag, and Encrypted Data.
     * @returns The original plaintext string.
     */
    public decrypt(encryptedData: string): string {
        try {
            const parts = encryptedData.split(':');
            if (parts.length !== 3) {
                throw new Error('Invalid encrypted data format. Expected iv:authTag:data');
            }

            const [ivHex, authTagHex, encryptedHex] = parts;

            const iv = Buffer.from(ivHex, 'hex');
            const authTag = Buffer.from(authTagHex, 'hex');

            const decipher = crypto.createDecipheriv(this.algorithm, this.encryptionKey, iv);
            decipher.setAuthTag(authTag);

            let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
            decrypted += decipher.final('utf8');

            return decrypted;
        } catch (err) {
            throw new Error(`Decryption failed: ${(err as Error).message}`);
        }
    }

    /**
     * Encrypts a JSON serializable object.
     * @param data The object to encrypt.
     * @returns The encrypted string representation.
     */
    public encryptObject(data: Record<string, any>): string {
        return this.encrypt(JSON.stringify(data));
    }

    /**
     * Decrypts a string back into a JSON object.
     * @param encryptedData The encrypted string.
     * @returns The original object.
     */
    public decryptObject<T = Record<string, any>>(encryptedData: string): T {
        const decryptedText = this.decrypt(encryptedData);
        return JSON.parse(decryptedText) as T;
    }
}